apiVersion: v1
data:
  Corp-Issuing-CA01-G2.pem: {{ .Values.extraObjects.cert }}
kind: Secret
metadata:
  name: acme-ca
  namespace: {{ include "cert-manager.namespace" . }}
type: Opaque
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: mercedes-benz-acme
  namespace: {{ include "cert-manager.namespace" . }}
spec:
  acme:
    server: https://acme.app.corpintra.net/acme/ws/Acme.svc/InternalWebserverACME/directory
    email: dna@mercedes-benz.com
    privateKeySecretRef:
      name: mercedes-benz-acme
    solvers:
    - http01:
        ingress:
          ingressClassName: ingress-traefik
