apiVersion: v1
kind: Secret
metadata:
  name: argocd-vault-plugin-credentials
  namespace: argocd
data:
  AVP_AUTH_TYPE: 
  AVP_K8S_ROLE: 
  AVP_TYPE: 
  VAULT_ADDR: 
  VAULT_NAMESPACE:
  VAULT_SKIP_VERIFY:
type: Opaque
