replicaCount: 2
envs: []
secret: []
image:
  repository: registry-emea.app.corpintra.net/dnaplatform/dss-backend
  pullPolicy: IfNotPresent
  tag: 1.0.7
imagePullSecrets: []
nameOverride: ''
fullnameOverride: dss-be
namespace: dss
serviceAccount:
  create: false
  annotations: {}
  name: ''
podAnnotations: {}
podSecurityContext:
  runAsUser: 1000
containerPort: 7777
securityContext: {}
service:
  type: ClusterIP
  port: 7777
ingress:
  enabled: false
  host: api.dss.dna.app.corpintra.net
  annotations:
    traefik.frontend.rule.type: PathPrefix
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: 'true'
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: daimler-acme
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect@kubernetescrd
  hosts:
    - host: api.dss.dna.app.corpintra.net
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - api.dss.dna.app.corpintra.net
      secretName: api-dss-tls-secret
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
vaultInjector:
  enable: true
  annotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/role: dna
    vault.hashicorp.com/tls-skip-verify: 'true'
    vault.hashicorp.com/namespace: fmas/prod
    vault.hashicorp.com/agent-pre-populate-only: 'true'
    vault.hashicorp.com/agent-inject-secret-envvar: kv/dna/kubernetesSecret/dssService
    vault.hashicorp.com/agent-inject-template-envvar: |
      {{- with secret "kv/dna/kubernetesSecret/dssService" -}}
        {{- range $k, $v := .Data.data }}
            export {{ $k }}="{{ $v }}"
        {{- end }}
      {{- end }}        
  saName: default
  jarName: dataiku-backend-lib-1.0.0-all.jar
podDisruptionBudget:
  enabled: true
  minAvailable: 50%
