const getInjectedEnv = (key) => {
    if (window.CODE_SPACE_INJECTED_ENVIRONMENT) {
      return window.CODE_SPACE_INJECTED_ENVIRONMENT[key];
    }
    return undefined;
  };
  
  // const getDNAInjectedEnv = (key) => {
  //   if (window.INJECTED_ENVIRONMENT) {
  //     return window.INJECTED_ENVIRONMENT[key];
  //   }
  //   return undefined;
  // };
  
  export const Envs = {
    CODE_SPACE_API_BASEURL: getInjectedEnv('CODE_SPACE_API_BASEURL') || process.env.CODE_SPACE_API_BASEURL,
    API_BASEURL: getInjectedEnv('API_BASEURL') || process.env.API_BASEURL,
    CODE_SPACE_GIT_PAT_APP_URL: getInjectedEnv('CODE_SPACE_GIT_PAT_APP_URL') || process.env.CODE_SPACE_GIT_PAT_APP_URL,
    CODE_SPACE_GIT_ORG_NAME: getInjectedEnv('CODE_SPACE_GIT_ORG_NAME') || process.env.CODE_SPACE_GIT_ORG_NAME,
    CODESPACE_OPENSEARCH_LOGS_URL: getInjectedEnv('CODESPACE_OPENSEARCH_LOGS_URL') || process.env.CODESPACE_OPENSEARCH_LOGS_URL,
    CODESPACE_OPENSEARCH_BUILD_LOGS_URL: getInjectedEnv('CODESPACE_OPENSEARCH_BUILD_LOGS_URL') || process.env.CODESPACE_OPENSEARCH_BUILD_LOGS_URL,
    CODESPACE_OIDC_POPUP_URL: getInjectedEnv('CODESPACE_OIDC_POPUP_URL') || process.env.CODESPACE_OIDC_POPUP_URL,
    CODESPACE_AWS_POPUP_URL: getInjectedEnv('CODESPACE_AWS_POPUP_URL') || process.env.CODESPACE_AWS_POPUP_URL,
    CODESPACE_OIDC_POPUP_WAIT_TIME: getInjectedEnv('CODESPACE_OIDC_POPUP_WAIT_TIME') || process.env.CODESPACE_OIDC_POPUP_WAIT_TIME,
    REPORTS_API_BASEURL: getInjectedEnv('REPORTS_API_BASEURL') || process.env.REPORTS_API_BASEURL,
    STORAGE_API_BASEURL: getInjectedEnv('STORAGE_API_BASEURL') || process.env.STORAGE_API_BASEURL,
    VAULT_API_BASEURL: getInjectedEnv('VAULT_API_BASEURL') || process.env.VAULT_API_BASEURL,
    CODESPACE_HARDWARE_REQUEST_TEMPLATE: getInjectedEnv('CODESPACE_HARDWARE_REQUEST_TEMPLATE') || process.env.CODESPACE_HARDWARE_REQUEST_TEMPLATE,
    CODESPACE_SOFTWARE_REQUEST_TEMPLATE:getInjectedEnv('CODESPACE_SOFTWARE_REQUEST_TEMPLATE') || process.env.CODESPACE_SOFTWARE_REQUEST_TEMPLATE,
    CODESPACE_TUTORIALS_BASE_URL:getInjectedEnv('CODESPACE_TUTORIALS_BASE_URL') || process.env.CODESPACE_TUTORIALS_BASE_URL,
    CODESPACE_RECIEPES_ENABLE_README: getInjectedEnv('CODESPACE_RECIEPES_ENABLE_README') || process.env.CODESPACE_RECIEPES_ENABLE_README,
    SHOW_AWS_MIGRATION_WARNING: getInjectedEnv('SHOW_AWS_MIGRATION_WARNING') || process.env.SHOW_AWS_MIGRATION_WARNING,
    AWS_PROGRESS_API_URL: getInjectedEnv('AWS_PROGRESS_API_URL') || process.env.AWS_PROGRESS_API_URL,
    SHOW_ON_PREM_START: getInjectedEnv('SHOW_ON_PREM_START') || process.env.SHOW_ON_PREM_START,
    CODESPACE_AWS_OPENSEARCH_BUILD_LOGS_URL: getInjectedEnv('CODESPACE_AWS_OPENSEARCH_BUILD_LOGS_URL') || process.env.CODESPACE_AWS_OPENSEARCH_BUILD_LOGS_URL,
    CODESPACE_AWS_OPENSEARCH_LOGS_URL: getInjectedEnv('CODESPACE_AWS_OPENSEARCH_LOGS_URL') || process.env.CODESPACE_AWS_OPENSEARCH_LOGS_URL,
    AWS_MOVE_DOC_URL: getInjectedEnv('AWS_MOVE_DOC_URL') || process.env.AWS_MOVE_DOC_URL,
    CODESPACE_TEAMS_LINK: getInjectedEnv('CODESPACE_TEAMS_LINK') || process.env.CODESPACE_TEAMS_LINK,
    MONITORING_DASHBOARD_BASE_URL: getInjectedEnv('MONITORING_DASHBOARD_BASE_URL') || process.env.MONITORING_DASHBOARD_BASE_URL,
    CODESPACE_MATTERMOST_LINK: getInjectedEnv('CODESPACE_MATTERMOST_LINK') || process.env.CODESPACE_MATTERMOST_LINK,
  };