#!/usr/bin/env bash
LC_ALL=C

localBranchName="$(git rev-parse --abbrev-ref HEAD)"

validBranchRegex="^(dev|main|((feature|task|bugfix|hotfix|docs|improvement)\/[a-z0-9._-]+))$"

msg="Your local branch name doesn't not adhere to our policy. Rename the your branch, starting with feature|task|bugfix|hotfix|docs|improvement followed by '/<<your_branch_name>>'. Eg: feature/myBranch"

if [[ ! $localBranchName =~ $validBranchRegex ]]
then
    echo "$msg"
    exit 1
fi

exit 0