insert into entityid_nsql(id,data) values
('1','{"entityId":"3790","entityName":"1886 Ventures GmbH"}'),
('2','{"entityId":"2249","entityName":"8 VC Fund I, L.P."}'),
('3','{"entityId":"2790","entityName":"8VC Fund II, L.P."}'),
('4','{"entityId":"3711","entityName":"8VC Fund III, L.P."}'),
('5','{"entityId":"4112","entityName":"8VC Fund IV L.P."}'),
('6','{"entityId":"4092","entityName":"8VC Opportunities Fund II, L.P."}'),
('7','{"entityId":"829","entityName":"Accumotive GmbH & Co. KG"}'),
('8','{"entityId":"6198","entityName":"Accumotive Verwaltungs-GmbH"}'),
('9','{"entityId":"2233","entityName":"AEG Olympia Office GmbH"}'),
('10','{"entityId":"784","entityName":"AFCC Automotive Fuel Cell Cooperation Corp."}'),
('11','{"entityId":"546","entityName":"Aichi Corporation"}'),
('12','{"entityId":"132","entityName":"Akanko Bus Center Co., Ltd."}'),
('13','{"entityId":"440","entityName":"AKTIO HOLDINGS CORPORATION"}'),
('14','{"entityId":"2305","entityName":"Alpha 4 Mercedes-Benz Grundstücksverwaltung GmbH & Co. OHG"}'),
('15','{"entityId":"2378","entityName":"Alpha 5 Mercedes-Benz Grundstücksverwaltung GmbH & Co. OHG"}'),
('16','{"entityId":"1917","entityName":"Alpha 7 Mercedes-Benz Grundstücksverwaltung GmbH & Co. OHG"}'),
('17','{"entityId":"470","entityName":"Amagi Godo Unyu Co., Ltd."}'),
('18','{"entityId":"2784","entityName":"Anagog Ltd."}'),
('19','{"entityId":"1621","entityName":"Anota Fahrzeug Service- und Vertriebsgesellschaft mbH"}'),
('20','{"entityId":"8010","entityName":"Apex.AI Inc."}'),
('21','{"entityId":"647","entityName":"Asagami Corp."}'),
('22','{"entityId":"128","entityName":"Asahikawa Denki Kido Co., Ltd."}'),
('23','{"entityId":"3307","entityName":"Aston Martin Lagonda Global Holdings Plc"}'),
('24','{"entityId":"5320","entityName":"Athlon Beheer International B.V."}'),
('25','{"entityId":"5323","entityName":"Athlon Car Lease Belgium N.V."}'),
('26','{"entityId":"5310","entityName":"Athlon Car Lease International B.V."}'),
('27','{"entityId":"5329","entityName":"Athlon Car Lease Italy S.R.L."}'),
('28','{"entityId":"5313","entityName":"Athlon Car Lease Nederland B.V."}'),
('29','{"entityId":"5336","entityName":"Athlon Car Lease Polska Sp. z o.o."}'),
('30','{"entityId":"5335","entityName":"Athlon Car Lease Portugal, lda"}'),
('31','{"entityId":"5312","entityName":"Athlon Car Lease Rental Services B.V."}'),
('32','{"entityId":"5325","entityName":"Athlon Car Lease Rental Services Belgium N.V."}'),
('33','{"entityId":"5331","entityName":"Athlon Car Lease S.A.S."}'),
('34','{"entityId":"5321","entityName":"Athlon Car Lease Spain, S.A."}'),
('35','{"entityId":"5330","entityName":"Athlon France S.A.S."}'),
('36','{"entityId":"5326","entityName":"Athlon Germany GmbH"}'),
('37','{"entityId":"5322","entityName":"Athlon Mobility Consultancy N.V."}'),
('38','{"entityId":"9943","entityName":"Athlon Mobility Services UK Limited"}'),
('39','{"entityId":"5327","entityName":"Athlon Rental Germany GmbH"}'),
('40','{"entityId":"5324","entityName":"Athlon Sweden AB"}'),
('41','{"entityId":"5334","entityName":"Athlon Switzerland AG i.L."}'),
('42','{"entityId":"6951","entityName":"Atlantis Foundries (Pty.) Ltd."}'),
('43','{"entityId":"6886","entityName":"Atomico IV, L.P."}'),
('44','{"entityId":"4300","entityName":"Automotive Cells Company SE"}'),
('45','{"entityId":"2833","entityName":"BAIC BluePark New Energy Technology Co.,Ltd"}'),
('46','{"entityId":"29","entityName":"BAIC Motor Corporation Ltd."}'),
('47','{"entityId":"1759","entityName":"Balderton Capital VI, S.L.P."}'),
('48','{"entityId":"1443","entityName":"Banco Mercedes-Benz do Brasil S.A."}'),
('49','{"entityId":"785","entityName":"BDF IP Holdings Ltd."}'),
('50','{"entityId":"2747","entityName":"Beat Chile SpA"}'),
('51','{"entityId":"3698","entityName":"BEAT Mobility Services Single Member Societe Anonyme"}'),
('52','{"entityId":"2858","entityName":"Beat Ride App Colombia S.A.S"}'),
('53','{"entityId":"3357","entityName":"Beat Ride App S.A."}'),
('54','{"entityId":"1854","entityName":"Beijing Benz Automotive Co., Ltd."}'),
('55','{"entityId":"8885","entityName":"Beijing Foton Daimler Automotive Co., Ltd"}'),
('56','{"entityId":"4843","entityName":"Beijing Mercedes-Benz Sales Service Co., Ltd."}'),
('57','{"entityId":"88","entityName":"Blacklane GmbH"}'),
('58','{"entityId":"2796","entityName":"Blaize Inc."}'),
('59','{"entityId":"3182","entityName":"Bolt Technology OÜ"}'),
('60','{"entityId":"165","entityName":"Brooklands Estates Management Limited"}'),
('61','{"entityId":"3052","entityName":"Campo Largo Comercio de Veículos e Peças Ltda."}'),
('62','{"entityId":"2655","entityName":"Capital Factory 5, L.P."}'),
('63','{"entityId":"819","entityName":"car2go Belgium SPRL"}'),
('64','{"entityId":"3277","entityName":"car2go Canada Ltd."}'),
('65','{"entityId":"296","entityName":"car2go Group GmbH"}'),
('66','{"entityId":"3291","entityName":"car2go Iberia S.L.U."}'),
('67','{"entityId":"4799","entityName":"car2go Italia S.R.L."}'),
('68','{"entityId":"3101","entityName":"car2go N.A. Holding Inc."}'),
('69','{"entityId":"884","entityName":"car2go N.A. LLC"}'),
('70','{"entityId":"3294","entityName":"car2go Nederland B.V."}'),
('71','{"entityId":"3293","entityName":"car2go Österreich GmbH"}'),
('72','{"entityId":"9621","entityName":"CARS Technik & Logistik GmbH"}'),
('73','{"entityId":"3593","entityName":"carwow Ltd."}'),
('74','{"entityId":"2773","entityName":"Catapult Ventures I, L.P."}'),
('75','{"entityId":"3723","entityName":"cellcentric Fuel Cell Canada Inc"}'),
('76','{"entityId":"3722","entityName":"cellcentric GmbH & Co. KG"}'),
('77','{"entityId":"3536","entityName":"cellcentric Verwaltungsgesellschaft mbH"}'),
('78','{"entityId":"436","entityName":"Central Japan International Airport Co., Ltd."}'),
('79','{"entityId":"3838","entityName":"ChargePoint Holdings Inc."}'),
('80','{"entityId":"4840","entityName":"Chichibuno Mori Country Club, Ltd."}'),
('81','{"entityId":"770","entityName":"CHOREN Industries GmbH"}'),
('82','{"entityId":"1941","entityName":"Circulo Cerrado S.A. de Ahorro para Fines Determinados"}'),
('83','{"entityId":"2571","entityName":"Clever Tech S.R.L."}'),
('84','{"entityId":"2583","entityName":"Clever Tech Sud S.R.L."}'),
('85','{"entityId":"3247","entityName":"CLIDET NO 1048 (Proprietary) Limited"}'),
('86','{"entityId":"8000","entityName":"Cloudgeeks GmbH"}'),
('87','{"entityId":"8009","entityName":"CLOUDGEEKS, UNIPESSOAL LDA"}'),
('88','{"entityId":"2382","entityName":"COBUS Industries GmbH"}'),
('89','{"entityId":"8018","entityName":"Commercial Vehicle Charging Europe BV"}'),
('90','{"entityId":"814","entityName":"Commercial Vehicle Cluster - Nutzfahrzeug GmbH"}'),
('91','{"entityId":"384","entityName":"Cooperation Manufacturing Plant Aguascalientes, S.A.P.I de C.V."}'),
('92','{"entityId":"4100","entityName":"Cúspide Daimler Trucks & Buses GmbH"}'),
('93','{"entityId":"830","entityName":"Cúspide GmbH"}'),
('94','{"entityId":"3209","entityName":"DAF Investments, Ltd."}'),
('95','{"entityId":"221","entityName":"Daimler AG & Co. Anlagenverwaltung OHG"}'),
('96','{"entityId":"1611","entityName":"Daimler Australia/Pacific Pty. Ltd."}'),
('97','{"entityId":"739","entityName":"Daimler Automotive de Venezuela C.A."}'),
('98','{"entityId":"3608","entityName":"Daimler Buses North America Inc."}'),
('99','{"entityId":"3206","entityName":"Daimler Capital Services LLC"}'),
('100','{"entityId":"3190","entityName":"Daimler Coaches North America LLC"}'),
('101','{"entityId":"4920","entityName":"Daimler Colombia S. A."}'),
('102','{"entityId":"8666","entityName":"Daimler Commercial Vehicles (Thailand) Ltd."}'),
('103','{"entityId":"793","entityName":"Daimler Commercial Vehicles Africa Ltd."}'),
('104','{"entityId":"757","entityName":"Daimler Commercial Vehicles MENA FZE"}'),
('105','{"entityId":"848","entityName":"Daimler Commercial Vehicles South East Asia Pte. Ltd."}'),
('106','{"entityId":"2470","entityName":"Daimler Financial Services Africa & Asia Pacific Ltd."}'),
('107','{"entityId":"3250","entityName":"Daimler Financial Services India Private Limited"}'),
('108','{"entityId":"720","entityName":"Daimler Financial Services México, S. de R.L. de C.V."}'),
('109','{"entityId":"1788","entityName":"Daimler Financial Services, S.A. de C.V., S.O.F.O.M., E.N.R."}'),
('110','{"entityId":"2460","entityName":"Daimler Fleet Management GmbH"}'),
('111','{"entityId":"2746","entityName":"Daimler Fleet Management Singapore Pte. Ltd."}'),
('112','{"entityId":"1119","entityName":"Daimler Fleet Management South Africa (Pty.) Ltd. i. L."}'),
('113','{"entityId":"4124","entityName":"Daimler Gastronomie GmbH"}'),
('114','{"entityId":"2943","entityName":"Daimler Greater China Ltd."}'),
('115','{"entityId":"4126","entityName":"Daimler Group Services Berlin GmbH"}'),
('116','{"entityId":"1889","entityName":"Daimler Group Services Madrid, S.A.U."}'),
('117','{"entityId":"804","entityName":"Daimler India Commercial Vehicles Private Limited"}'),
('118','{"entityId":"875","entityName":"DAIMLER KAMAZ RUS OOO"}'),
('119','{"entityId":"874","entityName":"Daimler Kamaz Trucks Holding GmbH"}'),
('120','{"entityId":"2676","entityName":"Daimler Ladungsträger GmbH"}'),
('121','{"entityId":"2722","entityName":"Daimler Manufactura, S. de R.L. de C.V."}'),
('122','{"entityId":"712","entityName":"Daimler Mexico, S.A. de C.V."}'),
('123','{"entityId":"8858","entityName":"Daimler Mobility & Technology Service Co., Ltd."}'),
('124','{"entityId":"8886","entityName":"Daimler Northeast Asia Parts Trading and Services Co., Ltd."}'),
('125','{"entityId":"2660","entityName":"Daimler Pension Trust e.V."}'),
('126','{"entityId":"3110","entityName":"Daimler Pensionsfonds AG"}'),
('127','{"entityId":"721","entityName":"DAIMLER SERVICIOS CORPORATIVOS MEXICO S. DE R.L. DE C.V."}'),
('128','{"entityId":"4147","entityName":"Daimler Sigorta Aracilik Hizmetleri A.S."}'),
('129','{"entityId":"1401","entityName":"Daimler South East Asia Pte. Ltd."}'),
('130','{"entityId":"4184","entityName":"Daimler Truck & Bus Slovakia s.r.o."}'),
('131','{"entityId":"2725","entityName":"Daimler Truck AG"}'),
('132','{"entityId":"6888","entityName":"Daimler Truck Australia Pacific Pty Ltd"}'),
('133','{"entityId":"4379","entityName":"Daimler Truck Canada Ltd."}'),
('134','{"entityId":"8866","entityName":"Daimler Truck China Limited"}'),
('135','{"entityId":"758","entityName":"Daimler Truck Finance Canada Inc."}'),
('136','{"entityId":"4042","entityName":"Daimler Truck Finance North America LLC"}'),
('137','{"entityId":"3892","entityName":"Daimler Truck Financial Services Asia Co., Ltd."}'),
('138','{"entityId":"3881","entityName":"DAIMLER TRUCK FINANCIAL SERVICES AUSTRALIA PTY LTD"}'),
('139','{"entityId":"3889","entityName":"Daimler Truck Financial Services Belgium NV"}'),
('140','{"entityId":"1302","entityName":"Daimler Truck Financial Services Brasil Holding S.A."}'),
('141','{"entityId":"3872","entityName":"Daimler Truck Financial Services Canada Corporation"}'),
('142','{"entityId":"3849","entityName":"Daimler Truck Financial Services Deutschland GmbH"}'),
('143','{"entityId":"4049","entityName":"Daimler Truck Financial Services España, E.F.C., S.A.U."}'),
('144','{"entityId":"3848","entityName":"Daimler Truck Financial Services GmbH"}'),
('145','{"entityId":"4054","entityName":"Daimler Truck Financial Services Italia S.p.A"}'),
('146','{"entityId":"3888","entityName":"Daimler Truck Financial Services Nederland B.V."}'),
('147','{"entityId":"3882","entityName":"Daimler Truck Financial Services South Africa (Pty) Ltd"}'),
('148','{"entityId":"3883","entityName":"Daimler Truck Financial Services UK Limited"}'),
('149','{"entityId":"3871","entityName":"Daimler Truck Financial Services USA LLC"}'),
('150','{"entityId":"3956","entityName":"Daimler Truck Holding AG"}'),
('151','{"entityId":"5740","entityName":"DAIMLER TRUCK HOLDING AUSTRALIA PACIFIC PTY LTD"}'),
('152','{"entityId":"4068","entityName":"Daimler Truck Innovation Center India Private Limited"}'),
('153','{"entityId":"4131","entityName":"Daimler Truck Insurance Agency LLC"}'),
('154','{"entityId":"4152","entityName":"Daimler Truck International Assignment Services LLC"}'),
('155','{"entityId":"4041","entityName":"Daimler Truck International Finance B.V."}'),
('156','{"entityId":"3850","entityName":"Daimler Truck MENA Holding GmbH"}'),
('157','{"entityId":"1331","entityName":"Daimler Truck North America LLC"}'),
('158','{"entityId":"4132","entityName":"Daimler Truck Pension Trust e.V."}'),
('159','{"entityId":"4053","entityName":"Daimler Truck Renting España S.A."}'),
('160','{"entityId":"4182","entityName":"Daimler Truck Retail Italia S.r.l."}'),
('161','{"entityId":"8016","entityName":"Daimler Truck Retail Polska Sp.zo.o."}'),
('162','{"entityId":"8012","entityName":"Daimler Truck Retail Portugal, Unipessoal Lda."}'),
('163','{"entityId":"4058","entityName":"Daimler Truck Services France S.A."}'),
('164','{"entityId":"861","entityName":"Daimler Truck Southern Africa Ltd"}'),
('165','{"entityId":"2707","entityName":"Daimler Truck Vermögens- und Beteiligungsgesellschaft mbH"}'),
('166','{"entityId":"3621","entityName":"Daimler Truck Verwaltungsgesellschaft für Grundbesitz mbH"}'),
('167','{"entityId":"3591","entityName":"Daimler Trucks & Buses US Holding LLC"}'),
('168','{"entityId":"4753","entityName":"Daimler Trucks and Buses (China) Ltd."}'),
('169','{"entityId":"82","entityName":"Daimler Trucks Asia Taiwan Ltd."}'),
('170','{"entityId":"8524","entityName":"Daimler Trucks Korea Ltd."}'),
('171','{"entityId":"1966","entityName":"Daimler Trucks Remarketing Corporation"}'),
('172','{"entityId":"501","entityName":"Daimler Unterstützungskasse GmbH"}'),
('173','{"entityId":"869","entityName":"Daimler Vans USA, LLC"}'),
('174','{"entityId":"1411","entityName":"Daimler Vehículos Comerciales Mexico, S. de R.L. de C.V."}'),
('175','{"entityId":"2713","entityName":"Daimler Vermögens- und Beteiligungsgesellschaft mbH"}'),
('176','{"entityId":"2310","entityName":"Delta Mercedes-Benz Grundstücksverwaltung GmbH & Co. OHG"}'),
('177','{"entityId":"1957","entityName":"Detroit Diesel Corporation"}'),
('178','{"entityId":"350","entityName":"Detroit Diesel Remanufacturing LLC"}'),
('179','{"entityId":"1652","entityName":"Deutsches Forschungszentrum für künstliche Intelligenz GmbH"}'),
('180','{"entityId":"2865","entityName":"Digital Charging Solutions GmbH"}'),
('181','{"entityId":"116","entityName":"Donan Bus Co., Ltd."}'),
('182','{"entityId":"6651","entityName":"Dreizehnte Vermögensverwaltungsgesellschaft DVB mbH"}'),
('183','{"entityId":"8017","entityName":"Dritte Neptun Vermögensverwaltungsgesellschaft mbH"}'),
('184','{"entityId":"3096","entityName":"DriveNow Belgium SPRL"}'),
('185','{"entityId":"3089","entityName":"DriveNow Sverige AB"}'),
('186','{"entityId":"3098","entityName":"DriveNow UK Limited i.L."}'),
('187','{"entityId":"3079","entityName":"DriveNow Verwaltungs GmbH"}'),
('188','{"entityId":"3262","entityName":"DTB Tech & Data Hub, Unipessoal Lda"}'),
('189','{"entityId":"3764","entityName":"DTFC Holding GmbH"}'),
('190','{"entityId":"1668","entityName":"Earlybird DWES Fund VI GmbH & Co. KG"}'),
('191','{"entityId":"4045","entityName":"Earlybird DWES Fund VII GmbH & Co. KG"}'),
('192','{"entityId":"7278","entityName":"EHG Elektroholding GmbH"}'),
('193','{"entityId":"780","entityName":"Enbase Power GmbH"}'),
('194','{"entityId":"660","entityName":"Enshyu Tetsudo Co., Ltd."}'),
('195','{"entityId":"2311","entityName":"Epsilon Mercedes-Benz Grundstücksverwaltung GmbH & Co. OHG"}'),
('196','{"entityId":"601","entityName":"Esslinger Wohnungsbau GmbH"}'),
('197','{"entityId":"182","entityName":"European Center for Information and Communication Technologies - EICT GmbH"}'),
('198','{"entityId":"1248","entityName":"EvoBus (Schweiz) AG"}'),
('199','{"entityId":"1233","entityName":"EvoBus (U.K.) Ltd."}'),
('200','{"entityId":"1218","entityName":"EvoBus Austria GmbH"}'),
('201','{"entityId":"1249","entityName":"EvoBus Belgium N.V."}'),
('202','{"entityId":"9984","entityName":"EvoBus Ceská republika s.r.o."}'),
('203','{"entityId":"1389","entityName":"EvoBus Danmark A/S"}'),
('204','{"entityId":"1217","entityName":"EvoBus France S.A.S.U."}'),
('205','{"entityId":"245","entityName":"EvoBus GmbH"}'),
('206','{"entityId":"9930","entityName":"EvoBus Ibérica, S.A.U."}'),
('207','{"entityId":"1221","entityName":"EvoBus Italia S.p.A."}'),
('208','{"entityId":"1263","entityName":"EvoBus Nederland B.V."}'),
('209','{"entityId":"9987","entityName":"EvoBus Polska Sp. z o.o."}'),
('210','{"entityId":"3836","entityName":"EvoBus Portugal, S.A."}'),
('211','{"entityId":"9989","entityName":"EvoBus Reunion S. A."}'),
('212','{"entityId":"2870","entityName":"EvoBus Russland OOO"}'),
('213','{"entityId":"2431","entityName":"EvoBus Sverige AB"}'),
('214','{"entityId":"4767","entityName":"F Tec Co., Ltd."}'),
('215','{"entityId":"4284","entityName":"Factorial Inc."}'),
('216','{"entityId":"3749","entityName":"Farasis Energy (Ganzhou) Co., Ltd."}'),
('217','{"entityId":"2414","entityName":"FinTech Collective Fund II L.P."}'),
('218','{"entityId":"3522","entityName":"Fleetboard Logistics GmbH"}'),
('219','{"entityId":"28","entityName":"Flix SE"}'),
('220','{"entityId":"2398","entityName":"Freightliner Custom Chassis Corporation"}'),
('221','{"entityId":"5318","entityName":"Friesland Lease B.V."}'),
('222','{"entityId":"249","entityName":"Fujian Benz Automotive Co., Ltd."}'),
('223','{"entityId":"835","entityName":"Fundo Garantidor para Investimentos - FGI"}'),
('224','{"entityId":"650","entityName":"Fushiki Kairiku Unso Co. Ltd."}'),
('225','{"entityId":"521","entityName":"FUSO LAND TRANSPORT & Co. Ltd."}'),
('226','{"entityId":"4314","entityName":"FYI.FYI Inc."}'),
('227','{"entityId":"4016","entityName":"G2VP I, LLC"}'),
('228','{"entityId":"3807","entityName":"G2VP II, LLC"}'),
('229','{"entityId":"1181","entityName":"Grundstücksgesellschaft Schlossplatz 1 mbH & Co. KG"}'),
('230','{"entityId":"2302","entityName":"Grundstücksverwaltungsgesellschaft Daimler AG & Co. Alpha 1 OHG"}'),
('231','{"entityId":"2303","entityName":"Grundstücksverwaltungsgesellschaft Daimler AG & Co. Alpha 2 OHG"}'),
('232','{"entityId":"2304","entityName":"Grundstücksverwaltungsgesellschaft Daimler AG & Co. Alpha 3 OHG"}'),
('233','{"entityId":"1817","entityName":"Grundstücksverwaltungsgesellschaft Daimler AG & Co. Alpha 6 OHG"}'),
('234','{"entityId":"2307","entityName":"Grundstücksverwaltungsgesellschaft Daimler AG & Co. Gamma 1 OHG"}'),
('235','{"entityId":"2308","entityName":"Grundstücksverwaltungsgesellschaft Daimler AG & Co. Gamma 2 OHG"}'),
('236','{"entityId":"2309","entityName":"Grundstücksverwaltungsgesellschaft Daimler AG & Co. Gamma 3 OHG"}'),
('237','{"entityId":"6655","entityName":"Grundstücksverwaltungsgesellschaft Daimler AG & Co. Gamma 4 OHG"}'),
('238','{"entityId":"1872","entityName":"Grundstücksverwaltungsgesellschaft EvoBus GmbH & Co. OHG"}'),
('239','{"entityId":"4089","entityName":"H2 Green Steel AB"}'),
('240','{"entityId":"730","entityName":"H2 Mobility Deutschland GmbH & Co. KG"}'),
('241','{"entityId":"711","entityName":"H2 Mobility Deutschland Verwaltungs GmbH"}'),
('242','{"entityId":"6636","entityName":"Hailo Network Iberia S.L."}'),
('243','{"entityId":"6638","entityName":"Hailo Network IP Limited"}'),
('244','{"entityId":"3461","entityName":"Hamilton Bio Ventures, L.P."}'),
('245','{"entityId":"591","entityName":"Hankyu Hanshin Holdings Inc."}'),
('246','{"entityId":"3260","entityName":"hap2U SAS"}'),
('247','{"entityId":"897","entityName":"Here International B.V."}'),
('248','{"entityId":"4196","entityName":"High Definition Vehicle Insurance Inc."}'),
('249','{"entityId":"710","entityName":"High-Tech Gründerfonds GmbH & Co. KG"}'),
('250','{"entityId":"4554","entityName":"High-Tech Gründerfonds II GmbH & Co. KG"}'),
('251','{"entityId":"587","entityName":"Hiroshima Electric Railway Co., Ltd."}'),
('252','{"entityId":"447","entityName":"Hiroshima Rikuso co., Ltd."}'),
('253','{"entityId":"643","entityName":"Hokkaido Chuo Bus Co., Ltd."}'),
('254','{"entityId":"126","entityName":"Hokkaido Tuun Co., Ltd."}'),
('255','{"entityId":"662","entityName":"Hokuriku Railroad Co., Ltd."}'),
('256','{"entityId":"4790","entityName":"Hubject GmbH"}'),
('257','{"entityId":"598","entityName":"Hutech norin Co., Ltd."}'),
('258','{"entityId":"188","entityName":"Ibarakiken Jidosya Kaikan Co., Ltd."}'),
('259','{"entityId":"190","entityName":"Ibarakiken Jidosya Toroku Center Co., Ltd."}'),
('260','{"entityId":"3231","entityName":"Immuta, Inc."}'),
('261','{"entityId":"4760","entityName":"Intelligent Apps GmbH"}'),
('262','{"entityId":"5328","entityName":"Interleasing Luxembourg S.A."}'),
('263','{"entityId":"3324","entityName":"IONITY GmbH"}'),
('264','{"entityId":"858","entityName":"IONITY Holding GmbH & Co. KG"}'),
('265','{"entityId":"3331","entityName":"IONITY Management GmbH"}'),
('266','{"entityId":"2960","entityName":"Isuzu Motors Limited"}'),
('267','{"entityId":"3585","entityName":"IVU Traffic Technologies AG"}'),
('268','{"entityId":"448","entityName":"Iwami Kotsu Co., Ltd."}'),
('269','{"entityId":"282","entityName":"Izu Hakone Railway Co., Ltd."}'),
('270','{"entityId":"125","entityName":"Justice Co., Ltd."}'),
('271','{"entityId":"654","entityName":"K.R.S. (Kyuso Ryutsu System) Corp."}'),
('272','{"entityId":"487","entityName":"Kagoshimaken Jidosya Kaikan Co., Ltd."}'),
('273','{"entityId":"841","entityName":"KAMAZ PAO"}'),
('274','{"entityId":"505","entityName":"Kanagawa Chuo Kotsu Co., Ltd."}'),
('275','{"entityId":"519","entityName":"Kanagawa Mitsubishi Fuso Truck & Bus Sales Co., Ltd."}'),
('276','{"entityId":"656","entityName":"Kanamoto Co., Ltd."}'),
('277','{"entityId":"600","entityName":"Kanda Holdings Co., Ltd."}'),
('278','{"entityId":"104","entityName":"Kansai International Airport Co., Ltd."}'),
('279','{"entityId":"198","entityName":"Kanto Bus Co., Ltd."}'),
('280','{"entityId":"98","entityName":"Kawasaki Azalea Co., Ltd."}'),
('281','{"entityId":"578","entityName":"Keikyu Corp."}'),
('282','{"entityId":"580","entityName":"Keisei Electric Railway Co., Ltd."}'),
('283','{"entityId":"166","entityName":"Kirin Holdings Co., Ltd."}'),
('284','{"entityId":"129","entityName":"Kitami Tsuun Co., Ltd"}'),
('285','{"entityId":"276","entityName":"Koei Kanko Co., Ltd."}'),
('286','{"entityId":"4216","entityName":"Koppieview Property (Pty) Ltd"}'),
('287','{"entityId":"137","entityName":"Kushiro Bus Co., Ltd."}'),
('288','{"entityId":"120","entityName":"Kyokuto Kikai Co., Ltd."}'),
('289','{"entityId":"1270","entityName":"Lapland Car Test Aktiebolag"}'),
('290','{"entityId":"2721","entityName":"LEONIE DMS DVB GmbH"}'),
('291','{"entityId":"2821","entityName":"Lerer Hippeau Ventures Select Fund II, LP"}'),
('292','{"entityId":"2823","entityName":"Lerer Hippeau Ventures VI, LP"}'),
('293','{"entityId":"828","entityName":"Li-Tec Battery GmbH"}'),
('294','{"entityId":"4004","entityName":"LICULAR GmbH"}'),
('295','{"entityId":"4044","entityName":"Linse Capital Fund I LP"}'),
('296','{"entityId":"6868","entityName":"LSH Auto International Limited"}'),
('297','{"entityId":"3774","entityName":"Luminar Technologies, Inc."}'),
('298','{"entityId":"6644","entityName":"Magma Venture Capital IV L.P."}'),
('299','{"entityId":"633","entityName":"Maruwn Corp."}'),
('300','{"entityId":"634","entityName":"Maruzen Showa Unyu Co., Ltd."}'),
('301','{"entityId":"2643","entityName":"Mascot Truck Parts Canada Ltd (2017)"}'),
('302','{"entityId":"6641","entityName":"Matternet Inc."}'),
('303','{"entityId":"607","entityName":"MB GTC GmbH Mercedes-Benz Gebrauchtteile Center"}'),
('304','{"entityId":"2771","entityName":"MB Service Japan Co., Ltd."}'),
('305','{"entityId":"3279","entityName":"MBarc Credit Canada Inc."}'),
('306','{"entityId":"2891","entityName":"MBition GmbH"}'),
('307','{"entityId":"4214","entityName":"MBition Sofia EOOD"}'),
('308','{"entityId":"3825","entityName":"MDC Power GmbH"}'),
('309','{"entityId":"285","entityName":"Meitetsu Jidosya Seibi Co., Ltd."}'),
('310','{"entityId":"593","entityName":"Meito Transportation Co., Ltd."}'),
('311','{"entityId":"2133","entityName":"Mercedes AMG High Performance Powertrains Ltd"}'),
('312','{"entityId":"87","entityName":"Mercedes Benz Filo Hizmetleri A.S."}'),
('313','{"entityId":"4046","entityName":"Mercedes Benz Kamyon Finansman A.S"}'),
('314','{"entityId":"3228","entityName":"Mercedes Benz Otomotiv Ticaret ve Hizmetler A.S."}'),
('315','{"entityId":"6647","entityName":"Mercedes pay AG"}'),
('316','{"entityId":"2677","entityName":"Mercedes pay GmbH"}'),
('317','{"entityId":"6648","entityName":"Mercedes pay S.A. – in liquidation"}'),
('318','{"entityId":"3762","entityName":"Mercedes pay USA LLC"}'),
('319','{"entityId":"1581","entityName":"Mercedes ServiceCard Beteiligungsgesellschaft mbH"}'),
('320','{"entityId":"2914","entityName":"Mercedes ServiceCard GmbH & Co. KG"}'),
('321','{"entityId":"1697","entityName":"Mercedes-AMG GmbH"}'),
('322','{"entityId":"734","entityName":"Mercedes-Benz  Insurance Agency LLC"}'),
('323','{"entityId":"854","entityName":"Mercedes-Benz  Retail Receivables LLC"}'),
('324','{"entityId":"2408","entityName":"Mercedes-Benz  Trust Leasing Conduit LLC"}'),
('325','{"entityId":"3647","entityName":"Mercedes-Benz - Aluguer de Veículos, Lda."}'),
('326','{"entityId":"8889","entityName":"Mercedes-Benz (China) Ltd."}'),
('327','{"entityId":"1071","entityName":"Mercedes-Benz (Thailand) Limited"}'),
('328','{"entityId":"2724","entityName":"Mercedes-Benz AG"}'),
('329','{"entityId":"4139","entityName":"Mercedes-Benz Antwerpen N.V."}'),
('330','{"entityId":"1310","entityName":"Mercedes-Benz Argentina S.A.U."}'),
('331','{"entityId":"4123","entityName":"Mercedes-Benz Asia GmbH"}'),
('332','{"entityId":"776","entityName":"Mercedes-Benz Assignment Services Americas, LLC"}'),
('333','{"entityId":"818","entityName":"Mercedes-Benz Assuradeuren B.V."}'),
('334','{"entityId":"1391","entityName":"Mercedes-Benz Australia/Pacific Pty Ltd"}'),
('335','{"entityId":"8887","entityName":"Mercedes-Benz Auto Finance Ltd."}'),
('336','{"entityId":"6639","entityName":"Mercedes-Benz Automotive Mobility GmbH"}'),
('337','{"entityId":"8001","entityName":"Mercedes-Benz Bank AG"}'),
('338','{"entityId":"256","entityName":"Mercedes-Benz Bank GmbH"}'),
('339','{"entityId":"2517","entityName":"Mercedes-Benz Bank Polska S.A. w likwidacji"}'),
('340','{"entityId":"798","entityName":"Mercedes-Benz Bank Rus OOO"}'),
('341','{"entityId":"8302","entityName":"Mercedes-Benz Bank Service Center GmbH"}'),
('342','{"entityId":"2457","entityName":"Mercedes-Benz Banking Service GmbH"}'),
('343','{"entityId":"1241","entityName":"Mercedes-Benz Belgium Luxembourg S.A."}'),
('344','{"entityId":"3804","entityName":"Mercedes-Benz Bordeaux S.A.S."}'),
('345','{"entityId":"3537","entityName":"Mercedes-Benz Broker Argentina S.A."}'),
('346','{"entityId":"3604","entityName":"Mercedes-Benz Broker Biztositási Alkusz Hungary Kft."}'),
('347','{"entityId":"61","entityName":"Mercedes-Benz Brooklands Limited"}'),
('348','{"entityId":"3344","entityName":"Mercedes-Benz Camiones y Buses Argentina SAU."}'),
('349','{"entityId":"1350","entityName":"Mercedes-Benz Canada Inc."}'),
('350','{"entityId":"31","entityName":"Mercedes-Benz Capital Investments B.V."}'),
('351','{"entityId":"3315","entityName":"Mercedes-Benz Capital Nederland B.V."}'),
('352','{"entityId":"515","entityName":"Mercedes-Benz Capital Rus OOO"}'),
('353','{"entityId":"3288","entityName":"Mercedes-Benz Cars & Vans Brasil Ltda."}'),
('354','{"entityId":"821","entityName":"Mercedes-Benz Cars Middle East FZE"}'),
('355','{"entityId":"1230","entityName":"Mercedes-Benz Cars UK Limited"}'),
('356','{"entityId":"1199","entityName":"Mercedes-Benz #eská republika s.r.o."}'),
('357','{"entityId":"1793","entityName":"Mercedes-Benz CharterWay S.A.S."}'),
('358','{"entityId":"3313","entityName":"Mercedes-Benz Compañía Financiera Argentina S.A."}'),
('359','{"entityId":"6003","entityName":"Mercedes-Benz Connectivity Services GmbH"}'),
('360','{"entityId":"234","entityName":"Mercedes-Benz Consulting GmbH"}'),
('361','{"entityId":"790","entityName":"Mercedes-Benz Corporate Investments, LLC"}'),
('362','{"entityId":"1837","entityName":"Mercedes-Benz Corretora de Seguros Ltda"}'),
('363','{"entityId":"7872","entityName":"Mercedes-Benz CPH A/S"}'),
('364','{"entityId":"9921","entityName":"Mercedes-Benz Credit Pénzügyi Szolgáltató Hungary Zrt."}'),
('365','{"entityId":"1225","entityName":"Mercedes-Benz Customer Assistance Center Maastricht N.V."}'),
('366','{"entityId":"8138","entityName":"Mercedes-Benz Customer Solutions GmbH"}'),
('367','{"entityId":"1295","entityName":"Mercedes-Benz Danmark A/S"}'),
('368','{"entityId":"4375","entityName":"Mercedes-Benz Dealer Bedrijven B.V."}'),
('369','{"entityId":"3481","entityName":"Mercedes-Benz do Brasil Assessoria Comercial Ltda."}'),
('370','{"entityId":"1300","entityName":"Mercedes-Benz do Brasil Ltda."}'),
('371','{"entityId":"1773","entityName":"Mercedes-Benz Drogenbos N.V."}'),
('372','{"entityId":"2646","entityName":"Mercedes-Benz Egypt S.A.E."}'),
('373','{"entityId":"403","entityName":"Mercedes-Benz Energy GmbH"}'),
('374','{"entityId":"1200","entityName":"Mercedes-Benz Espana, S.A.U."}'),
('375','{"entityId":"880","entityName":"Mercedes-Benz Europa NV/SA"}'),
('376','{"entityId":"1036","entityName":"Mercedes-Benz ExTra LLC"}'),
('377','{"entityId":"1341","entityName":"Mercedes-Benz Finance Canada Inc."}'),
('378','{"entityId":"1413","entityName":"Mercedes-Benz Finance Co., Ltd."}'),
('379','{"entityId":"733","entityName":"Mercedes-Benz Finance North America LLC"}'),
('380','{"entityId":"2287","entityName":"Mercedes-Benz Financial Services Australia Pty. Ltd."}'),
('381','{"entityId":"1042","entityName":"Mercedes-Benz Financial Services Austria GmbH"}'),
('382','{"entityId":"8204","entityName":"Mercedes-Benz Financial Services BeLux NV"}'),
('383','{"entityId":"709","entityName":"Mercedes-Benz Financial Services Canada Corporation"}'),
('384','{"entityId":"1488","entityName":"Mercedes-Benz Financial Services Ceská republika s.r.o."}'),
('385','{"entityId":"1789","entityName":"Mercedes-Benz Financial Services España, E.F.C., S.A."}'),
('386','{"entityId":"1900","entityName":"Mercedes-Benz Financial Services France S.A."}'),
('387','{"entityId":"2280","entityName":"Mercedes-Benz Financial Services Hong Kong Ltd."}'),
('388','{"entityId":"3325","entityName":"Mercedes-Benz Financial Services Investment Company LLC"}'),
('389','{"entityId":"8203","entityName":"Mercedes-Benz Financial Services Italia S.p.A."}'),
('390','{"entityId":"4052","entityName":"Mercedes-Benz Financial Services Korea Ltd."}'),
('391','{"entityId":"8205","entityName":"Mercedes-Benz Financial Services Nederland B.V."}'),
('392','{"entityId":"9642","entityName":"Mercedes-Benz Financial Services New Zealand Ltd"}'),
('393','{"entityId":"4520","entityName":"Mercedes-Benz Financial Services Portugal - Sociedade Financeira de Crédito S.A."}'),
('394','{"entityId":"2527","entityName":"Mercedes-Benz Financial Services Rus OOO"}'),
('395','{"entityId":"8202","entityName":"Mercedes-Benz Financial Services Schweiz AG"}'),
('396','{"entityId":"2462","entityName":"Mercedes-Benz Financial Services Slovakia s.r.o."}'),
('397','{"entityId":"2372","entityName":"Mercedes-Benz Financial Services South Africa (Pty) Ltd"}'),
('398','{"entityId":"3468","entityName":"Mercedes-Benz Financial Services Sp. zo.o."}'),
('399','{"entityId":"2360","entityName":"Mercedes-Benz Financial Services Taiwan Ltd."}'),
('400','{"entityId":"9950","entityName":"Mercedes-Benz Financial Services UK (Trustees) Ltd"}'),
('401','{"entityId":"1232","entityName":"Mercedes-Benz Financial Services UK Limited"}'),
('402','{"entityId":"708","entityName":"Mercedes-Benz Financial Services USA LLC"}'),
('403','{"entityId":"1786","entityName":"Mercedes-Benz Finans Danmark A/S"}'),
('404','{"entityId":"232","entityName":"Mercedes-Benz Finans Sverige AB"}'),
('405','{"entityId":"3662","entityName":"Mercedes-Benz Finansal Kiralama Türk A.S."}'),
('406','{"entityId":"2941","entityName":"Mercedes-Benz Finansman Türk A.S."}'),
('407','{"entityId":"2673","entityName":"Mercedes-Benz Formula E Limited"}'),
('408','{"entityId":"2404","entityName":"Mercedes-Benz Försäljnings AB"}'),
('409','{"entityId":"1211","entityName":"Mercedes-Benz France S.A.S."}'),
('410','{"entityId":"1292","entityName":"Mercedes-Benz G GmbH"}'),
('411','{"entityId":"9730","entityName":"Mercedes-Benz Grand Prix Ltd."}'),
('412','{"entityId":"400","entityName":"Mercedes-Benz Group AG"}'),
('413','{"entityId":"4534","entityName":"Mercedes-Benz Group Services Phils., Inc."}'),
('414','{"entityId":"1860","entityName":"Mercedes-Benz Grund Services GmbH"}'),
('415','{"entityId":"1290","entityName":"Mercedes-Benz Hellas Single-Member S.A."}'),
('416','{"entityId":"1231","entityName":"Mercedes-Benz Holdings UK Limited"}'),
('417','{"entityId":"1560","entityName":"Mercedes-Benz Hong Kong Limited"}'),
('418','{"entityId":"398","entityName":"Mercedes-Benz Hungária Kft."}'),
('419','{"entityId":"2567","entityName":"Mercedes-Benz IDC Europe S.A.S."}'),
('420','{"entityId":"1414","entityName":"Mercedes-Benz India Private Limited"}'),
('421','{"entityId":"3350","entityName":"Mercedes-Benz Insurance Agency (Beijing) Co., Ltd."}'),
('422','{"entityId":"812","entityName":"Mercedes-Benz Insurance Broker S.R.L."}'),
('423','{"entityId":"1760","entityName":"Mercedes-Benz Insurance Services GmbH"}'),
('424','{"entityId":"2196","entityName":"Mercedes-Benz Insurance Services Nederland B.V."}'),
('425','{"entityId":"9701","entityName":"Mercedes-Benz Insurance Services Taiwan Ltd."}'),
('426','{"entityId":"1048","entityName":"Mercedes-Benz Insurance Services UK Limited"}'),
('427','{"entityId":"2849","entityName":"Mercedes-Benz Intellectual Property GmbH & Co. KG"}'),
('428','{"entityId":"2699","entityName":"Mercedes-Benz Intellectual Property Management GmbH"}'),
('429','{"entityId":"1269","entityName":"Mercedes-Benz International Finance B.V."}'),
('430','{"entityId":"3327","entityName":"Mercedes-Benz Investment Company LLC"}'),
('431','{"entityId":"703","entityName":"Mercedes-Benz Investments North America, LLC"}'),
('432','{"entityId":"1250","entityName":"Mercedes-Benz Italia S.p.A."}'),
('433','{"entityId":"1400","entityName":"Mercedes-Benz Japan Co., Ltd."}'),
('434','{"entityId":"3943","entityName":"Mercedes-Benz Korea Limited"}'),
('435','{"entityId":"2384","entityName":"Mercedes-Benz Lease Italia S.r.l."}'),
('436','{"entityId":"2358","entityName":"Mercedes-Benz Leasing (Thailand) Co., Ltd."}'),
('437','{"entityId":"4735","entityName":"Mercedes-Benz Leasing Co., Ltd."}'),
('438','{"entityId":"3769","entityName":"Mercedes-Benz Leasing Deutschland GmbH"}'),
('439','{"entityId":"8","entityName":"Mercedes-Benz Leasing do Brasil Arrendamento Mercantil S.A."}'),
('440','{"entityId":"8002","entityName":"Mercedes-Benz Leasing GmbH"}'),
('441','{"entityId":"810","entityName":"Mercedes-Benz Leasing IFN S.A."}'),
('442','{"entityId":"2125","entityName":"Mercedes-Benz Leasing Kft."}'),
('443','{"entityId":"2288","entityName":"Mercedes-Benz Leasing Polska Sp. z o.o."}'),
('444','{"entityId":"9696","entityName":"Mercedes-Benz Leasing Treuhand GmbH"}'),
('445','{"entityId":"4227","entityName":"Mercedes-Benz Logistics and Distribution Egypt LLC"}'),
('446','{"entityId":"219","entityName":"Mercedes-Benz Ludwigsfelde GmbH"}'),
('447','{"entityId":"3992","entityName":"Mercedes-Benz Malaysia Sdn. Bhd."}'),
('448','{"entityId":"1337","entityName":"Mercedes-Benz Manhattan, Inc."}'),
('449','{"entityId":"1951","entityName":"Mercedes-Benz Manufacturing (Thailand) Limited"}'),
('450','{"entityId":"4798","entityName":"Mercedes-Benz Manufacturing and Import Egypt"}'),
('451','{"entityId":"809","entityName":"Mercedes-Benz Manufacturing Hungary Kft."}'),
('452','{"entityId":"1667","entityName":"Mercedes-Benz Manufacturing Poland sp. z o. o."}'),
('453','{"entityId":"1748","entityName":"Mercedes-Benz Manufacturing Rus Ltd"}'),
('454','{"entityId":"3467","entityName":"Mercedes-Benz Mechelen N.V."}'),
('455','{"entityId":"706","entityName":"Mercedes-Benz México International, S. de R.L. de C.V."}'),
('456','{"entityId":"8523","entityName":"Mercedes-Benz Mexico, S. de R.L. de C.V."}'),
('457','{"entityId":"2122","entityName":"Mercedes-Benz Mitarbeiter-Fahrzeuge Leasing GmbH"}'),
('458','{"entityId":"8101","entityName":"Mercedes-Benz Mobility AG"}'),
('459','{"entityId":"9245","entityName":"MERCEDES-BENZ MOBILITY AUSTRALIA PTY LTD"}'),
('460','{"entityId":"2712","entityName":"Mercedes-Benz Mobility Beteiligungsgesellschaft mbH"}'),
('461','{"entityId":"3359","entityName":"Mercedes-Benz Mobility Korea Ltd."}'),
('462','{"entityId":"4218","entityName":"MERCEDES-BENZ MOBILITY MEXICO, S. DE R.L. DE C.V."}'),
('463','{"entityId":"774","entityName":"Mercedes-Benz Mobility Services GmbH"}'),
('464','{"entityId":"3781","entityName":"Mercedes-Benz Motorsport Limited"}'),
('465','{"entityId":"3983","entityName":"Mercedes-Benz Museum GmbH"}'),
('466','{"entityId":"1261","entityName":"Mercedes-Benz Nederland B.V."}'),
('467','{"entityId":"863","entityName":"Mercedes-Benz Nederland Holding B.V."}'),
('468','{"entityId":"1938","entityName":"Mercedes-Benz New Zealand Ltd"}'),
('469','{"entityId":"1330","entityName":"Mercedes-Benz North America Corporation"}'),
('470','{"entityId":"1696","entityName":"Mercedes-Benz North America Finance Corporation"}'),
('471','{"entityId":"3530","entityName":"Mercedes-Benz OD GmbH"}'),
('472','{"entityId":"1920","entityName":"Mercedes-Benz Österreich GmbH"}'),
('473','{"entityId":"3845","entityName":"Mercedes-Benz Paris SAS"}'),
('474','{"entityId":"4121","entityName":"Mercedes-Benz Parts Brand GmbH"}'),
('475','{"entityId":"3792","entityName":"Mercedes-Benz Parts Logistics Asia Pacific Sdn. Bhd."}'),
('476','{"entityId":"5166","entityName":"Mercedes-Benz Parts Logistics Eastern Europe s.r.o."}'),
('477','{"entityId":"898","entityName":"Mercedes-Benz Parts Logistics Ibérica, S.L.U."}'),
('478','{"entityId":"1627","entityName":"Mercedes-Benz Parts Logistics UK Limited"}'),
('479','{"entityId":"8689","entityName":"Mercedes-Benz Parts Manufacturing & Services Ltd."}'),
('480','{"entityId":"1975","entityName":"Mercedes-Benz Polska Sp. z.o.o"}'),
('481','{"entityId":"1940","entityName":"Mercedes-Benz Portugal, S.A."}'),
('482','{"entityId":"6660","entityName":"Mercedes-Benz PRAHA s.r.o."}'),
('483','{"entityId":"1339","entityName":"Mercedes-Benz Purchasing Coordination Corporation"}'),
('484','{"entityId":"4129","entityName":"Mercedes-Benz Real Estate GmbH"}'),
('485','{"entityId":"2192","entityName":"Mercedes-Benz Reinsurance S.A. Luxembourg"}'),
('486','{"entityId":"4702","entityName":"Mercedes-Benz Renting, S.A."}'),
('487','{"entityId":"358","entityName":"Mercedes-Benz Research & Development North America, Inc."}'),
('488','{"entityId":"6640","entityName":"Mercedes-Benz Research & Development Tel Aviv Ltd."}'),
('489','{"entityId":"2370","entityName":"Mercedes-Benz Research and Development India Private Limited"}'),
('490','{"entityId":"876","entityName":"Mercedes-Benz Retail Belgium NV/SA"}'),
('491','{"entityId":"1910","entityName":"Mercedes-Benz Retail Group UK Limited"}'),
('492','{"entityId":"1890","entityName":"Mercedes-Benz Retail, S.A."}'),
('493','{"entityId":"3953","entityName":"Mercedes-Benz Retail, Unipessoal Lda."}'),
('494','{"entityId":"1658","entityName":"Mercedes-Benz Risk Solutions South Africa (Pty.) Ltd."}'),
('495','{"entityId":"4086","entityName":"Mercedes-Benz Roma S.p.A."}'),
('496','{"entityId":"509","entityName":"Mercedes-Benz Romania S.R.L."}'),
('497','{"entityId":"1220","entityName":"Mercedes-Benz Russia AO"}'),
('498','{"entityId":"1280","entityName":"Mercedes-Benz Schweiz AG"}'),
('499','{"entityId":"807","entityName":"Mercedes-Benz Service Leasing S.R.L."}'),
('500','{"entityId":"2752","entityName":"Mercedes-Benz Services Correduria de Seguros, S.A."}'),
('501','{"entityId":"4545","entityName":"Mercedes-Benz Services Malaysia Sdn Bhd"}'),
('502','{"entityId":"3542","entityName":"Mercedes-Benz Servicios S.A.U"}'),
('503','{"entityId":"3062","entityName":"Mercedes-Benz Sigorta Aracilik Hizmetleri A.S."}'),
('504','{"entityId":"2609","entityName":"Mercedes-Benz Slovakia s.r.o."}'),
('505','{"entityId":"9605","entityName":"Mercedes-Benz Sosnowiec Sp. z o.o."}'),
('506','{"entityId":"1360","entityName":"Mercedes-Benz South Africa Ltd"}'),
('507','{"entityId":"3183","entityName":"Mercedes-Benz Subscription Services USA LLC"}'),
('508','{"entityId":"1271","entityName":"Mercedes-Benz Sverige AB"}'),
('509','{"entityId":"3742","entityName":"Mercedes-Benz Taiwan Ltd."}'),
('510','{"entityId":"9953","entityName":"Mercedes-Benz Tech Innovation GmbH"}'),
('511','{"entityId":"3426","entityName":"Mercedes-Benz Tech Motion GmbH"}'),
('512','{"entityId":"3586","entityName":"Mercedes-Benz Trucks & Buses Romania S.R.L."}'),
('513','{"entityId":"870","entityName":"Mercedes-Benz Trucks Belgium Luxembourg NV/SA"}'),
('514','{"entityId":"881","entityName":"Mercedes-Benz Trucks Center Sint-Pieters-Leeuw NV/SA"}'),
('515','{"entityId":"1025","entityName":"Mercedes-Benz Trucks Ceská republika s.r.o."}'),
('516','{"entityId":"900","entityName":"Mercedes-Benz Trucks España, S.L.U."}'),
('517','{"entityId":"886","entityName":"Mercedes-Benz Trucks France S.A.S.U"}'),
('518','{"entityId":"1005","entityName":"Mercedes-Benz Trucks Italia S.r.l."}'),
('519','{"entityId":"1893","entityName":"Mercedes-Benz Trucks Molsheim SASU"}'),
('520','{"entityId":"866","entityName":"Mercedes-Benz Trucks Nederland B.V."}'),
('521','{"entityId":"3472","entityName":"Mercedes-Benz Trucks Österreich GmbH"}'),
('522','{"entityId":"893","entityName":"MERCEDES-BENZ TRUCKS POLSKA SPÓ#KA Z OGRANICZONA ODPOWIEDZIALNOSCIA"}'),
('523','{"entityId":"3588","entityName":"Mercedes-Benz Trucks Portugal, S.A."}'),
('524','{"entityId":"887","entityName":"Mercedes-Benz Trucks Schweiz AG"}'),
('525','{"entityId":"1078","entityName":"Mercedes-Benz Trucks UK Limited"}'),
('526','{"entityId":"840","entityName":"Mercedes-Benz Trust Holdings LLC"}'),
('527','{"entityId":"827","entityName":"Mercedes-Benz Trust Leasing LLC"}'),
('528','{"entityId":"1402","entityName":"Mercedes-Benz Türk A.S."}'),
('529','{"entityId":"1333","entityName":"Mercedes-Benz U.S. International, Inc."}'),
('530','{"entityId":"3406","entityName":"Mercedes-Benz Ubezpieczenia Sp. z o.o."}'),
('531','{"entityId":"141","entityName":"Mercedes-Benz UK Share Trustee Ltd."}'),
('532','{"entityId":"1907","entityName":"Mercedes-Benz UK Trustees Limited"}'),
('533','{"entityId":"1336","entityName":"Mercedes-Benz USA, LLC"}'),
('534','{"entityId":"19","entityName":"Mercedes-Benz V.I. Lyon SAS"}'),
('535','{"entityId":"3846","entityName":"Mercedes-Benz V.I. Paris Ile de France SAS"}'),
('536','{"entityId":"4525","entityName":"Mercedes-Benz Vans Hong Kong Limited"}'),
('537','{"entityId":"2734","entityName":"Mercedes-Benz Vans Mobility, S.L.U."}'),
('538','{"entityId":"1628","entityName":"Mercedes-Benz Vans UK Limited"}'),
('539','{"entityId":"4141","entityName":"Mercedes-Benz Vans, LLC"}'),
('540','{"entityId":"1306","entityName":"Mercedes-Benz Venezuela S.A."}'),
('541','{"entityId":"2705","entityName":"Mercedes-Benz Vermögens- und Beteiligungsgesellschaft mbH"}'),
('542','{"entityId":"382","entityName":"Mercedes-Benz Versicherung AG"}'),
('543','{"entityId":"1762","entityName":"Mercedes-Benz Versicherungsservice GmbH"}'),
('544','{"entityId":"244","entityName":"Mercedes-Benz Verwaltungsgesellschaft für Grundbesitz mbH"}'),
('545','{"entityId":"1316","entityName":"Mercedes-Benz Vietnam Ltd."}'),
('546','{"entityId":"293","entityName":"Mercedes-Benz Warszawa Sp. z o.o."}'),
('547','{"entityId":"3968","entityName":"Mercedes-Benz Waterloo S.A."}'),
('548','{"entityId":"3673","entityName":"Mercedes-Benz Wavre S.A."}'),
('549','{"entityId":"3878","entityName":"Mercedes-Benz Wemmel N.V."}'),
('550','{"entityId":"4826","entityName":"Mercedes-Benz Wholesale Receivables LLC"}'),
('551','{"entityId":"2619","entityName":"Mercedes-Benz.io GmbH"}'),
('552','{"entityId":"2633","entityName":"Mercedes-Benz.io Portugal Unipessoal Lda."}'),
('553','{"entityId":"3997","entityName":"MFTA Canada, Inc."}'),
('554','{"entityId":"518","entityName":"MFTB Taiwan Co., Ltd."}'),
('555','{"entityId":"595","entityName":"Mie Kotsu Group Holdings, Inc."}'),
('556','{"entityId":"4428","entityName":"Mitsubishi Fuso Bus Manufacturing Co., Ltd."}'),
('557','{"entityId":"4156","entityName":"Mitsubishi Fuso Truck and Bus Corporation"}'),
('558','{"entityId":"3543","entityName":"MITSUBISHI FUSO TRUCK EUROPE - Sociedade Europeia de Automóveis, S.A."}'),
('559','{"entityId":"3546","entityName":"Mitsubishi Fuso Truck of America, Inc."}'),
('560','{"entityId":"146","entityName":"Miyagi Transportation Co., Ltd."}'),
('561','{"entityId":"152","entityName":"Miyagiken Kotsu Kaikan Co., Ltd."}'),
('562','{"entityId":"493","entityName":"Miyakoh Holdings Co., Ltd."}'),
('563','{"entityId":"488","entityName":"Miyazakiken Jidosya Hanbaiten Center Co., Ltd."}'),
('564','{"entityId":"3289","entityName":"Mobility Trader GmbH"}'),
('565','{"entityId":"3620","entityName":"Mobility Trader Holding GmbH"}'),
('566','{"entityId":"3773","entityName":"MolecuLED Ltd."}'),
('567','{"entityId":"2662","entityName":"Momenta Global Limited"}'),
('568','{"entityId":"778","entityName":"Montajes y Estampaciones Metálicas, S.L."}'),
('569','{"entityId":"297","entityName":"moovel Group GmbH"}'),
('570','{"entityId":"3732","entityName":"Movinx GmbH"}'),
('571','{"entityId":"5333","entityName":"Multifleet G.I.E"}'),
('572','{"entityId":"864","entityName":"mytaxi Austria GmbH"}'),
('573','{"entityId":"391","entityName":"myTaxi Iberia SL"}'),
('574','{"entityId":"732","entityName":"MYTAXI ITALIA S.R.L."}'),
('575','{"entityId":"6635","entityName":"mytaxi Network Ireland Ltd."}'),
('576','{"entityId":"6637","entityName":"mytaxi Network Ltd."}'),
('577','{"entityId":"394","entityName":"MYTAXI POLSKA SPÓLKA Z OGRANICZONA ODPOWIEDZIALNOSCIA"}'),
('578','{"entityId":"895","entityName":"mytaxi Portugal Unipessoal LDA"}'),
('579','{"entityId":"1625","entityName":"mytaxi Sweden AB"}'),
('580','{"entityId":"396","entityName":"myTaxi UG"}'),
('581','{"entityId":"392","entityName":"myTaxi UK Ltd."}'),
('582','{"entityId":"390","entityName":"myTaxi USA Inc."}'),
('583','{"entityId":"1113","entityName":"NAG Nationale Automobil-Gesellschaft Aktiengesellschaft"}'),
('584','{"entityId":"481","entityName":"Nagasakiken Jihanren Kaikan Co., Ltd."}'),
('585','{"entityId":"420","entityName":"Nanao Shakenjou Uneikai Co., Ltd."}'),
('586','{"entityId":"494","entityName":"Nangoku Kotsu Co., Ltd."}'),
('587','{"entityId":"592","entityName":"Nankai Electric Railway Co., Ltd."}'),
('588','{"entityId":"1840","entityName":"National Automobile Industry Company Ltd."}'),
('589','{"entityId":"114","entityName":"New A.C.E. Institute Co., Ltd."}'),
('590','{"entityId":"3628","entityName":"NEXT Multimodal GmbH"}'),
('591','{"entityId":"113","entityName":"Nihon Truck Kogyo Co., Ltd."}'),
('592','{"entityId":"582","entityName":"Niigata Kotsu Co., Ltd."}'),
('593','{"entityId":"110","entityName":"Niigata Unyu Co., Ltd."}'),
('594','{"entityId":"628","entityName":"Nippon Express Co., Ltd."}'),
('595','{"entityId":"139","entityName":"Nippon Motors Co., Ltd."}'),
('596','{"entityId":"586","entityName":"Nishi-Nippon Railroad Co., Ltd."}'),
('597','{"entityId":"2479","entityName":"North America Fuel Systems Remanufacturing LLC"}'),
('598','{"entityId":"4538","entityName":"ogotrac S.A.S."}'),
('599','{"entityId":"475","entityName":"Oita Bus Co., Ltd."}'),
('600','{"entityId":"467","entityName":"Oita Kairiku Unso Co., Ltd."}'),
('601','{"entityId":"4435","entityName":"Okayama Mitsubishi Fuso Truck & Bus Sales Co., Ltd."}'),
('602','{"entityId":"4251","entityName":"Omnibus Hungária Kereskedelmi Kft."}'),
('603','{"entityId":"668","entityName":"Omuta Unso Co., Ltd."}'),
('604','{"entityId":"3337","entityName":"Ondine Tech Fund 1 L.P."}'),
('605','{"entityId":"771","entityName":"P.T. Krama Yudha Tiga Berlian Motors"}'),
('606','{"entityId":"1970","entityName":"P.T. Mercedes-Benz Indonesia"}'),
('607','{"entityId":"772","entityName":"P.T. Mitsubishi Krama Yudha Motors and Manufacturing"}'),
('608','{"entityId":"3538","entityName":"PABCO Co., Ltd."}'),
('609','{"entityId":"3977","entityName":"PDB - Partnership for Dummy Technology and Biomechanics GbR"}'),
('610','{"entityId":"472","entityName":"Piano Terminal Nakamura Co., Ltd."}'),
('611','{"entityId":"8014","entityName":"PIPO Mobility Pvt. Ltd."}'),
('612','{"entityId":"2678","entityName":"Pitango Venture Capital Fund VII, L.P."}'),
('613','{"entityId":"3718","entityName":"Platform Science Inc."}'),
('614','{"entityId":"4360","entityName":"Polomex, S.A. de C.V."}'),
('615','{"entityId":"205","entityName":"Porcher & Meffert Grundstücksgesellschaft mbH & Co. Stuttgart OHG"}'),
('616','{"entityId":"4137","entityName":"Power Supply Systems GmbH"}'),
('617','{"entityId":"4306","entityName":"Prologium Holding Inc."}'),
('618','{"entityId":"1675","entityName":"PROSTEP AG"}'),
('619','{"entityId":"3295","entityName":"Proterra Inc."}'),
('620','{"entityId":"742","entityName":"PT Daimler Commercial Vehicles Indonesia"}'),
('621','{"entityId":"3598","entityName":"PT Daimler Commercial Vehicles Manufacturing Indonesia"}'),
('622','{"entityId":"1948","entityName":"PT Mercedes-Benz Distribution Indonesia"}'),
('623','{"entityId":"741","entityName":"Quanergy Systems Inc."}'),
('624','{"entityId":"1922","entityName":"R.T.C. Management Company Limited"}'),
('625','{"entityId":"265","entityName":"RACER Benchmark Group GmbH"}'),
('626','{"entityId":"3988","entityName":"Rally Communitas Corp."}'),
('627','{"entityId":"2871","entityName":"ReachNow LLC"}'),
('628','{"entityId":"2864","entityName":"RepairSmith, Inc."}'),
('629','{"entityId":"3688","entityName":"Ride Hive GmbH"}'),
('630','{"entityId":"3627","entityName":"Ride Hive GmbH"}'),
('631','{"entityId":"3622","entityName":"Ride Hive Operations SLU"}'),
('632','{"entityId":"3691","entityName":"Ride Hive S.R.L."}'),
('633','{"entityId":"3625","entityName":"Ride Hive SAS"}'),
('634','{"entityId":"3650","entityName":"Ride Hive Single Member Private Capital Company"}'),
('635','{"entityId":"3685","entityName":"Ride Hive sp z.o.o."}'),
('636','{"entityId":"3687","entityName":"Ride Hive Unipessoal Lda."}'),
('637','{"entityId":"1751","entityName":"RRE Ventures VII, L.P."}'),
('638','{"entityId":"4038","entityName":"RS Holdings Inc."}'),
('639','{"entityId":"3705","entityName":"ryd GmbH"}'),
('640','{"entityId":"641","entityName":"S Line Co., Ltd."}'),
('641','{"entityId":"4213","entityName":"Sandown Motor Holdings (Pty) Ltd"}'),
('642','{"entityId":"434","entityName":"Sanyo Jidosya Unso Co., Ltd."}'),
('643','{"entityId":"6006","entityName":"Sechste Vermögensverwaltungsgesellschaft Zeus mbH"}'),
('644','{"entityId":"1631","entityName":"Seibu Holdings Inc."}'),
('645','{"entityId":"1835","entityName":"SelecTrucks Comércio de Veículos Ltda"}'),
('646','{"entityId":"4451","entityName":"SelecTrucks of America LLC"}'),
('647','{"entityId":"4468","entityName":"SelecTrucks of Houston LLC"}'),
('648','{"entityId":"4433","entityName":"SelecTrucks of Houston Wholesale LLC"}'),
('649','{"entityId":"4480","entityName":"SelecTrucks of Omaha LLC"}'),
('650','{"entityId":"4399","entityName":"SelecTrucks of Toronto, Inc."}'),
('651','{"entityId":"596","entityName":"Senkon Logistics Co., Ltd."}'),
('652','{"entityId":"3791","entityName":"Sfara Inc."}'),
('653','{"entityId":"3285","entityName":"SHARE NOW GmbH"}'),
('654','{"entityId":"3287","entityName":"Shenzhen DENZA New Energy Automotive Co. Ltd."}'),
('655','{"entityId":"8013","entityName":"Shikoku Mitsubishi Fuso Truck & Bus Sales Co., Ltd"}'),
('656','{"entityId":"258","entityName":"Shinetsu Teiki Jidosya Corp."}'),
('657','{"entityId":"642","entityName":"Shinki Bus Co., Ltd."}'),
('658','{"entityId":"250","entityName":"Shinko Juki Co., Ltd."}'),
('659','{"entityId":"136","entityName":"Shiraoi Sharyo Kougyo Co., Ltd."}'),
('660','{"entityId":"661","entityName":"Shizuoka Tetsudo Co., Ltd."}'),
('661','{"entityId":"275","entityName":"Shizuokaken Jihan Kaikan Co., Ltd."}'),
('662','{"entityId":"3484","entityName":"Sila Nanotechnologies Inc."}'),
('663','{"entityId":"3268","entityName":"Silver Arrow Canada GP Inc."}'),
('664','{"entityId":"3270","entityName":"Silver Arrow Canada LP"}'),
('665','{"entityId":"6688","entityName":"Sinovation Fund III, L.P."}'),
('666','{"entityId":"3346","entityName":"SK Gaming Beteiligungs GmbH"}'),
('667','{"entityId":"3347","entityName":"SK Gaming GmbH & Co. KG"}'),
('668','{"entityId":"121","entityName":"SK Lease Co., Ltd."}'),
('669','{"entityId":"3599","entityName":"smart Automobile Co., Ltd."}'),
('670','{"entityId":"3725","entityName":"Smart Europe GmbH"}'),
('671','{"entityId":"4171","entityName":"SMART MOBILITY PTE. LTD."}'),
('672','{"entityId":"3666","entityName":"smart-BRABUS GmbH i.L."}'),
('673','{"entityId":"3230","entityName":"SoftBank Vision Fund (AIV I) L.P."}'),
('674','{"entityId":"3682","entityName":"Soul Machines Ltd."}'),
('675','{"entityId":"4326","entityName":"SoundHound, AI Inc."}'),
('676','{"entityId":"13","entityName":"Star Assembly SRL"}'),
('677','{"entityId":"3812","entityName":"Star Transmission srl"}'),
('678','{"entityId":"79","entityName":"STARCAM s.r.o."}'),
('679','{"entityId":"407","entityName":"STARKOM, proizvodnja in trgovina d.o.o."}'),
('680','{"entityId":"3648","entityName":"Starship Technologies Holdings, Inc."}'),
('681','{"entityId":"1866","entityName":"Sterling Truck Corporation"}'),
('682','{"entityId":"2679","entityName":"StoreDot Ltd."}'),
('683','{"entityId":"4575","entityName":"Sumperská správa majetku k.s."}'),
('684','{"entityId":"4514","entityName":"T.O.C (Schweiz) AG"}'),
('685','{"entityId":"115","entityName":"Taihei Kogyo Inc."}'),
('686','{"entityId":"99","entityName":"Takebe Tekkousyo Co., Ltd."}'),
('687','{"entityId":"4784","entityName":"TASIAP GmbH"}'),
('688','{"entityId":"417","entityName":"Tateyama Kurobe Kanko Co., Ltd."}'),
('689','{"entityId":"1669","entityName":"Taxibeat Ltd. UK"}'),
('690','{"entityId":"1886","entityName":"Taxibeat Peru S.A."}'),
('691','{"entityId":"1771","entityName":"Taxibeat Teknoloji Hizmetleri A.S."}'),
('692','{"entityId":"3229","entityName":"Teisan Kanko Bus Co., Ltd."}'),
('693','{"entityId":"100","entityName":"Tenryu Holdings Co., Ltd."}'),
('694','{"entityId":"836","entityName":"The Mobility House AG"}'),
('695','{"entityId":"896","entityName":"There Holding B.V."}'),
('696','{"entityId":"2547","entityName":"Thomas Built Buses of Canada Limited"}'),
('697','{"entityId":"1867","entityName":"Thomas Built Buses, Inc."}'),
('698','{"entityId":"2452","entityName":"Toll4Europe GmbH"}'),
('699','{"entityId":"636","entityName":"Tonami Holdings Co., Ltd."}'),
('700','{"entityId":"4186","entityName":"Torc Europe GmbH"}'),
('701','{"entityId":"3592","entityName":"TORC Robotics, Inc."}'),
('702','{"entityId":"451","entityName":"Tottoriken Jidosya Hanbaiten kaikan Co., Ltd."}'),
('703','{"entityId":"107","entityName":"Toyama Chiho Tetsudou Co., Ltd."}'),
('704','{"entityId":"524","entityName":"Toyo Kotsu Co., Ltd."}'),
('705','{"entityId":"2763","entityName":"Transcovo SAS"}'),
('706','{"entityId":"2764","entityName":"Transopco France SAS"}'),
('707','{"entityId":"393","entityName":"Transopco GmbH"}'),
('708','{"entityId":"3264","entityName":"Transopco Portugal Unipessoal Lda."}'),
('709','{"entityId":"3319","entityName":"Transopco UK Ltd."}'),
('710','{"entityId":"2657","entityName":"Trucks Venture Fund 1, LP"}'),
('711','{"entityId":"3614","entityName":"Trucks Venture Fund 2, LP"}'),
('712','{"entityId":"5332","entityName":"Ucafleet S.A.S"}'),
('713','{"entityId":"3734","entityName":"Ukuvela Holdings Proprietary Limited"}'),
('714','{"entityId":"3733","entityName":"Ukuvela Properties (Pty.) Ltd."}'),
('715','{"entityId":"1764","entityName":"Unternehmertum VC Fonds II GmbH & Co. KG"}'),
('716','{"entityId":"2686","entityName":"Verimi GmbH"}'),
('717','{"entityId":"5175","entityName":"VfB Stuttgart 1893 AG"}'),
('718','{"entityId":"3483","entityName":"Vierte Vermögensverwaltung PV GmbH"}'),
('719','{"entityId":"1019","entityName":"Vierzehnte Vermögensverwaltungsgesellschaft DVB mbH"}'),
('720','{"entityId":"2592","entityName":"Volocopter GmbH"}'),
('721','{"entityId":"5319","entityName":"Wagenplan B.V."}'),
('722','{"entityId":"3597","entityName":"Wei Xing Tech. Co., Ltd."}'),
('723','{"entityId":"4797","entityName":"Wellstone Enterprise Co., Ltd."}'),
('724','{"entityId":"3606","entityName":"Western Star Trucks Sales, Inc"}'),
('725','{"entityId":"2770","entityName":"what3words Ltd."}'),
('726','{"entityId":"150","entityName":"X Rentalease Hokuto Co., Ltd."}'),
('727','{"entityId":"453","entityName":"Yamaguchiken Auto Dealers Co., Ltd."}'),
('728','{"entityId":"4845","entityName":"Yamanashi-ken Jidosha Hanbaiten Kaikan, Ltd."}'),
('729','{"entityId":"4102","entityName":"YASA Limited"}'),
('730','{"entityId":"2868","entityName":"YOUR NOW Holding GmbH"}'),
('731','{"entityId":"444","entityName":"Zentan Bus Co., Ltd."}'),
('732','{"entityId":"5317","entityName":"Zuidlease B.V."}'),
('733','{"entityId":"3535","entityName":"Zweite Vermögensverwaltung PV GmbH"}'),
('734','{"entityId":"4127","entityName":"Zweite Vermögensverwaltungsgesellschaft Zeus mbH"}');