export const SESSION_STORAGE_KEYS = {
  JWT: 'jwt',
  PAGINATION_MAX_ITEMS_PER_PAGE: 'paginationMaxItemsPerPage',
};

export const ProvisionSource = {
  FABRIC: 'fabric',
};

export const FLOW_DIAGRAM_TYPES = {
  ROLE: 'ROLE',
  ENTITLEMENT: 'ENTITLEMENT',
  INTERMEDIATE: 'INTERMEDIATE',
  ENTITLEMENT_ROLE: 'ENTITLEMENT_ROLE',
  PRIVILEGE: 'PRIVILEDGE',
  GROUP: 'GROUP',
}

export const FLOW_DIAGRAM_STATES = {
  PENDING: 'PENDING',
  CREATED: 'CREATED',
  ASSIGNED: 'ASSIGNED',
  NULL: null,
}

export const FLOW_DIAGRAM_MEASUREMENTS = {
  NODE_WIDTH: 300,
  NODE_HEIGHT: 62,
  INTERMEDIATE_NODE_WIDTH: 10,
}