apiVersion: v1
kind: Secret
metadata:
  name: vault-agent-injector
  namespace: {{ include "vault.namespace" . }}
  annotations:
    kubernetes.io/service-account.name: {{ template "vault.fullname" . }}-agent-injector
type: kubernetes.io/service-account-token