apiVersion: v1
kind: Secret
metadata:
  name: vault
  namespace: {{ include "vault.namespace" . }}
  annotations:
    kubernetes.io/service-account.name: {{ template "vault.serviceAccount.name" . }}
type: kubernetes.io/service-account-token