---
{{- $accesskey := .Values.storageCredentials.accessKeyId -}}
{{- $secretAccessKey := .Values.storageCredentials.secretAccessKey -}}
{{- $resticKey := .Values.storageCredentials.resticKey -}}
{{- $bucketName := .Values.storageCredentials.bucketName -}}
{{- range $index,$pvc := .Values.backupJob.backupPvc }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $pvcName.pvcName }}
data:
  accessKeyId: {{ $accesskey | base64enc }}  # change me - base 64 encoded AWS access key ID
  secretAccessKey: {{ $secretAccessKey | base64enc }} # change me - base64 encoded AWS secret access key
  resticKey: {{ $resticKey | base64enc }} # change me - base64 encoded encryption key (generate randomly)
  bucketName: {{$bucketName | base64enc }} # change me - prefix your bucket URL with s3:
                                   # e.g. s3:https://s3.eu-west-2.amazonaws.com/example-bucket/pvc-name
type: Opaque
---
{{- end }}