---
{{- if .Values.restoreJob.enabled }}
{{- range $index, $pvc := .Values.restoreJob.restorePvcName }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $pvc.pvcName }}-rs-job
  namespace: {{ $pvc.namespace | quote }}
spec:
  template:
    spec:
      containers:      
      - image: registry-emea.app.corpintra.net/dockerhub/restic/restic:latest
        imagePullPolicy: IfNotPresent
        name: restic
        args:
        - restore
        - latest  # change me, if needed, to restore different snapshot
        - --target
        - {{ $pvc.restorePath }} ## path
        - --insecure-tls
        env:
        - name: RESTIC_REPOSITORY
          valueFrom:
            secretKeyRef:
              name: {{ $pvc.pvcName }}
              key: bucketName
              optional: false
        - name: RESTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              key: resticKey
              name: {{ $pvc.pvcName }}
              optional: false
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: accessKeyId
              name: {{ $pvc.pvcName }}
              optional: false
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: secretAccessKey
              name: {{ $pvc.pvcName }}
              optional: false
        volumeMounts:
        - mountPath: {{ $pvc.restorePath }} ##
          name: backupdata
        - name: backupdata
          mountPath: /.cache          
      restartPolicy: OnFailure
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000            
      volumes:
      - name: backupdata
        persistentVolumeClaim:
          claimName: {{ $pvc.pvcName }}  # change me ## pvc name
---
{{- end }}
{{- end }}