---
{{- if .Values.restoreJob.enabled }}
{{- $accesskey := .Values.storageCredentials.accessKeyId -}}
{{- $secretAccessKey := .Values.storageCredentials.secretAccessKey -}}
{{- $resticKey := .Values.storageCredentials.resticKey -}}
{{- range $index,$pvc := .Values.restoreJob.restorePvc }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $pvc.pvcName }}
  namespace: {{ $pvc.namespace | quote }}
data:
  accessKeyId: {{ $accesskey | b64enc }}  # change me - base 64 encoded AWS access key ID
  secretAccessKey: {{ $secretAccessKey | b64enc }} # change me - base64 encoded AWS secret access key
  resticKey: {{ $resticKey | b64enc }} # change me - base64 encoded encryption key (generate randomly)
type: Opaque
---
{{- end }}
{{- end }}