piVersion: v1
kind: Secret
metadata:
  name: s3-secret
  namespace: {{ .Values.namespace | quote }}
data:
  accessKeyId: {{ .Values.storageCredentials.accessKeyId | b64enc }}  # change me - base 64 encoded AWS access key ID
  secretAccessKey: {{ .Values.storageCredentials.secretAccessKey | b64enc }} # change me - base64 encoded AWS secret access key
  resticKey: {{ .Values.storageCredentials.resticKey | b64enc }} # change me - base64 encoded encryption key (generate randomly)
type: Opaque