openapi: 3.0.1
info:
  title: Db Service
  version: 1.0.0
servers:
- url: https://localhost:8089/api/1.0
tags:
- name: dbService
  description: This service is used to maintain dbService information.
paths:
  /dbService:
    get:
      tags:
      - dbService
      summary: Get all dbService for the user.
      description: Get all dbService for the user.
      operationId: getAll
      parameters:
      - name: offset
        in: query
        description: page number from which listing of dbService should start.
          Offset. Example 2
        schema:
          type: integer
      - name: limit
        in: query
        description: page size to limit the number of dbService, Example 15
        schema:
          type: integer
      responses:
        "201":
          description: Returns message of success or failure
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DbServiceCollectionVO'
        "204":
          description: Fetch complete, no content found.
          content: {}
        "400":
          description: Bad request.
          content: {}
        "401":
          description: Request does not have sufficient credentials.
          content: {}
        "403":
          description: Request is not authorized.
          content: {}
        "405":
          description: Method not allowed
          content: {}
        "500":
          description: Internal error
          content: {}      
    post:
      tags:
      - dbService
      summary: Initialize/Create dbService.
      description: Initialize/Create dbService.
      operationId: createdbService
      requestBody:
        description: Request Body that contains data required to initialize 
          dbService for user
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DbServiceVO'
        required: true
      responses:
        "201":
          description: 'Returns message of success or failure '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InitializeResponseVo'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericMessage'
        "401":
          description: Request does not have sufficient credentials.
          content: {}
        "403":
          description: Request is not authorized.
          content: {}
        "405":
          description: Method not allowed
          content: {}
        "500":
          description: Internal error
          content: {}
      x-codegen-request-body-name: ServiceVO
    patch:
      tags:
      - dbService
      summary: 'edit dbService. '
      description: 'edit dbService '
      operationId: editdbService
      requestBody:
        description: Request Body that contains data required to initialize 
          dbService for user
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DbServiceVO'
        required: true
      responses:
        "201":
          description: 'Returns message of success or failure '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InitializeResponseVo'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericMessage'
        "401":
          description: Request does not have sufficient credentials.
          content: {}
        "403":
          description: Request is not authorized.
          content: {}
        "405":
          description: Method not allowed
          content: {}
        "500":
          description: Internal error
          content: {}
      x-codegen-request-body-name: ServiceVO

  /dbService/{id}:
    get:
      tags:
      - dbService
      summary: Get dbService by id for the user.
      description: Get dbService by id for the user.
      operationId: getById
      parameters:
        - name: id
          in: path
          description: dbService id
          required: true
          schema:
            type: string
      responses:
        "201":
          description: Returns message of success or failure
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InitializeResponseVo'
        "204":
          description: Fetch complete, no content found.
          content: {}
        "400":
          description: Bad request.
          content: {}
        "401":
          description: Request does not have sufficient credentials.
          content: {}
        "403":
          description: Request is not authorized.
          content: {}
        "405":
          description: Method not allowed
          content: {}
        "500":
          description: Internal error
          content: {}
    delete:
      tags:
      - dbService
      summary: Delete dbService by id for the user.
      description: Delete dbService by id for the user.
      operationId: deleteById
      parameters:
        - name: id
          in: path
          description: dbService id
          required: true
          schema:
            type: string
      responses:
        201:
          description: Returns message of success or failure
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericMessage'
        204:
          description: Fetch complete, no content found.
        400:
          description: Bad request.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Method not allowed
        500:
          description: Internal error
    patch:
      tags:
      - dbService
      summary: updateStatus dbService by id for the user.
      description: updateStatus dbService by id for the user.
      operationId: updateStatus
      parameters:
        - name: id
          in: path
          description: dbService id
          required: true
          schema:
            type: string
      responses:
        201:
          description: Returns message of success or failure
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericMessage'
        204:
          description: Fetch complete, no content found.
        400:
          description: Bad request.
        401:
          description: Request does not have sufficient credentials.
        403:
          description: Request is not authorized.
        405:
          description: Method not allowed
        500:
          description: Internal error                  
components:
  schemas:
    DbServiceCollectionVO:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/DbServiceVO'
        count:
          type: integer
          description: "total number of records"    
        success:
          type: string
        errors:
          type: array
          items:
            $ref: '#/components/schemas/MessageDescription'
        warnings:
          type: array
          items:
            $ref: '#/components/schemas/MessageDescription'     

    GovernanceVO:
      type: object
      properties:
        classificationType:
          type: string
          description: Classification type for dbService
        divisionId:
          type: string
          description: division Id for the dbService
        division:
          type: string
          description: division for the dbService
        subDivisionId:
          type: string
          description: sub division Id for the dbService
        subDivision:
          type: string
          description: sub division for the dbService
        department:
          type: string
          description: department for the dbService
        archerId:
          type: string
          description: archerId for the dbService
        procedureID:
          type: string
          description: producerId for the dbService
        tags:
          type: array
          items:
            type: string
        typeOfProject:
          type: string
          description: typeOfProject for the dbService
        piiData:
          type: boolean
          description: If dbService contains personally identifiable information

    GenericMessage:
      type: object
      properties:
        success:
          type: string
        errors:
          type: array
          items:
            $ref: '#/components/schemas/MessageDescription'
        warnings:
          type: array
          items:
            $ref: '#/components/schemas/MessageDescription'

    MessageDescription:
      type: object
      properties:
        message:
          type: string
          description: message

    CreatedByVO:
      type: object
      properties:
        id:
          type: string
          description: ID of user
        firstName:
          type: string
          description: First Name of the user
        lastName:
          type: string
          description: Last Name of the user
        department:
          type: string
          description: Department of the user
        email:
          type: string
          description: E-Mail of the user
        mobileNumber:
          type: string
          description: Mobile number of the user

    DbServiceVO:
      type: object
      properties:
        id: 
          type: string
          description: Unique technical ID of workspace
        dataGovernance:
          $ref: '#/components/schemas/GovernanceVO'
        dbType:
          type: string  
        serviceName:
          type: string
        status:
          type: string  
        dbName:
          type: string  
        projectType:
          type: string
        projectOwner:
          $ref: '#/components/schemas/UserInfoVO'
        description:
          type: string            
        projectCollaborators:
          type: array
          items:
            $ref: '#/components/schemas/UserInfoVO'
        createdOn:
          type: string
          format: date 
        modifiedOn:
          type: string
          format: date 
        modifiedBy:
          $ref: '#/components/schemas/UserInfoVO'        
        port:
          type: string
        credentials:
          type: array
          items:
            $ref: '#/components/schemas/CredentialsVO'  
        url:
          type: string    

    UserInfoVO:
      type: object
      properties:
        id:
          type: string
          description: ID of user
        firstName:
          type: string
          description: First Name of the user
        lastName:
          type: string
          description: Last Name of the user
        department:
          type: string
          description: Department of the user
        email:
          type: string
          description: E-Mail of the user
        mobileNumber:
          type: string
          description: Mobile number of the user 
        gitUserName:
          type: string
          description: git Username
        isAdmin:
          type: boolean
          description: is the user has Admin rights
          default: false
        isApprover:
          type: boolean
          description: does the user have approver rights
          default: false
        isRead:
          type: boolean
          description: is the user has Admin rights
          default: false
        isWrite:
          type: boolean
          description: is the user has Admin rights
          default: false    

    InitializeResponseVo:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/DbServiceVO'
        success:
          type: string
        errors:
          type: array
          items:
            $ref: '#/components/schemas/MessageDescription'
        warnings:
          type: array
          items:
            $ref: '#/components/schemas/MessageDescription'

    CredentialsVO:
      type: object
      properties:
        userName:
          type: string
        password:
          type: string

    SubscriptionkeysVO:
      type: object
      properties:
        privateKey:
          type: string
        publicKey:
          type: string
        userID:
          type: string                


              