# LICENSE START
# 
# MIT License
# 
# Copyright (c) 2019 Daimler TSS GmbH
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# 
# LICENSE END 
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : marketingCommunicationChannel.yaml
#  **
#  ** Module     : core
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  ***REMOVED***
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
  

swagger: "2.0"
info:
 version: "1.0.0"
 title: "core marketingCommunicationChannel Service"
host: "localhost:7171"
basePath: "/api/1.0"
consumes:
 - "application/json"
produces:
 - "application/json"
tags:
 - name: "marketingCommunicationChannels"
   description: "This service is used to maintain marketingCommunicationChannels used in solutions."

schemes:
- "https"

paths:

# path to create a new marketingCommunicationChannel and fetch all valid marketingCommunicationChannels or by intent
#
#  supprorted http methods GET, POST and DELETE 
#
# path example ../marketingCommunicationChannels

 /marketingCommunicationChannels:
  post:
   tags:
    - "marketingCommunicationChannels"
   summary: "Adds a new marketingCommunicationChannels."
   description: "Adds a new non existing marketingCommunicationChannels which is used in providing solution."
   operationId: "create"
   parameters:
    - name: "marketingCommunicationChannelRequestVO" 
      in: "body" 
      description: "Request Body that contains data required for creating a new marketingCommunicationChannel" 
      required: true
      schema:
       $ref: "#/definitions/MarketingCommunicationChannelRequestVO"
   responses:
    201: 
     description: "Returns message of succes or failure " 
     schema:
       $ref: "#/definitions/MarketingCommunicationChannelVO"
    400:
     description: "Bad Request"
     schema:
       $ref: "#/definitions/GenericMessage"
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Method not allowed"
    500:
     description: "Internal error"
  get:
   tags:
    - "marketingCommunicationChannels"
   summary: "Get all available marketingCommunicationChannels."
   description:  "Get all marketingCommunicationChannels. This endpoints will be used to Get all valid available marketingCommunicationChannels maintenance records."
   operationId: "getAll"
   parameters:
        - name: sortOrder
          in: query
          description: Sort marketingCommunicationChannels based on the given order, example asc,desc
          required: false
          type: string   
          enum: [asc,desc]
   responses:
    201:
     description: "Returns message of succes or failure"
     schema:
       $ref: "#/definitions/MarketingCommunicationChannelCollection"
    204:
      description: "Fetch complete, no content found."
    400:
     description: "Bad request."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Method not allowed"
    500:
     description: "Internal error"

  put:
    tags:
    - "marketingCommunicationChannels"
    summary: "Update the marketingCommunicationChannel"
    description:  "Update the marketingCommunicationChannel"
    operationId: "update"
    parameters:
      - name: "divisionRequestVO"
        in: "body" 
        description: "Request Body that contains data required for updating division." 
        required: true
        schema:
         $ref: "#/definitions/MarketingCommunicationChannelRequestVO"    
    responses:
      200:
       description: "Successfully updated."
       schema:
         $ref: "#/definitions/MarketingCommunicationChannelResponseVO"
      400:
       description: "Bad Request"
      401:
       description: "Request does not have sufficient credentials."
      403:
       description: "Request is not authorized."
      405:
       description: "Method not allowed"
      500:
       description: "Internal error"       
  
 /marketingCommunicationChannels/{id}:
  delete:
    tags:
    - "marketingCommunicationChannels"
    summary: "Deletes the marketingCommunicationChannel identified by given ID."
    description:  "Deletes the marketingCommunicationChannel identified by given ID"
    operationId: "delete"
    parameters:
      - name: "id"
        in: "path"
        description: "Id of the marketingCommunicationChannel"
        required: true
        type: "string"
    responses:
      200:
       description: "Successfully deleted."
       schema:
         $ref: "#/definitions/GenericMessage"
      400:
       description: "Bad request"
      401:
       description: "Request does not have sufficient credentials."
      403:
       description: "Request is not authorized."
      404:
       description: "Invalid id, record not found."
      500:
       description: "Internal error"    
definitions:
 MarketingCommunicationChannelResponseVO:
   type: object
   properties:
     data:
       $ref: "#/definitions/MarketingCommunicationChannelVO"
     errors:
       type: array
       items:
         $ref: "#/definitions/MessageDescription"
 
 MarketingCommunicationChannelVO:
  type: object
  properties: 
    id:
     type: string
     description: "ID of MarketingCommunicationChannel"
    name:
     type: string
     description: "Name of the MarketingCommunicationChannel"
     minLength: 1
#     pattern: '[a-zA-Z\s]+'
  required:
     - name
 MarketingCommunicationChannelCollection: 
  description: "Collection of MarketingCommunicationChannels."
  type: array
  items: 
     $ref: "#/definitions/MarketingCommunicationChannelVO"
 MarketingCommunicationChannelRequestVO:
  type: object
  properties:
    data:
      description: "Request data containing MarketingCommunicationChannel details to be created"
      $ref: "#/definitions/MarketingCommunicationChannelVO"

 GenericMessage:
  type: object
  properties:
    success:
      type: string
    errors:
      type: array
      items: 
        $ref: "#/definitions/MessageDescription"
  
 MessageDescription:
  type: object
  properties:
    message: 
      type: string
      description: "error message"
 