# LICENSE START
# 
# MIT License
# 
# Copyright (c) 2019 Daimler TSS GmbH
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# 
# LICENSE END 
#
 
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : visualization.yaml
#  **
#  ** Module     : core
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  boonbaluri
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
  

swagger: "2.0"
info:
 version: "1.0.0"
 title: "core visualization Service"
host: "localhost:7171"
basePath: "/api/1.0"
consumes:
 - "application/json"
produces:
 - "application/json"
tags:
 - name: "visualizations"
   description: "This service is used to maintain visualizations used in solutions."

schemes:
- "https"

paths:

# path to create a new visualization and fetch all valid visualizations or by intent
#
#  supprorted http methods GET, POST and DELETE 
#
# path example ../visualizations

 /visualizations:
  post:
   tags:
    - "visualizations"
   summary: "Adds a new visualization."
   description: "Adds a new non existing visualization which is used in providing solution."
   operationId: "create"
   parameters:
    - name: "VisualizationRequestVO" 
      in: "body" 
      description: "Request Body that contains data required for creating a new visualization" 
      required: true
      schema:
       $ref: "#/definitions/VisualizationRequestVO"
   responses:
    201: 
     description: "Returns message of success or failure "
     schema:
       $ref: "#/definitions/VisualizationVO"
    400:
     description: "Bad Request"
     schema:
       $ref: "#/definitions/GenericMessage"
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Method not allowed"
    500:
     description: "Internal error"
     
  get:
   tags:
    - "visualizations"
   summary: "Get all available visualizations."
   description:  "Get all visualizations. This endpoints will be used to Get all valid available visualizations maintenance records."
   operationId: "getAll"
   responses:
    201:
     description: "Returns message of success or failure"
     schema:
       $ref: "#/definitions/VisualizationCollection"
    204:
      description: "Fetch complete, no content found."
    400:
     description: "Bad request."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Method not allowed"
    500:
     description: "Internal error"

# path to delete existing visualizations
#
#  supported http methods DELETE
#
# path examples----
#   DELETE    .../visualizations/xxx

 /visualizations/{id}:
  delete:
    tags:
    - "visualizations"
    summary: "Deletes the visualization identified by given ID."
    description:  "Deletes the visualization identified by given ID"
    operationId: "delete"
    parameters:
      - name: "id"
        in: "path"
        description: "Id of the visualization"
        required: true
        type: "string"
    responses:
      200:
       description: "Successfully deleted."
       schema:
         $ref: "#/definitions/GenericMessage"
      400:
       description: "Bad request"
      401:
       description: "Request does not have sufficient credentials."
      403:
       description: "Request is not authorized."
      404:
       description: "Invalid id, record not found."
      500:
       description: "Internal error"
     
definitions:
 VisualizationVO:
  type: object
  properties: 
    id:
     type: string
     description: "ID of Visualization"
    name:
     type: string
     description: "Name of the Visualization"
     minLength: 1
#     pattern: '[a-zA-Z\s]+'
  required:
     - name
 VisualizationCollection: 
  description: "Collection of Visualizations."
  type: array
  items: 
     $ref: "#/definitions/VisualizationVO"
 VisualizationRequestVO:
  type: object
  properties:
    data:
      description: "Request data containing Visualization details to be created"
      $ref: "#/definitions/VisualizationVO"
 BindingResult:
  type: object

 GenericMessage:
  type: object
  properties:
    success:
      type: string
    errors:
      type: array
      items: 
        $ref: "#/definitions/MessageDescription"
  
 MessageDescription:
  type: object
  properties:
    message: 
      type: string
      description: "error message"