{
 "title": "I³ PostgreSQL",
 "description": "Dashboard for PostgreSQL Statistics.",
 "tags": [
  "i3",
  "i3-postgresql"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(pg_up, kubernetes_namespace)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(pg_up{kubernetes_namespace=\"$namespace\"}, cluster_name)"
   },
   {
    "name": "role",
    "label": "Role",
    "query": "label_values(pg_up{kubernetes_namespace=\"$namespace\"}, role)"
   },
   {
    "name": "statefulset_name",
    "label": "Statefulset",
    "query": "label_values(kube_statefulset_metadata_generation{namespace=\"$namespace\"}, statefulset)"
   },
   {
    "name": "db",
    "label": "Database",
    "query": "label_values(pg_stat_database_tup_fetched{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",datname!~\"template.*\"},datname)"
   }
  ]
 },
 "panels": [
  { "title": "I³ PostgreSQL overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "singlestat",
   "description": "CPU usage of namespace (per second average rate over the last 5 minutes)",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod_name=~\"$statefulset_name.*\",container_name!=\"\"}[5m]))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "description": "Memory usage of namespace",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",pod_name=~\"$statefulset_name.*\",container_name!=\"\"})"
    }
   ]
  },
  {
   "title": "Network",
   "type": "singlestat",
   "description": "Network rate of namespace (per second average rate over the last 5 minutes)",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\",pod_name=~\"$statefulset_name.*\"}[5m])) + sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\",pod_name=~\"$statefulset_name.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Desired Replicas",
   "type": "singlestat",
   "description": "Number of desired replica pods in namespace",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_statefulset_replicas{statefulset=\"$statefulset_name\",namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Available Replicas",
   "type": "singlestat",
   "description": "Number of available replica pods in namespace",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_ready{statefulset=\"$statefulset_name\",namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Observed Generation",
   "type": "singlestat",
   "description": "k8s generation counter - observed generation number\n\nExplanation:\nSome kubernetes objects (mainly those that affect underlying pods) have a generation field that increments as the spec changes. \n\nThe generation field is used internally at kubernetes so that it knows when some action is required at that object.",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kube_statefulset_status_observed_generation{statefulset=\"$statefulset_name\",namespace=\"$namespace\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Metadata Generation",
   "type": "singlestat",
   "description": "k8s generation counter - metadata generation number\n\nExplanation:\nSome kubernetes objects (mainly those that affect underlying pods) have a generation field that increments as the spec changes. \n\nThe generation field is used internally at kubernetes so that it knows when some action is required at that object.",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kube_statefulset_metadata_generation{statefulset=\"$statefulset_name\",namespace=\"$namespace\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Replica History Status",
   "type": "graph",
   "description": "History view of replica status in namespace",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "min(kube_statefulset_status_replicas{statefulset=\"$statefulset_name\",namespace=\"$namespace\"}) without (instance, pod)",
     "legendFormat": "Available"
    },
    {
     "expr": "max(kube_statefulset_replicas{statefulset=\"$statefulset_name\",namespace=\"$namespace\"}) without (instance, pod)",
     "legendFormat": "Desired"
    }
   ]
  },
  {
   "title": "PostgreSQL Pods in Role",
   "type": "graph",
   "description": "Role of PostgreSQL pods in namespace",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pg_up{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"master\"})",
     "legendFormat": "master"
    },
    {
     "expr": "sum(pg_up{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"replica\"})",
     "legendFormat": "replica"
    },
    {
     "expr": "sum(pg_up{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role!=\"replica\",role!=\"master\"})",
     "legendFormat": "unknown"
    }
   ]
  },
  {
   "title": "Database role",
   "type": "stat",
   "description": "Database role",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg_is_in_recovery_database_role{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Uptime per database pod",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "\rsum by (kubernetes_pod_name) ( pg_postmaster_start_time_seconds{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\"} )\r",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Current Replication lag",
   "type": "stat",
   "description": "If replayed LSN on replica is equal to current LSN on master, there is no replication lag and then this value shows always 0. Otherwise this value displays the elapsed time since last transaction replayed during streaming replication recovery. If recovery is still in progress this will increase monotonically.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "\rsum by (kubernetes_pod_name) ( pg_replication_lag{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\", role=\"replica\"} )",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Replication lag",
   "type": "graph",
   "description": "If replayed LSN on replica is equal to current LSN on master, there is no replication lag and then this value shows always 0. Otherwise this graph gives a historical view for elapsed time since last transaction replayed during streaming replication recovery. If recovery is still in progress this will increase monotonically.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "\rsum by (kubernetes_pod_name)  (pg_replication_lag{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\", role=\"replica\"})",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Settings (master)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Version",
   "type": "singlestat",
   "description": "Shows the PostgreSQL server version as an integer (e.g. 110005 means postgres version  11.5)",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_server_version_num{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"master\"}",
     "legendFormat": "{{short_version}}"
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "singlestat",
   "description": "Current configuration of the postgreSQL  max_connections setting.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 30 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "pg_settings_max_connections{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"master\"}"
    }
   ]
  },
  {
   "title": "Shared Buffers",
   "type": "singlestat",
   "description": "Current configuration of the postgreSQL shared_buffers setting",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 30 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_shared_buffers_bytes{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"master\"}"
    }
   ]
  },
  {
   "title": "Effective Cache",
   "type": "singlestat",
   "description": "Current configuration of the postgreSQL effective_cache_size setting",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 30 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_effective_cache_size_bytes{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"master\"}"
    }
   ]
  },
  {
   "title": "Work Mem",
   "type": "singlestat",
   "description": "Current configuration of the postgreSQL work_mem setting",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 30 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_work_mem_bytes{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"master\"}"
    }
   ]
  },
  {
   "title": "Max Parallel Workers",
   "type": "singlestat",
   "description": "Current configuration of the postgreSQL max_parallel_workers setting",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_max_parallel_workers{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"master\"}"
    }
   ]
  },
  {
   "title": "Maintenance Work Mem",
   "type": "singlestat",
   "description": "Current configuration of the postgreSQL maintenance_work_mem setting",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 30 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_maintenance_work_mem_bytes{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"master\"}"
    }
   ]
  },
  {
   "title": "Wal Buffer Size",
   "type": "singlestat",
   "description": "Current configuration of the postgreSQL wal_buffers setting",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 30 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_wal_buffers_bytes{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"master\"}"
    }
   ]
  },
  { "title": "Memory / CPU overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Memory Usage  vs Limits for PostgreSQL Pod(s)",
   "type": "graph",
   "description": "Current memory usage, including all memory regardless of when it was accessed.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (i3labelpodname) (label_replace(container_memory_usage_bytes{namespace=\"$namespace\",pod_name=~\"$statefulset_name.*\"}, \"i3labelpodname\", \"$1\", \"pod_name\", \"(.*)\")+ on (i3labelpodname) group_left(role) 0 * label_replace(sum by (kubernetes_pod_name) (pg_stat_activity_count{kubernetes_namespace=\"$namespace\",role=\"$role\",cluster_name=\"$cluster\",kubernetes_pod_name=~\"$statefulset_name.*\"} >0), \"i3labelpodname\", \"$1\", \"kubernetes_pod_name\", \"(.*)\"))",
     "legendFormat": "{{i3labelpodname}}"
    },
    {
     "expr": "kube_pod_container_resource_requests{resource=\"memory\",unit=\"byte\",namespace=~\"$namespace\",pod=~\"$statefulset_name.*\"}",
     "legendFormat": "Limit for {{pod }} "
    }
   ]
  },
  {
   "title": "CPU Usage for Containers in PostgreSQL Pod(s)",
   "type": "graph",
   "description": "The total amount of \"user\" and \"system\" time (per-second average rate over the last 5 minutes)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (i3labelpodname) (label_replace(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container_name!=\"POD\",image!~\".*docker.io_postgres_exporter.*\"}[5m]), \"i3labelpodname\", \"$1\", \"pod_name\", \"(.*)\")+ on (i3labelpodname) group_left(role) 0 * label_replace(sum by (kubernetes_pod_name) (pg_stat_activity_count{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\"} >0), \"i3labelpodname\", \"$1\", \"kubernetes_pod_name\", \"(.*)\"))",
     "legendFormat": "{{i3labelpodname}}"
    },
    {
     "expr": "quantile(0.5,kube_pod_container_resource_limits{resource=\"cpu\",unit=\"core\",namespace=\"$namespace\",pod=~\"$statefulset_name.*\"}) by (container, pod)",
     "legendFormat": "Limit for {{pod }} "
    }
   ]
  },
  {
   "title": "PostgreSQL Pods Bytes Read per second",
   "type": "graph",
   "description": "PostgreSQL Pods Bytes Read per second (per-second average rate over the last 5 minutes)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{pod_namespace=\"$namespace\",pod_name=~\"$statefulset_name.*\"}[5m])) by (pod_name)",
     "legendFormat": "{{pod_name}}-reads"
    }
   ]
  },
  {
   "title": "PostgreSQL Pods Bytes Written per second",
   "type": "graph",
   "description": "PostgreSQL Pods Bytes Written per second (per-second average rate over the last 5 minutes)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{pod_namespace=\"$namespace\",pod_name=~\"$statefulset_name.*\"}[5m])) by (pod_name)",
     "legendFormat": "{{pod_name}}-writes"
    }
   ]
  },
  {
   "title": "PostgreSQL PVC capacity",
   "type": "stat",
   "description": "PostgreSQL PVC capacity",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (pvc_name)(dhc-gp3_volume_size{pvc_namespace=\"$namespace\",status=\"in-use\"})",
     "legendFormat": "{{pvc_name}}"
    }
   ]
  },
  {
   "title": "PostgreSQL Pod Disk usage",
   "type": "graph",
   "description": "PostgreSQL Pod Disk usage",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - node_filesystem_free_bytes{pv_name!=\"\"} / node_filesystem_size_bytes + on(pv_name) group_left(pvc_name) 0 * min by(pv_name, pvc_name) (kube_persistentvolumeclaim_info{namespace=\"$namespace\"})",
     "legendFormat": "{{pvc_name}}"
    }
   ]
  },
  {
   "title": "Connection / Transaction Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 }
  },
  {
   "title": "Number of Connections",
   "type": "graph",
   "description": "Number of connections (backends) currently on this database. ",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_numbackends{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\", datname=~\"$db\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{datname}}"
    }
   ]
  },
  {
   "title": "Connection Status",
   "type": "graph",
   "description": "Connections by status",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_count{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\", datname=~\"$db\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{datname}}-{{state}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "description": "Number of transactions in this database that have been committed/rolled back (per-second rate, looking up to 5 minutes back for the two most recent data points)",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_commit{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\", datname=~\"$db\"}[5m])",
     "legendFormat": "{{kubernetes_pod_name}}-{{datname}}-commits"
    },
    {
     "expr": "irate(pg_stat_database_xact_rollback{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\", datname=~\"$db\"}[5m])",
     "legendFormat": "{{kubernetes_pod_name}}-{{datname}}-rollbacks"
    }
   ]
  },
  {
   "title": "Longest Transaction",
   "type": "graph",
   "description": "Max duration in seconds any active transaction has been running on this database.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_max_tx_duration{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\", datname=~\"$db\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{datname}}-max_tx_duration [{{state}}]"
    }
   ]
  },
  {
   "title": "Rows",
   "type": "graph",
   "description": "Number of rows fetched/inserted/updated/deleted by queries in this database (per-second reate, looking up to 5 minutes back for the two most recent data points)",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "fetched",
     "expr": "irate(pg_stat_database_tup_fetched{datname=~\"$db\",kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\"}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{kubernetes_pod_name}}-{{datname}}-fetched",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "fetched",
     "expr": "irate(pg_stat_database_tup_returned{datname=~\"$db\",kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\"}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{kubernetes_pod_name}}-{{datname}}-returned",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "fetched",
     "expr": "irate(pg_stat_database_tup_inserted{datname=~\"$db\",kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\"}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{kubernetes_pod_name}}-{{datname}}-inserted",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "fetched",
     "expr": "irate(pg_stat_database_tup_updated{datname=~\"$db\",kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\"}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{kubernetes_pod_name}}-{{datname}}-updated",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "fetched",
     "expr": "irate(pg_stat_database_tup_deleted{datname=~\"$db\",kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\"}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{kubernetes_pod_name}}-{{datname}}-deleted",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Locktimeouts/Deadlocks",
   "type": "graph",
   "description": "Number of queries that have been canceled due to lock timeouts and number of deadlocks detected in this database (per-second reate, looking up to 5 minutes back for the two most recent data points)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_conflicts_confl_lock{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\", datname=~\"$db\"}[5m])",
     "legendFormat": "{{kubernetes_pod_name}}-{{datname}}-locktimeouts"
    },
    {
     "expr": "irate(pg_stat_database_deadlocks{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\", datname=~\"$db\"}[5m])",
     "legendFormat": "{{kubernetes_pod_name}}-{{datname}}-deadlocks"
    }
   ]
  },
  {
   "title": "Lock Modes",
   "type": "graph",
   "description": "Number of locks by type on this database. ",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_locks_count{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\", datname=~\"$db\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{datname}}-{{mode}}"
    }
   ]
  },
  { "title": "PostgreSQL Internal Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 } },
  {
   "title": "Current DB size",
   "type": "stat",
   "description": "Current database size",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\", datname=~\"$db\"}",
     "legendFormat": "{{kubernetes_pod_name}}: {{datname}}"
    }
   ]
  },
  {
   "title": "DB size",
   "type": "graph",
   "description": "Database size history",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 103 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_database_size_bytes{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\", datname=~\"$db\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{datname}}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "graph",
   "description": "Calculated Cache Hit Ratio for this database.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_blks_hit{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\", datname=~\"$db\"} / (pg_stat_database_blks_read{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\", datname=~\"$db\"} + pg_stat_database_blks_hit{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\", datname=~\"$db\"})",
     "legendFormat": "{{kubernetes_pod_name}}-{{datname}}"
    }
   ]
  },
  {
   "title": "Temp File",
   "type": "graph",
   "description": "Total amount of data written to temporary files by queries in this database. All temporary files are counted, regardless of why the temporary file was created, and regardless of the log_temp_files setting.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_temp_bytes{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\", datname=~\"$db\"}[5m])",
     "legendFormat": "{{kubernetes_pod_name}}-{{datname}}"
    }
   ]
  }
 ]
}