{
 "title": "I³ PostgreSQL Query Monitoring",
 "description": "Dashboard for PostgreSQL Query Statistics.",
 "tags": [
  "i3",
  "i3-postgresql"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(pg_up, kubernetes_namespace)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(pg_up{kubernetes_namespace=\"$namespace\"}, cluster_name)"
   },
   {
    "name": "role",
    "label": "Role",
    "query": "label_values(pg_up{kubernetes_namespace=\"$namespace\"}, role)"
   },
   {
    "name": "statefulset_name",
    "label": "Statefulset",
    "query": "label_values(kube_statefulset_metadata_generation{namespace=\"$namespace\"}, statefulset)"
   },
   {
    "name": "db",
    "label": "Database",
    "query": "label_values(pg_stat_database_tup_fetched{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",datname!~\"template.*\"},datname)"
   },
   {
    "name": "rolname",
    "label": "Rolname",
    "query": "label_values(pg_stat_statements_calls{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",datname!~\"template.*\"},rolname)"
   }
  ]
 },
 "panels": [
  { "title": "Statements Calls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Statements Calls",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) ((rate(pg_stat_statements_calls{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\", datname=~\"$db\", rolname=~\"$rolname\"}[5m]) or \nirate(pg_stat_statements_calls{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\", datname=~\"$db\", rolname=~\"$rolname\"}[5m])))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Most Called Queries",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sort_desc(topk(10,rate(pg_stat_statements_calls{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\", datname=~\"$db\", rolname=~\"$rolname\"}[5m]) or \nirate(pg_stat_statements_calls{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\", datname=~\"$db\", rolname=~\"$rolname\"}[5m])))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Slowest Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Total Duration of Queries",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) ((rate(pg_stat_statements_total_time_seconds{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\", datname=~\"$db\", rolname=~\"$rolname\"}[5m]) or \nirate(pg_stat_statements_total_time_seconds{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\", datname=~\"$db\", rolname=~\"$rolname\"}[5m])))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Top Query Runtime Total",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sort_desc(topk(10,rate(pg_stat_statements_total_time_seconds{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\", datname=~\"$db\", rolname=~\"$rolname\"}[5m])))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top Query Runtime Average",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "topk(10, rate(pg_stat_statements_mean_time_seconds{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\", datname=~\"$db\", rolname=~\"$rolname\"}[5m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Shared Blocks I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Total Shared Blocks Dirtied",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_stat_statements_shared_blks_dirtied{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\", datname=~\"$db\", rolname=~\"$rolname\"}[5m]))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Total Shared Blocks Cache Hits",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_stat_statements_shared_blks_hit{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\", datname=~\"$db\", rolname=~\"$rolname\"}[5m]))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Top Shared Blocks  Dirtied",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sort_desc(topk(10,rate(pg_stat_statements_shared_blks_dirtied{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\", datname=~\"$db\", rolname=~\"$rolname\"}[5m])))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top Shared Block Cache Hits",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "sort_desc(topk(10,rate(pg_stat_statements_shared_blks_hit{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\", datname=~\"$db\", rolname=~\"$rolname\"}[5m])))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Shared Blocks Read",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_stat_statements_shared_blks_read{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\",datname=~\"$db\", rolname=~\"$rolname\"}[5m]))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Total Shared Blocks Written",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_stat_statements_shared_blks_written{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\",datname=~\"$db\", rolname=~\"$rolname\"}[5m]))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Top Shared Blocks Read",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "sort_desc(topk(10,rate(pg_stat_statements_shared_blks_read{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\", datname=~\"$db\", rolname=~\"$rolname\"}[5m])))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top Shared Blocks Written",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "sort_desc(topk(10,rate(pg_stat_statements_shared_blks_written{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\",datname=~\"$db\", rolname=~\"$rolname\"}[5m])))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Local Blocks I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Total Local Blocks Dirtied",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_stat_statements_local_blks_dirtied{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\", datname=~\"$db\", rolname=~\"$rolname\"}[5m]) * 8)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Total Local Blocks Cache Hits",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_stat_statements_local_blks_hit{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\", datname=~\"$db\", rolname=~\"$rolname\"}[5m]))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Top Local Blocks Dirtied",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "sort_desc(topk(10,rate(pg_stat_statements_local_blks_dirtied{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\", datname=~\"$db\", rolname=~\"$rolname\"}[5m])))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top Local Blocks Cache Hits",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 77 },
   "targets": [
    {
     "expr": "sort_desc(topk(10,rate(pg_stat_statements_local_blks_hit{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\", datname=~\"$db\", rolname=~\"$rolname\"}[5m])))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Local Blocks Read",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_stat_statements_local_blks_read{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\", datname=~\"$db\", rolname=~\"$rolname\"}[5m]))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Total Local Blocks Written",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_stat_statements_local_blks_written{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\", datname=~\"$db\", rolname=~\"$rolname\"}[5m]))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Top Local Blocks Read",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 95 },
   "targets": [
    {
     "expr": "sort_desc(topk(10,rate(pg_stat_statements_local_blks_read{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\", datname=~\"$db\", rolname=~\"$rolname\"}[5m])))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top Local Blocks Written",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 95 },
   "targets": [
    {
     "expr": "sort_desc(topk(10,rate(pg_stat_statements_local_blks_written{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\", datname=~\"$db\", rolname=~\"$rolname\"}[5m])))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Temp Data Read", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 } },
  {
   "title": "Total Temp Blocks Read",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_stat_statements_temp_blks_read{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\", datname=~\"$db\", rolname=~\"$rolname\"}[5m]) or \nirate(pg_stat_statements_temp_blks_read{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\", datname=~\"$db\", rolname=~\"$rolname\"}[5m]))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Top Temp Blocks Read",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 110 },
   "targets": [
    {
     "expr": "sort_desc(topk(10,rate(pg_stat_statements_temp_blks_read{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\", datname=~\"$db\", rolname=~\"$rolname\"}[5m])))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "test1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top Temp Blocks Read per Call",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 110 },
   "targets": [
    {
     "expr": "topk(10, rate(pg_stat_statements_temp_blks_read{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\", datname=~\"$db\", rolname=~\"$rolname\"}[5m]) / \n(rate(pg_stat_statements_calls{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\", datname=~\"$db\", rolname=~\"$rolname\"}[5m])))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Temp Data Written", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 } },
  {
   "title": "Temp Blocks Written",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 121 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_stat_statements_temp_blks_written{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\", datname=~\"$db\", rolname=~\"$rolname\"}[5m]))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Temp Blocks Written",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 125 },
   "targets": [
    {
     "expr": "sort_desc(topk(10,rate(pg_stat_statements_temp_blks_written{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\", datname=~\"$db\", rolname=~\"$rolname\"}[5m])))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temp Blocks Written per Call",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 125 },
   "targets": [
    {
     "expr": "topk(10, rate(pg_stat_statements_temp_blks_written{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\", datname=~\"$db\", rolname=~\"$rolname\"}[5m]) / \n(rate(pg_stat_statements_calls{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster\",role=\"$role\", datname=~\"$db\", rolname=~\"$rolname\"}[5m])))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}