replicaCount: 1
envs: []
secret: []
image:
  repository: registry-emea.app.corpintra.net/dnaplatform/matomo-backend
  pullPolicy: IfNotPresent
  tag: '198'
imagePullSecrets: []
nameOverride: ''
fullnameOverride: matomo-be
namespace: dev-dna-matomo
serviceAccount:
  create: false
  annotations: {}
  name: ''
podAnnotations: {}
podSecurityContext:
  runAsUser: 1000
containerPort: 8989
securityContext: {}
service:
  type: ClusterIP
  port: 8989
ingress:
  enabled: false
  host: api.matomo.dna-aws.app.corpintra.net
  annotations:
    traefik.frontend.rule.type: PathPrefix
    kubernetes.io/ingress.class: test-ingress-intranet
    traefik.ingress.kubernetes.io/router.tls: 'true'
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: mercedes-benz-acme
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect@kubernetescrd
  hosts:
    - host: api.matomo.dna-aws.app.corpintra.net
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - api.matomo.dna-aws.app.corpintra.net
      secretName: api-matomo-tls-secret
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
vaultInjector:
  enable: true
  annotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/role: dna_aws_dev_k8_role
    vault.hashicorp.com/tls-skip-verify: 'true'
    vault.hashicorp.com/agent-image: registry-emea.app.corpintra.net/dnaplatform/vault-secret-auto-update:v1
    vault.hashicorp.com/agent-inject-command-envvar: sh /opt/restart_deployment.sh
    vault.hashicorp.com/template-static-secret-render-interval: 10s
    vault.hashicorp.com/agent-pre-populate-only: 'false'
    vault.hashicorp.com/agent-inject-secret-envvar: dna_aws_kv/dev/kubernetesSecret/matomoService
    vault.hashicorp.com/agent-inject-template-envvar: |
      {{- with secret "dna_aws_kv/dev/kubernetesSecret/matomoService" -}}
        {{- range $k, $v := .Data.data }}
            export {{ $k }}="{{ $v }}"
        {{- end }}
      {{- end }}        
  saName: default
  jarName: matomo-lib-1.0.0.jar
