{{- if .Values.server.horizontalAutoscaler.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "prometheus.server.fullname" . }}-hpa
  namespace: {{ include "prometheus.namespace" . }}
  labels:
    {{- include "prometheus.server.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
{{- if .Values.server.statefulSet.enabled }}
    kind: StatefulSet
{{- else }}
    kind: Deployment
{{- end }}
    name: {{ template "prometheus.server.fullname" . }}
  minReplicas: {{ .Values.server.horizontalAutoscaler.minReplicas | default 3 }}
  maxReplicas: {{ .Values.server.horizontalAutoscaler.maxReplicas | default 10 }}
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.server.horizontalAutoscaler.targetMemoryUtilizationPercentage }}
{{- end }}
