kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: dev-bat-argocd-root-app
  namespace: argocd
spec:
  project: 'bat-development'
  source:
    repoURL: 'https://git.i.mercedes-benz.com/BAT/bat-infra.git'
    targetRevision: 'aws/migration'
    path: c52p219-dev/apps
    plugin:
      name: argocd-vault-plugin-helm
  destination:
    name: 'in-cluster'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
