apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-apps-test
  namespace: argocd
  labels:
    name: argocd-apps-test
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: deployment/kubernetes/DyP/argocd/apps
    repoURL: https://git.i.mercedes-benz.com/DNA/NeuDnAPlatform.git
    targetRevision: staging
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_ARGS
          value: -f values-test.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
