server: "https://kubernetes.default.svc"
# Environment to deploy it  (dev|test|prod)
env: dev
branch: dev
namespace: argocd
repoURL: "https://git.i.mercedes-benz.com/DNA/NeuDnAPlatform.git"
enableSync: true
gitRepo:
  username: <path:kv/data/dna/kubernetesSecret/argocd#username | base64encode>
  password: <path:kv/data/dna/kubernetesSecret/argocd#password | base64encode>

annotations: 
  notifications.argoproj.io/subscribe.on-created.teams: channelName
  notifications.argoproj.io/subscribe.on-deleted.teams: channelName
  notifications.argoproj.io/subscribe.on-deployed.teams: channelName
  notifications.argoproj.io/subscribe.on-health-degraded.teams: channelName
  notifications.argoproj.io/subscribe.on-sync-failed.teams: channelName
  notifications.argoproj.io/subscribe.on-sync-running.teams: channelName
  notifications.argoproj.io/subscribe.on-sync-status-unknown.teams: channelName
  notifications.argoproj.io/subscribe.on-sync-succeeded.teams: channelName
  
repositories:
  # - name: chronos-frontend
  #   url: https://git.i.mercedes-benz.com/DNA/dna-chronos-frontend.git  
  # - name: dna-dataproduct-frontend
  #   url: https://git.i.mercedes-benz.com/DNA/dna-dataproduct-frontend.git  
  # - name: dna-frontend
  #   url: https://git.i.mercedes-benz.com/DNA/dna-frontend.git
  # - name: dna-trino
  #   url: https://git.i.mercedes-benz.com/DNA/dna-trino.git  
  - name: dna-model-registry
    url: https://git.i.mercedes-benz.com/DNA/dna-model-registry.git        
  # - name: dss-be
  #   url: https://git.i.mercedes-benz.com/DNA/dna-dss-backend.git
  # - name: dna-codeserver-backend
  #   url: https://git.i.mercedes-benz.com/DNA/dna-codeserver-backend.git  
  - name: dna-kong
    url: https://git.i.mercedes-benz.com/DNA/dna-kong.git  
  # - name: matomo-mfe
  #   url: https://git.i.mercedes-benz.com/DNA/dna-matomo-frontend.git
  - name: dataentry-backend
    url: https://git.i.mercedes-benz.com/DNA/dna-dataentry-backend.git 
  # - name: dna-notification
  #   url: https://git.i.mercedes-benz.com/DNA/dna-notification.git       
