fullnameOverride: tempo
global:
  image:
    registry: registry-emea.app.corpintra.net/dockerhub  
storage:
  trace:
    backend: s3
    s3:
      access_key: 'root-user'
      secret_key: 'supersecret'
      bucket: 'tempo-traces'
      endpoint: 'loki-minio:9000'
      insecure: true
ingester:
  persistence:
    enabled: true
    claims:
      - name: data
        size: 50Gi  
        storageClass: dhc-gp3
  config:
    trace_idle_period: 10s  
    max_block_bytes: 1_000_000  
    max_block_duration: 1m 
compactor:
  config:
    compaction:
      compaction_window: 720h # 30days
      max_compaction_objects: 1000000
      block_retention: 720h
      compacted_block_retention: 10m
traces:
  otlp:
    grpc:
      enabled: true
    http:
      enabled: true        
  zipkin:
    enabled: true      
overrides:
  defaults:
    metrics_generator:
      processors: ['service-graphs', 'span-metrics', 'local-blocks']
      generate_native_histograms: both