apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}
  ingress:
    - ports:
        - port: 7171
          protocol: TCP
  policyTypes:
  - Ingress