

spring:
    cloud:
        vault:
            authentication: ${VAULT_AUTHENTICATION:XXXX}
            host: ${VAULT_HOST:XXXX}
            kv:
                enabled: 'XXXX'
            mountpath: ${VAULT_MOUNTPATH:XXXX}
            port: ${VAULT_PORT:XXXX}
            scheme: ${VAULT_SCHEME:XXXX}
            token: ${VAULT_TOKEN:s.XXXX}
            vaultpath: ${VAULT_PATH:XXXX}
            namespace: ${VAULT_NAMESPACE:XXXX}
            uri: ${VAULT_URI:XXXX}
            kubernetes:
                kubernetes-path: ${KUBERNETES_PATH:XXXX}
                role: ${KUBERNETES_ROLE:XXXX}
                service-account-token-file: ${KUBERNETES_SATOKENPATH:XXXX}            
            ssl:
                enabled: XXXX
                trust:
                    store:
                        path: ${CA_TRUSTSTORE_PATH:XXXX}
                        password: ${CA_TRUSTSTORE_PASSWORD:XXXX}    

    datasource:
        driver-class-name: org.postgresql.Driver
        hikari:
            connection-timeout: 4000
            data-source-properties: stringtype=unspecified
        password: ${API_DB_PASS:XXXX}
        tomcat:
            connection-properties: stringtype=unspecified
        url: ${API_DB_URL:XXXX}
        username: ${API_DB_USER:XXXX}
    flyway:
        baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE:XXXX}
        baseline-version: ${FLYWAY_BASELINEVERSION:XXXX}
        enabled: ${FLYWAY_ENABLED:XXXX}
        locations: classpath:XXXX
        schemas: ${FLYWAY_SCHEMA:XXXX}

    http:
        multipart:
            enabled: XXXX        

    servlet:
        multipart:
            max-file-size: ${MAX_FILE_SIZE:XXXX}
            max-request-size: ${MAX_REQUEST_SIZE:XXXX}      
    graphql:
        path: /api/minified
    jpa:
        database: POSTGRESQL
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                temp:
                    use_jdbc_metadata_defaults: false

    
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher

server:
    forward-headers-strategy: framework
    port: 8081


management:
    endpoint:
        health:
            probes:
                enabled: true
            show-details: always
        loggers:
            enabled: true
    endpoints:
        web:
            exposure:
                include: loggers,health
 

springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        enabled: true

swagger:
    headers:
        authorization:
            apiKey: ${SWAGGER_HEADER_AUTH_APPKEY:XXXXXX}
            appId: ${SWAGGER_HEADER_AUTH_APPID:XXXXXX}
            token: ${SWAGGER_HEADER_AUTH:XXXXXX}

technical:
    user:
        password: ${TECHNICAL_USER_PASSWORD:XXXXXX}
        username: ${TECHNICAL_USER_USERNAME:XXXXXX}

allowedCorsOriginPatternUrl: http://*

proxy:
    port: ${CUSTOMPROXY_PORT:3128}
    host: ${CUSTOMPROXY_HOST:xxxx}

dna:
  uri: ${DNA_URI:XXXXXX}

argocd:
  argocdTokenUrl: ${ARGOCD_TOKEN_URI:XXXX}
  argocdCreateUrl: ${ARGOCD_CREATE_URI:XXXX}
  tokenUserName: ${TOKEN_USER_NAME:XXXX}
  tokenPassword: ${TOKEN_PASSWORD:XXXX}
  createTargetRevision: ${ARGOCD_CREATE_TARGETREVISION:xxxx}
  createMemoryRequest: ${ARGOCD_CREATE_MEMORYREQUEST:xxxx}
  createCpuRequest: ${ARGOCD_CREATE_CPUREQUES:xxxx}
  createMaxconnections: ${ARGOCD_CREATE_MAXCONNECTIONS:xxxx}
  createProjectName: ${ARGOCD_CREATE_PROJECTNAME:xxxx}
  createReplicaCount: ${ARGOCD_CREATE_REPLICACOUNT:xxxx}
  createNameSpace: ${ARGOCD_CREATE_NAMESPACE:xxxx}
  createPDBminAvailable: ${ARGOCD_CREATE_PDBMINAVAILABLE:0}
  createEnvironment: ${ARGOCD_CREATE_ENVIRONMENT:xxxx}
  createRepoUrl: ${ARGOCD_CREATE_REPOURL:xxxx}
  createSourcePath: ${ARGOCD_CREATE_SOURCEPATH:xxxx}

dbService:
    host:
        url: ${HOST_BASE_URL:.XXXX}
    accesskey: ${ACCESSKEY:XXXX}
    backupPassword: ${BACKUP_PASSWORD:XXXX}
    bucketName: ${BUCKET_NAME:XXXX}
    dataCatalogPassword: ${DATA_CATALOG_PASSWORD:XXXX}
    debeziumPassword: ${DEBEZIUM_PASSWORD:XXXX}
    patroniPassword: ${PATRONI_PASSWORD:XXXX}
    pgmonPassword: ${PGMON_PASSWORD:XXXX}
    retention: ${RETENTION:XXXX}
    s3Host: ${S3_HOST:XXXX}
    s3secretkey: ${S3_SECRET_KEY:XXXX}
    size: ${SIZE:XXXX}
    port: ${PORT:XXXX}
    initDbTemplatePath: ${INITDBTEMPLATEPATH:XXXX}    
