/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mb.dna.kube.client.main;

import java.util.Map;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import io.kubernetes.client.openapi.ApiClient;
import io.kubernetes.client.openapi.Configuration;
import io.kubernetes.client.openapi.apis.CoreV1Api;
import io.kubernetes.client.openapi.models.V1Container;
import io.kubernetes.client.openapi.models.V1Pod;
import io.kubernetes.client.openapi.models.V1PodList;
import io.kubernetes.client.openapi.models.V1PodSpec;
import io.kubernetes.client.openapi.models.V1Secret;
import io.kubernetes.client.util.Config;

@SpringBootApplication
public class Application {

  private static String KUBEFLOW_NAMESPACE = "kubeflow";
	
  public static void main(String[] args) {
    SpringApplication.run(Application.class, args);
    try {
		ApiClient client = Config.defaultClient();
		Configuration.setDefaultApiClient(client);
        CoreV1Api api = new CoreV1Api();
        V1PodList items = api.listNamespacedPod(KUBEFLOW_NAMESPACE,null, null, null, null, null, null, null, null, 10, false);
        V1Pod minioPod = items.getItems().stream().filter(pod -> pod.getMetadata().getName().contains("minio")).findFirst().get();
        V1PodSpec minioPodSpec = minioPod.getSpec();
        V1Container minioContainer = minioPodSpec.getContainers().stream().filter(container -> container.getName().contains("minio")).findFirst().get();
        minioContainer.getEnv().forEach(x -> System.out.println("Environment name: " + x.getName() + " , value: " + x.getValue()));
        V1Secret result = api.readNamespacedSecret("mlpipeline-minio-artifact", KUBEFLOW_NAMESPACE, null);
        System.out.println(result.getData().toString());
        Map<String, byte[]> secretsMap = result.getData();
        for (String key: secretsMap.keySet()) {
            System.out.println(key + ": " + secretsMap.get(key));
        }
	}catch(Exception e) {
		e.printStackTrace();
	}
  }


}
