# Default values for aws-data-migration-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

imagePullSecrets:

backupJob:
  enabled: true
  backupPvc:
    - pvcName: ws1887
      namespace: 'backup-ns-01'
      backupPath: '/home/backup-ns-01'
    - pvcName: ws1888
      namespace: 'backup-ns-02'
      backupPath: '/home/backup-ns-02'
    - pvcName: ws1889
      namespace: 'backup-ns-03'
      backupPath: '/home/backup-ns-03'

restoreJob:
  enabled: true
  namespace: restore-ns
  restorePath: '/home/coder'
# If the job is enabled, then mention the jobname below  
  restorePvcName:
    - ws1275
    - ws1639
    - ws1841

storageCredentials:
  accessKeyId: ""
  secretAccessKey: ""
  resticKey: ""
  bucketName: ""