apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ .Values.env }}-dna-officalairflow253
  namespace: {{ .Values.namespace }}
  labels:
    name: service
spec:
  destination:
    namespace: {{ .Values.env }}-dna-airflow
    server: {{ .Values.server | squote }}
  source:
    path: deployment/kubernetes/helm/charts/helm-offical-airflow253
    repoURL: {{ .Values.repoURL | squote }}
    targetRevision: migration/aws-airflow
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_ARGS         
          value: -f values-{{ .Values.env }}.yaml -n {{ .Values.env }}-dna-airflow      
  project: dev-dna
{{- if .Values.enableSync }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
{{- end }}
