apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ .Values.env }}-db-apisap
  namespace: {{ .Values.namespace }}
  labels:
    name: db
    env: {{ .Values.env }}
    project: {{ .Values.env }}-apisap
spec:
  destination:
    namespace: {{ .Values.env }}-apisap
    server: {{ .Values.server | squote }}
  source:
    path: deployment/kubernetes/DyP/i3/postgresql-helm
    repoURL: {{ .Values.repoURL | squote }}
    targetRevision: {{ .Values.branch }}
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_ARGS
          {{- if ne .Values.env "prod" }}          
          value: -f values-apisap-dev-db.yaml --set namespace={{ .Values.env }}-apisap
          {{ else }}
          value: -f values-apisap-{{ .Values.env }}-db.yaml --set namespace={{ .Values.env }}-apisap
          {{- end }}                    
  project: {{ .Values.env }}-apisap
{{- if .Values.enableSync }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
{{- end }}
