{{- if ne .Values.env "test" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: imagepullsecret-patcher
  namespace: {{ .Values.namespace }}
  labels:
    name: service 
    env: {{ .Values.env }}
    project: c-svc 
spec:
  destination:
    namespace: imagepullsecret-patcher
    server: {{ .Values.server | squote }}
  source:
    path: deployment/kubernetes/DyP/imagepullsecret-patcher
    repoURL: {{ .Values.repoURL | squote }}
    targetRevision: {{ .Values.branch }}
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_ARGS
          value: --namespace imagepullsecret-patcher -f values-{{ .Values.env }}.yaml                     
  project: c-svc
{{- if .Values.enableSync }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
{{- end }}
{{- end }}