apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: cert-manager
  namespace: {{ .Values.namespace }}
  labels:
    name: dhc
spec:
  destination:
    namespace: cert-manager
    server: {{ .Values.server | squote }}
  source:
    path: deployment/kubernetes/DyP/cert-manager
    repoURL: {{ .Values.repoURL | squote }}
    targetRevision: {{ .Values.branch }}
    helm:
      releaseName: cert-manager
      valueFiles:
        - values-dhc.yaml    
  project: dna
{{- if .Values.enableSync }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
{{- end }}