{{- if eq .Values.env "prod" }} 
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: generic-redis-int
  namespace: {{ .Values.namespace }}
  labels:
    name: service
    env: {{ .Values.env }}
    project: {{ .Values.env }}-dna
spec:
  destination:
    namespace: cs-apps-services
    server: {{ .Values.server | squote }}
  source:
    path: deployment/kubernetes/helm/charts/redis
    repoURL: {{ .Values.repoURL | squote }}
    targetRevision: {{ .Values.branch }}
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_ARGS
          value: -f values-cs-apps-generic-redis-int.yaml --set fullnameOverride=generic-redis-int
  project: {{ .Values.env }}-dna
{{- if .Values.enableSync }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
{{- end }}
{{- end }}