apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: dataentry-backend
  namespace: {{ .Values.namespace }}
  labels:
    name: backend  
spec:
  destination:
    namespace: dataentry
    server: {{ .Values.server | squote }}
  source:
    path: deployment/helm
    repoURL: https://git.i.mercedes-benz.com/DNA/dna-dataentry-backend.git
    targetRevision: {{ .Values.branch }}
    helm:
      releaseName: dataentry-backend
      valueFiles:
        - values-{{ .Values.env }}.yaml
  project: dna
{{- if .Values.enableSync }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
{{- end }}