apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: dataproduct-backend
  namespace: {{ .Values.namespace }}
  labels:
    name: backend  
spec:
  destination:
    namespace: data-product
    server: {{ .Values.server | squote }}
  source:
    path: deployment/kubernetes/helm/charts/data-product-be
    repoURL: {{ .Values.repoURL | squote }}
    targetRevision: {{ .Values.branch }}
    helm:
      releaseName: data-product-be
      valueFiles:
        - values-{{ .Values.env }}.yaml
  project: dna
{{- if .Values.enableSync }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
{{- end }}
