apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ .Values.env }}-dna-matomo
  namespace: {{ .Values.namespace }}
  labels:
    name: service
    env: {{ .Values.env }}
    project: {{ .Values.env }}-dna
spec:
  destination:
    namespace: {{ .Values.env }}-dna-matomo
    server: {{ .Values.server | squote }}
  source:
    path: deployment/kubernetes/helm/charts/matomo
    repoURL: {{ .Values.repoURL | squote }}
    targetRevision: infra/matomosync-fix
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_ARGS         
          value: -f values-{{ .Values.env }}.yaml -n matomo      
  project: {{ .Values.env }}-dna
{{- if .Values.enableSync }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
{{- end }}
