apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ .Values.env }}-dna-cs-frontend
  namespace: {{ .Values.namespace }}
  labels:
    name: frontend 
    env: {{ .Values.env }}
    project: {{ .Values.env }}-dna 
spec:
  destination:
    namespace: {{ .Values.env }}-dna-cs-workspaces
    server: {{ .Values.server | squote }}
  source:
    path: deployment/kubernetes/helm/charts/code-space-mfe
    repoURL: {{ .Values.repoURL | squote }}
    targetRevision: {{ .Values.branch }}
    helm:
      releaseName: codespace-mfe
      valueFiles:
        - values-{{ .Values.env }}.yaml
  project: {{ .Values.env }}-dna
{{- if .Values.enableSync }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
{{- end }}
