{{- if ne .Values.env "test" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ .Values.env }}-dna-neo4j
  namespace: {{ .Values.namespace }}
  labels:
    name: service
    env: {{ .Values.env }}
    project: {{ .Values.env }}-dna  
spec:
  destination:
    namespace: {{ .Values.env }}-dna-neo4j
    server: {{ .Values.server | squote }}
  source:
    path: deployment/kubernetes/helm/charts/neo4j
    repoURL: {{ .Values.repoURL | squote }}
    targetRevision: {{ .Values.branch }}
    helm:
      releaseName: neo4j-release
      valueFiles:
        - values-{{ .Values.env }}.yaml                 
  project: {{ .Values.env }}-dna
{{- if .Values.enableSync }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
{{- end }}
{{- end -}}
