apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: power-platform-db
  namespace: {{ .Values.env }}-dna-power-platform
  labels:
    name: db
spec:
  destination:
    namespace: {{ .Values.env }}-dna-power-platform
    server: {{ .Values.server | squote }}
  source:
    path: deployment/kubernetes/DyP/i3/postgresql-helm
    repoURL: {{ .Values.repoURL | squote }}
    targetRevision: {{ .Values.branch }}
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_ARGS          
          value: -f values-power-platform-db-{{ .Values.env }}.yaml --set namespace={{ .Values.env }}-dna-power-platform                     
  project: {{ .Values.env }}-dna
{{- if .Values.enableSync }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
{{- end }}