{{- if eq .Values.env "prod" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: prompt-craft-int
  namespace: {{ .Values.namespace }}
  labels:
    name: service
spec:
  destination:
    namespace: cs-apps-services
    server: {{ .Values.server | squote }}
  source:
    path: helm
    repoURL: https://git.i.mercedes-benz.com/DNA/prompt-craft.git
    targetRevision: {{ .Values.branch }}
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_ARGS
          value: --namespace cs-apps-services -f values-test.yaml
  project: {{ .Values.env }}-dna
{{- if .Values.enableSync }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
{{- end }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: prompt-craft-prod
  namespace: {{ .Values.namespace }}
  labels:
    name: service
spec:
  destination:
    namespace: cs-apps-services
    server: {{ .Values.server | squote }}
  source:
    path: helm
    repoURL: https://git.i.mercedes-benz.com/DNA/prompt-craft.git
    targetRevision: {{ .Values.branch }}
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_ARGS
          value: --namespace cs-apps-services -f values-prod.yaml
  project: {{ .Values.env }}-dna
{{- if .Values.enableSync }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
{{- end }}
{{- end }}      