apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ .Values.env }}-dna-kafka-cs-apps
  namespace: cs-apps-services
  labels:
    name: service
    project: dna
spec:
  destination:
    namespace: cs-apps-services
    server: {{ .Values.server | squote }}
  source:
    path: deployment/kubernetes/DyP/i3/i3-kafka/kafka-tenant
    repoURL: {{ .Values.repoURL | squote }}
    targetRevision: {{ .Values.branch }}
    helm:
      releaseName: {{ .Values.env }}-cs-apps-services
      valueFiles:
        - values-dev-prod.yaml 
  project: dna
{{- if .Values.enableSync }}
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
{{- end }}
