{{- if ne .Values.env "not-used" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ .Values.env }}-dna-openmetadata
  namespace: {{ .Values.namespace }}
  labels:
    name: service
    env: {{ .Values.env }}
    project: {{ .Values.env }}-dna  
spec:
  destination:
    namespace: {{ .Values.env }}-dna-openmetadata
    server: {{ .Values.server | squote }}
  source:
    path: deployment/kubernetes/helm/charts/openmetadata
    repoURL: {{ .Values.repoURL | squote }}
    targetRevision: {{ .Values.branch }}
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_ARGS
          value: --namespace openmetadata -f values-{{ .Values.env }}.yaml          
  project: {{ .Values.env }}-dna
{{- if .Values.enableSync }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
{{- end }}
{{- end }}
