apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ .Values.env }}-dna-dna-backend
  namespace: {{ .Values.namespace }}
  labels:
    name: backend
    env: {{ .Values.env }}
    project: {{ .Values.env }}-dna  
spec:
  destination:
    namespace: {{ .Values.env }}-dna
    server: {{ .Values.server | squote }}
  source:
    path: deployment/kubernetes/helm/charts/backend
    repoURL: {{ .Values.repoURL | squote }}
    targetRevision: {{ .Values.branch }}
    helm:
      releaseName: dna-app-backend
      valueFiles:
        - values-{{ .Values.env }}.yaml
  project: {{ .Values.env }}-dna
{{- if .Values.enableSync }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
{{- end }}
