apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: ingress-internet
  namespace: {{ .Values.namespace }}
  labels:
    name: dyp
    env: {{ .Values.env }}
    project: dna
spec:
  destination:
    namespace: ingress-internet
    server: {{ .Values.server | squote }}
  source:
    path: deployment/kubernetes/DyP/ingress
    repoURL: {{ .Values.repoURL | squote }}
    targetRevision: {{ .Values.branch }}
    helm:
      releaseName: ingress-internet
      skipCrds: false
      valueFiles:
        - values-{{ .Values.env }}.yaml    
  project: dna
{{- if .Values.enableSync }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
{{- end }}