apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: kafka
  namespace: {{ .Values.namespace }}
  labels:
    name: service
spec:
  destination:
    namespace: kafka
    server: {{ .Values.server | squote }}
  source:
    path: deployment/kubernetes/DyP/i3/i3-kafka/strimzi-kafka-operator
    repoURL: {{ .Values.repoURL | squote }}
    targetRevision: {{ .Values.branch }}
    helm:
      releaseName: kafka
      skipCrds: true
      valueFiles:
        - values-{{ .Values.env }}.yaml
  project: dna
{{- if .Values.enableSync }}
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
{{- end }}
