apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: dna-kong-gw
  namespace: {{ .Values.namespace }}
  labels:
    name: gateway
spec:
  destination:
    namespace: kong
    server: {{ .Values.server | squote }}
  source:
    path: deployment/helm
    repoURL: https://git.i.mercedes-benz.com/DNA/dna-kong.git
    targetRevision: {{ .Values.branch }}
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_ARGS
          value: -f values-{{ .Values.env }}.yaml -n kong
  project: dna
{{- if .Values.enableSync }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - PruneLast=true
      - Replace=true
{{- end }}
