apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: i3-logging
  namespace: {{ .Values.namespace }}
  labels:
    name: service
spec:
  destination:
    namespace: i3-logging
    server: {{ .Values.server | squote }}
  source:
    path: deployment/kubernetes/DyP/i3/i3-logging-helm
    repoURL: {{ .Values.repoURL | squote }}
    targetRevision: {{ .Values.branch }}
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_ARGS
          value: --namespace i3-logging -f values-{{ .Values.env }}.yaml
  project: dna
{{- if .Values.enableSync }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
{{- end }}
