apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: matomo
  namespace: {{ .Values.namespace }}
  labels:
    name: service
spec:
  destination:
    namespace: matomo
    server: {{ .Values.server | squote }}
  source:
    path: deployment/kubernetes/helm/charts/matomo
    repoURL: {{ .Values.repoURL | squote }}
    targetRevision: infra/matomosync-fix
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_ARGS         
          value: -f values-{{ .Values.env }}.yaml -n matomo      
  project: dna
{{- if .Values.enableSync }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
{{- end }}
