{{- if eq .Values.env "prod" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: parperless-ngx
  namespace: {{ .Values.namespace }}
  labels:
    name: service
spec:
  destination:
    namespace: tools
    server: {{ .Values.server | squote }}
  source:
    path: deployment/kubernetes/DyP/paperless-ngx
    repoURL: {{ .Values.repoURL | squote }}
    targetRevision: {{ .Values.branch }}
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_ARGS
          value: --namespace tools -f values-dyp.yaml
  project: dna
{{- if .Values.enableSync }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
{{- end }}
{{- end }}      