{{- $password := .Values.gitRepo.password -}}
{{- $username := .Values.gitRepo.username -}}
{{- range .Values.repositories }}
apiVersion: v1
kind: Secret
metadata:
  name: repo-{{ .name }}
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository  
  annotations:
    managed-by: argocd.argoproj.io
type: Opaque
data:
  password: {{ $password }}
  project: ZG5h
  type: Z2l0
  url: {{ .url | b64enc }}
  username: {{ $username }}
---
{{- end }}  