apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: vault-injector
  namespace: {{ .Values.namespace }}
  labels:
    name: service
    env: {{ .Values.env }}
    project: dna
spec:
  destination:
    namespace: vault-injector
    server: {{ .Values.server | squote }}
  source:
    path: deployment/kubernetes/DyP/vault-injector
    repoURL: {{ .Values.repoURL | squote }}
    targetRevision: {{ .Values.branch }}
    helm:
      releaseName: vault-injector
      valueFiles:
        - values-{{ .Values.env }}.yaml
  project: dna
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
  ignoreDifferences:     
  - group: admissionregistration.k8s.io                                                              
    kind: MutatingWebhookConfiguration
    jsonPointers:                                                                                    
    - /webhooks/0/clientConfig/caBundle
    - /webhooks/0/failurePolicy      