appName: notebooks
namespace: notebooks
app:
  jupyter:
    config:
      configproxy_auth_token: <path:kv/data/dna/kubernetesSecret/notebooks#configproxy_auth_token>
      kf_pipelines_endpoint: http://ml-pipeline-ui.kubeflow
  image:
    name: registry-emea.app.corpintra.net/dnaplatform/prod/jupyterhub:2.1.3
    pullPolicy: Always
  profileListImages:
    default: registry-emea.app.corpintra.net/dnaplatform/prod/pyspark-notebook-default:1.0.10
    tensorflow: registry-emea.app.corpintra.net/dnaplatform/prod/pyspark-notebook-tensorflow:1.0.10
    chronos: registry-emea.app.corpintra.net/dnaplatform/prod/pyspark-notebook:1.0-chronos
  proxy:
    image: registry-emea.app.corpintra.net/dnaplatform/prod/configurable-http-proxy:1.0.0
  hubConfig:
    name: hub-config
    KubeSpawnerimage: registry-emea.app.corpintra.net/dnaplatform/prod/pyspark-notebook-default:1.0.10
    securitycontext: https://dna.app.corpintra.net https://notebook.dna.app.corpintra.net login-int.mercedes-benz.com sso-int.mercedes-benz.com *.mercedes-benz.com
    serviceAccount: default-editor
    oauthAuthenticator: GenericOAuthenticator
    oauthClientId: <path:kv/data/dna/kubernetesSecret/notebooks#oauthClientId>
    oauthClientSecret: <path:kv/data/dna/kubernetesSecret/notebooks#oauthClientSecret>
    oauthCallback: https://notebook.dna.app.corpintra.net/hub/oauth_callback
    oauthAuthorizeUrl: https://sso.mercedes-benz.com/as/authorization.oauth2
    oauthTokenUrl: https://sso.mercedes-benz.com/as/token.oauth2
    oauthUserDataUrl: https://sso.mercedes-benz.com/idp/userinfo.openid
    oauthUsrKey: sub
    oauthLoginSvc: Mercedes-Benz OIDC
    prespawn_hook: ''
    enableUserNS: 'True'
    userNameSpaceTemplate: kubeflow
    vaultStorageAnnotations: |
      c.KubeSpawner.cmd = ['sh', '-c','. /vault/secrets/minio && start-notebook.sh']

      ## Make sure you have dummy secret path called "kv/dna/minio/DEFAULT"
      c.KubeSpawner.extra_annotations = {
        "vault.hashicorp.com/agent-init-first": "true",
        "vault.hashicorp.com/agent-inject": "true",
        "vault.hashicorp.com/agent-inject-secret-minio": "kv/dna/minio/DEFAULT",
        "vault.hashicorp.com/agent-inject-template-minio": "{{{{ range secrets \"kv/dna/minio/\" }}}}{{{{ $str := \"{username}\" | toUpper}}}}{{{{- if (eq . $str) }}}}{{{{ with secret (printf \"kv/dna/minio/%s\" .) }}}}{{{{ range $k, $v := .Data.data  }}}}export MINIO_ACCESS_KEY=\"{{{{ $k }}}}\"\nexport MINIO_SECRET_KEY=\"{{{{ $v }}}}\"{{{{ end }}}}{{{{ end }}}}{{{{- end }}}}{{{{ end }}}}",
        "vault.hashicorp.com/agent-pre-populate-only": "true",
        "vault.hashicorp.com/role": "dna",
        "vault.hashicorp.com/namespace": "fmas/prod",
        "vault.hashicorp.com/tls-skip-verify": "true",
        "traffic.sidecar.istio.io/excludeOutboundPorts": "443"
        }
ingress:
  enabled: true
  host: notebook.dna.app.corpintra.net
  annotations:
    traefik.frontend.rule.type: PathPrefix
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: 'true'
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: daimler-acme
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect@kubernetescrd 
Storage:
  storageClass: cinder
  accessModes: ReadWriteOnce
  size: 5G
resources:
  cpu: 1
  memory: 4G
