apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.conf.secretName }}
  labels:
    {{- include "imagepullsecret-patcher.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.conf.secretValue }}