apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: trino-backend-role-binding
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: trino-backend-sa
    namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: trino-backend-role