insert into customerjourneyphase_nsql(id,data)
values('1','{"name": "Brand Awareness | Brand & Vehicle Experience | AWARENESS"}'),
	  ('2','{"name": "Vehicle Awareness | Brand & Vehicle Experience | AWARENESS"}'),
	  ('3','{"name": "Friends Consultation| Brand & Vehicle Experience | AWARENESS"}'),
	  ('4','{"name": "Information Search | General Info Gathering | AWARENESS"}'),
	  ('5', '{"name": "Vehicle & Service Exploration | Targeted Research/Consultation | CONSIDERATION"}'),
	  ('6','{"name": "Vehicle & Service Comparison  | Targeted Research/Consultation | CONSIDERATION"}'),
	  ('7','{"name": "Recommendation & Consultation | Targeted Research/Consultation | CONSIDERATION"}'),
	  ('8','{"name": "Virtual Experience | Targeted Research/Consultation | CONSIDERATION"}'),
	  ('9', '{"name": "Configuration | Vehicle Selection | CONSIDERATION"}'),
	  ('10','{"name": "Stock Selection | Vehicle Selection | CONSIDERATION"}'),
	  ('11','{"name": "Test Drive - Physical | Test Drive | CONSIDERATION"}'),
	  ('12','{"name": "Vehicle Trade-In Assessment | Vehicle & Service Offering | CONSIDERATION"}'),
	  ('13', '{"name": "Flexible Ownership | Vehicle & Service Offering | CONSIDERATION"}'),
	  ('14','{"name": "Integrated Offer | Vehicle & Service Offering | CONSIDERATION"}'),
	  ('15','{"name": "Compare Offers | Vehicle & Service Offering | CONSIDERATION"}'),
	  ('16','{"name": "Price Negotiation (Model B specific) | Pricing & Committment | PURCHASE"}'),
	  ('17', '{"name": "MBM Credit Check/Financing | Pricing & Committment | PURCHASE"}'),
	  ('18','{"name": "Purchase Request | Pricing & Committment | PURCHASE"}'),
	  ('19','{"name": "Vehicle Order | Pricing & Committment | PURCHASE"}'),
	  ('20','{"name": "Waiting Phase Engagement | Waiting Phase | PURCHASE"}'),
	  ('21', '{"name": "Order Amendment | Waiting Phase | PURCHASE"}'),
	  ('22','{"name": "Charging Preparation | Waiting Phase | PURCHASE"}'),
	  ('23', '{"name": "Payment | Waiting Phase | PURCHASE"}'),
	  ('24','{"name": "Vehicle Handover | Vehicle Activation & Handover | HANDOVER"}'),
	  ('25','{"name": "Vehicle Explanation & Personalization | Vehicle Activation & Handover | HANDOVER"}'),
	  ('26','{"name": "Daily Usage | Vehicle Use | USAGE & CUSTOMER CARE"}'),
	  ('27', '{"name": "Accident & Damage Handling | Vehicle Use | USAGE & CUSTOMER CARE"}'),
	  ('28','{"name": "Breakdown Support | Vehicle Use | USAGE & CUSTOMER CARE"}'),
	  ('29','{"name": "Remote Services & Security | Vehicle Use | USAGE & CUSTOMER CARE"}'),
	  ('30','{"name": "Tire Change | Vehicle Care | USAGE & CUSTOMER CARE"}'),
	  ('31', '{"name": "Maintenance | Vehicle Care | USAGE & CUSTOMER CARE"}'),
	  ('32','{"name": "Repair (wear & tear) | Vehicle Care | USAGE & CUSTOMER CARE"}'),
	  ('33', '{"name": "Spare Parts Acquisition | Vehicle Care | USAGE & CUSTOMER CARE"}'),
	  ('34','{"name": "Recall & Field Management | Vehicle Care | USAGE & CUSTOMER CARE"}'),
	  ('35','{"name": "Warranty & Goodwill | Vehicle Care | USAGE & CUSTOMER CARE"}'),
	  ('36','{"name": "Mme - Vehicle/Customer Profile & Documentation | Vehicle Care | USAGE & CUSTOMER CARE"}'),
	  ('37', '{"name": "Vehicle Functionality Extension | Vehicle & Service Extension | USAGE & CUSTOMER CARE"}'),
	  ('38','{"name": "Service Contract Extension | Vehicle & Service Extension | USAGE & CUSTOMER CARE"}'),
	  ('39','{"name": "Digital Service Extension | Vehicle & Service Extension | USAGE & CUSTOMER CARE"}'),
	  ('40','{"name": "Mobility-as-a-Service | Vehicle & Service Extension | USAGE & CUSTOMER CARE"}'),
	  ('41', '{"name": "Sharing Vehicle | Vehicle & Service Extension | USAGE & CUSTOMER CARE"}'),
	  ('42','{"name": "Exchange in Communities | Feedback/ Complaint | USAGE & CUSTOMER CARE"}'),
	  ('43', '{"name": "Complaint & Feedback | Feedback/ Complaint | USAGE & CUSTOMER CARE"}'),
	  ('44','{"name": "Customer Support | Feedback/ Complaint | USAGE & CUSTOMER CARE"}'),
	  ('45','{"name": "T&C, Privacy | Dialog & Engagement | USAGE & CUSTOMER CARE"}'),
	  ('46','{"name": "Lifestyle & Travel Offer/Recommendation | Dialog & Engagement | USAGE & CUSTOMER CARE"}'),
	  ('47', '{"name": "Re-awareness, Attention & Benefits | Dialog & Engagement | USAGE & CUSTOMER CARE"}'),
	  ('48','{"name": "MBM Retention | Repurchase | RETENTION / LOYALTY"}'),
	  ('49','{"name": "Next Vehicle & Service Purchase | Repurchase | RETENTION / LOYALTY"}'),
	  ('50','{"name": "Lease Returns | Sell vehicle | RETENTION / LOYALTY"}'),
	  ('51', '{"name": "Reset vehicle | Sell vehicle | RETENTION / LOYALTY"}'),
	  ('52','{"name": "Transfer Of Ownership | Sell vehicle | RETENTION / LOYALTY"}'); 
	  
INSERT INTO marketingcommunicationchannel_nsql(id,data)
VALUES('1','{"name": "OneWeb"}'),
	('2','{"name": "E-Commerce"}'),
	('3','{"name": "In-Car, MBUX"}'),
	('4','{"name": "E-Mail"}'),
	('5','{"name": "SMS/MMS/Push"}'),
	('6','{"name": "Social"}'),
	('7','{"name": "Search"}'),
	('8','{"name": "CCC"}'),
	('9','{"name": "Retail"}'),
	('10','{"name": "Media/ Offsite"}'),
	('11','{"name": "In-App"}');