# {{- if ne .Values.env "dev" }}
# apiVersion: v1
# kind: Service
# metadata:
#   name: broker01
#   namespace: kafka
# spec:
#   ports:
#     - name: tcp-ctrlplane
#       protocol: TCP
#       port: 9090
#       targetPort: 9090
#     - name: tcp-replication
#       protocol: TCP
#       port: 9091
#       targetPort: 9091
#     - name: tcp-clients
#       protocol: TCP
#       port: 8001
#       targetPort: 9092
#   selector:
#     strimzi.io/cluster: my-cluster
#     strimzi.io/kind: Kafka
#     strimzi.io/name: my-cluster-kafka
#   type: ClusterIP
# {{- end -}}