apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafkaExporter:
    template:
      pod:
        metadata:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "9404"
            prometheus.io/path: "/metrics"
        securityContext:
          runAsUser: 1001
          fsGroup: 1001
  kafka:
    # version: 2.4.0
    replicas: 3
    authorization:
      type: simple  
      superUsers:
        - CN=dna-user           
    listeners:     
      - name: plain
        port: 9092
        type: internal
        tls: true
        authentication:
          type: tls        
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      auto.create.topics.enable: "true"
      inter.broker.protocol.version: "3.6"
      # Can be ignored if inter.broker.protocol.version is set to 3.0 or higher -> to avoid unnecessary rolling updates
      #log.message.format.version: "3.6"
    storage:
      type: persistent-claim
      size: {{ .Values.persistence.kafka }}
      class: {{ .Values.persistence.kafkaStorageClass }}
      deleteClaim: false
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
    template:
      pod:
        metadata:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "9404"
            prometheus.io/path: "/metrics"
        securityContext:
          runAsUser: 1001
          fsGroup: 1001
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: {{ .Values.persistence.zookeeper }}
      class: {{ .Values.persistence.zookeeperStorageClass }}
      deleteClaim: false
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: zookeeper-metrics-config.yml
    template:
      pod:
        metadata:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "9404"
            prometheus.io/path: "/metrics"
        securityContext:
          runAsUser: 1001
          fsGroup: 1001
  entityOperator:
    topicOperator: {}
    userOperator: {}
