image:
  registry: registry-emea.app.corpintra.net
  repository: publicquay
  name: strimzi/operator
  imagePullPolicy: Always
zookeeper:
  image:
    registry: registry-emea.app.corpintra.net
    repository: publicquay
    name: strimzi/kafka
kafka:
  image:
    registry: registry-emea.app.corpintra.net
    repository: publicquay
    name: strimzi/kafka
kafkaConnect:
  image:
    registry: registry-emea.app.corpintra.net
    repository: i3-releases
    name: strimzi_kafka_connect_debezium
kafkaConnects2i:
  image:
    registry: registry-emea.app.corpintra.net
    repository: publicquay
    name: strimzi/kafka
topicOperator:
  image:
    registry: registry-emea.app.corpintra.net
    repository: publicquay
    name: strimzi/operator
userOperator:
  image:
    registry: registry-emea.app.corpintra.net
    repository: publicquay
    name: strimzi/operator
kafkaInit:
  image:
    registry: registry-emea.app.corpintra.net
    repository: publicquay
    name: strimzi/operator
tlsSidecarZookeeper:
  image:
    registry: registry-emea.app.corpintra.net
    repository: publicquay
    name: strimzi/kafka
tlsSidecarKafka:
  image:
    registry: registry-emea.app.corpintra.net
    repository: publicquay
    name: strimzi/kafka
tlsSidecarEntityOperator:
  image:
    registry: registry-emea.app.corpintra.net
    repository: publicquay
    name: strimzi/kafka
kafkaMirrorMaker:
  image:
    registry: registry-emea.app.corpintra.net
    repository: publicquay
    name: strimzi/kafka
kafkaBridge:
  image:
    registry: registry-emea.app.corpintra.net
    repository: publicquay
    name: strimzi/kafka-bridge
kafkaExporter:
  image:
    registry: registry-emea.app.corpintra.net
    repository: publicquay
    name: strimzi/kafka
jmxTrans:
  image:
    registry: registry-emea.app.corpintra.net
    repository: publicquay
    name: strimzi/kafka
kafkaMirrorMaker2:
  image:
    registry: registry-emea.app.corpintra.net
    repository: publicquay
    name: strimzi/kafka
cruiseControl:
  image:
    registry: registry-emea.app.corpintra.net
    repository: publicquay
    name: strimzi/kafka
tlsSidecarCruiseControl:
  image:
    registry: registry-emea.app.corpintra.net
    repository: publicquay
    name: strimzi/kafka
resources:
  limits:
    memory: 512Mi
# If you set `watchNamespaces` to the same value as ``.Release.Namespace` (e.g. `helm ... --namespace $NAMESPACE`),
# the chart will fail because duplicate RoleBindings will be attempted to be created in the same namespace
watchNamespaces: 
  - i3-kafka
  - dev-dna-i3-kafka
  - test-dna-i3-kafka
  - prod-dna-i3-kafka
  - tools
# Overwrite default log level to get more detailed output
loglevel: DEBUG