# Default values for backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: dna
imagePullSecret: 
  name: vddockerhub
 
ingress:
  enabled: true
  namespace: ingress
  host: "ingress-host"
  lbIP: ""

  annotations:
    traefik.frontend.rule.type: PathPrefix
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: ""
app:
  backend:
    replicaCount: 1
    image: vardhandevalla/app-backend:2.0
    secrets: 
      name: app-secrets
      notebookSecretToken: ""
      oidcClientID: ""
      oidcClientSecret: ""
      drdCertPassword: xxxxx
      jwtSecretKey: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY0OTY2Mzg5MCwiaWF0IjoxNjQ5NjYzODkwfQ.0bHIjToqnWk5zOq0a-Bn-HV6jw6-bnVCNx56L5QnVkg
      s3AccessKey: minioadmin
      s3SecretKey: minioadmin
      dataikuProdApiKey: ""
      dataikuTrainingApiKey: ""
      avscanApiKey: ""
      appDBUserName: postgres
      appDBPassword: postgres
    config:
      enableItsmm: false
      enableJupyterNotebook: false
      enableDataiku: false
      enableAttachmentScan: false
      enableInternalUser: false
      redirectUrl:
      dbUri: jdbc:postgresql://bitnami-postgresql-bitnamipostgresql:5432/db
      oidcUserInfoUrl:
      oidcTokenIntrospectionUrl:
      oidcProvider: INTERNAL
      oidcTokenRevocationUrl:
      internalUserRequestUrl: xxxxx
      internalCertFile: xxxxx
      oidcDisabled: true
      s3BucketName: dna
      s3Url: http://minio:9000
      corosOriginUrl:
      jupyterNotebookUrl:
      vaultHost: vault.vault.svc.cluster.local
      vaultPort: 8200
      dataikuProdUri: 
      dataikuProdAdminGroup:
      dataikutraininguri:
      apacCorpDir: 
      emeaCorpDir:
      dataikuUserRoleUriPath: "/admin/users/"
      dataikuPermissionUriPath: "/permissions"
      avscanAppId: 
      naasBroker: kafka-1650536619-0.kafka-1650536619-headless.kafka.svc.cluster.local:9092
      loggingEnvironment: dev
      loggingPath: /tmp/app/log
      dataikuProjectUri: /projects/
      dataikuTrainingAdminGroup: 
      avscanUri: http://malware-backend:8181/avscan/api/v1
      flywayBaseline: "true"
      flywayBaselineOnMigrate: "true"
      flywayBaselineVersion: "0"
      flywaySchema: "public"
      dashboardUri: http://dashboard-backend-service.dashboard.svc.cluster.local:7173/dashboards

  vault:
    secret:
      name: vault-secrets
      rootToken: xxxxx
  probes:
    initialDelaySeconds: 120
    timeoutSeconds: 30
    periodSeconds: 10
    failureThreshold: 3
    livenessProbe:
      path: /actuator/health/liveness
      port: 7171
    readinessProbe:
      path: /actuator/health/readiness
      port: 7171 