namespace: dna
imagePullSecrets: null
ingress:
  enabled: false
  namespace: ingress
  host: dna.app.corpintra.net
  lbIP: 53.6.53.65
  annotations:
    traefik.frontend.rule.type: PathPrefix
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: 'true'
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: daimler-acme
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect@kubernetescrd
app:
  backend:
    replicaCount: 2
    image:
      repository: registry-emea.app.corpintra.net/dnaplatform/dna-backend
      tag: 3.4.5
    secrets:
      name: app-secrets
      notebookSecretToken: null
      oidcClientID: null
      oidcClientSecret: null
      drdCertPassword: null
      jwtSecretKey: null
      s3AccessKey: null
      s3SecretKey: null
      dataikuProdApiKey: null
      dataikuTrainingApiKey: null
      avscanApiKey: null
      appDBUserName: null
      appDBPassword: null
    config:
      enableItsmm: false
      enableJupyterNotebook: true
      enableDataiku: true
      enableAttachmentScan: true
      enableInternalUser: true
      redirectUrl: null
      dbUri: null
      oidcUserInfoUrl: null
      oidcTokenIntrospectionUrl: null
      oidcProvider: null
      oidcTokenRevocationUrl: null
      internalUserRequestUrl: null
      internalCertFile: null
      oidcDisabled: false
      s3BucketName: null
      s3Url: null
      corosOriginUrl: null
      jupyterNotebookUrl: null
      dataikuProdUri: null
      dataikuProdAdminGroup: null
      dataikutraininguri: null
      avscanAppId: null
      naasBroker: null
      loggingEnvironment: null
      loggingPath: null
      dataikuProjectUri: null
      apacCorpDir: null
      emeaCorpDir: null
      dataikuUserRoleUriPath: null
      dataikuPermissionUriPath: null
      dataikuTrainingAdminGroup: null
      avscanUri: null
      flywayBaseline: null
      flywayBaselineOnMigrate: null
      flywayBaselineVersion: null
      flywaySchema: null
      dashboardUri: null
      dataSourceBulkCreateApiAccessToken: null
  probes:
    initialDelaySeconds: 120
    timeoutSeconds: 30
    periodSeconds: 10
    failureThreshold: 3
    livenessProbe:
      path: /actuator/health/liveness
      port: 7171
    readinessProbe:
      path: /actuator/health/readiness
      port: 7171
vaultInjector:
  enable: true
  annotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/role: dna
    vault.hashicorp.com/namespace: fmas/prod
    vault.hashicorp.com/tls-skip-verify: 'true'
    vault.hashicorp.com/agent-pre-populate-only: 'true'
    vault.hashicorp.com/agent-inject-secret-truststore.jks: kv/dna/kubernetesSecret/kafka
    vault.hashicorp.com/agent-inject-template-truststore.jks: |
      {{- with secret "kv/dna/kubernetesSecret/kafka" -}}
      {{ base64Decode  .Data.data.TRUSTSTORE }}
      {{- end }}
    vault.hashicorp.com/agent-inject-secret-keystore.p12: kv/dna/kubernetesSecret/kafka
    vault.hashicorp.com/agent-inject-template-keystore.p12: |
      {{- with secret "kv/dna/kubernetesSecret/kafka" -}}
      {{ base64Decode  .Data.data.KEYSTORE }}
      {{- end }}      
    vault.hashicorp.com/agent-inject-secret-envvar: kv/dna/kubernetesSecret/dnaBackend
    vault.hashicorp.com/agent-inject-template-envvar: |
      {{- with secret "kv/dna/kubernetesSecret/dnaBackend" -}}
        {{- range $k, $v := .Data.data }}
            export {{ $k }}="{{ $v }}"
        {{- end }}
      {{- end }}
      {{- with secret "kv/dna/kubernetesSecret/kafka" -}}
        {{- range $k, $v := .Data.data }}
        {{- if or (eq $k "KEYSTORE_PASSWORD") (eq $k "TRUSTSTORE_PASSWORD") (eq $k "KEYSTORE_PATH") (eq $k "TRUSTSTORE_PATH") }}
            export {{ $k }}="{{ $v }}"
        {{- end }}        
        {{- end }}      
      {{- end }}      
  saName: default
  jarName: dnambc*.jar
podDisruptionBudget:
  enabled: true
  minAvailable: 50%
