namespace: dev-dna-trino
image:
  repository: registry-emea.app.corpintra.net/dnaplatform/trino-backend
  tag: '104'
imagePullPolicy: Always
imagePullSecret:
  name: imagepullsecret
secret:
  name: trinobackend-secrets
  minioSecretKey: null
  trinoPassword: null
  jwtKey: null
envs:
  - name: MINIO_SECRETKEY
    valueFrom:
      secretKeyRef:
        key: minio.secretkey
        name: trinobackend-secrets
  - name: TRINO_PASSWORD
    valueFrom:
      secretKeyRef:
        key: trino.password
        name: trinobackend-secrets
  - name: JWT_SECRET_KEY
    valueFrom:
      secretKeyRef:
        key: jwt.secret.key
        name: trinobackend-secrets
  - name: DNA_URI
    value: null
  - name: DNA_AUTH_ENABLE
    value: 'true'
  - name: MINIO_BASEURI
    value: null
  - name: MINIO_ACCESSKEY
    value: ''
  - name: TRINO_BASEURI
    value: null
  - name: TRINO_USER
    value: ''
  - name: TRINO_CATALOG
    value: ''
  - name: SWAGGER_HEADER_AUTH
    value: XXXXX
  - name: CORS_ORIGIN_URL
    value: null
  - name: LOGGING_ENVIRONMENT
    value: DEV
  - name: LOGGING_PATH
    value: /var/log
  - name: TRINO_SSL
    value: ''
  - name: TRINO_SSLVERIFICATION
    value: null
  - name: TRINO_UNIX_HADOOP_REMOTEUSER
    value: null
containerPort: 7575
ingress:
  enabled: false
  host: trino.dna-aws.app.corpintra.net
  annotations:
    traefik.frontend.rule.type: PathPrefix
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: 'true'
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: mercedes-benz-acme
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect@kubernetescrd
resources:
  requests:
    memory: 512Mi
    cpu: 250m
  limits:
    memory: 1000Mi
    cpu: 500m
probes:
  initialDelaySeconds: 120
  timeoutSeconds: 10
  periodSeconds: 20
  failureThreshold: 3
  livenessProbe:
    path: /actuator/health/liveness
    port: api
  readinessProbe:
    path: /actuator/health/readiness
    port: api
vaultInjector:
  enable: true
  annotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/role: dna
    vault.hashicorp.com/tls-skip-verify: 'true'
    vault.hashicorp.com/namespace: DnAPlatform/dev
    vault.hashicorp.com/agent-image: registry-emea.app.corpintra.net/dnaplatform/vault-secret-auto-update:v1
    vault.hashicorp.com/agent-inject-command-envvar: sh /opt/restart_deployment.sh
    vault.hashicorp.com/template-static-secret-render-interval: 10s
    vault.hashicorp.com/agent-pre-populate-only: 'false'
    vault.hashicorp.com/agent-inject-secret-truststore.jks: kv/dna/kubernetesSecret/kafka
    vault.hashicorp.com/agent-inject-template-truststore.jks: |
      {{- with secret "kv/dna/kubernetesSecret/kafka" -}}
      {{ base64Decode  .Data.data.TRUSTSTORE }}
      {{- end }}
    vault.hashicorp.com/agent-inject-secret-keystore.p12: kv/dna/kubernetesSecret/kafka
    vault.hashicorp.com/agent-inject-template-keystore.p12: |
      {{- with secret "kv/dna/kubernetesSecret/kafka" -}}
      {{ base64Decode  .Data.data.KEYSTORE }}
      {{- end }}
    vault.hashicorp.com/agent-inject-secret-envvar: kv/dna/kubernetesSecret/trinoService
    vault.hashicorp.com/agent-inject-template-envvar: |
      {{- with secret "kv/dna/kubernetesSecret/trinoService" -}}
        {{- range $k, $v := .Data.data }}
            export {{ $k }}="{{ $v }}"
        {{- end }}
      {{- end }}
      {{- with secret "kv/dna/kubernetesSecret/kafka" -}}
        {{- range $k, $v := .Data.data }}
        {{- if or (eq $k "KEYSTORE_PASSWORD") (eq $k "TRUSTSTORE_PASSWORD") (eq $k "KEYSTORE_PATH") (eq $k "TRUSTSTORE_PATH") }}
            export {{ $k }}="{{ $v }}"
        {{- end }}        
        {{- end }}      
      {{- end }}        
  saName: default
  jarName: trino-backend-lib*.jar
