appName: clamav
namespace: clamav
securityContext:
  runasUser: 100
app:
  backend:
    name: clamav-rest
    image:
      repository: registry-emea.app.corpintra.net/dnaplatform/malwarescan-backend
      tag: 3ccc860f5cdb125b396c8e7f3358c3a5e9cab344
    replicaCount: 1
    secrets:
      name: oneapi-secrets
      onapiBasicAuthToken: null
      jwtSecretKey: null
      appDBUserName: null
      appDBPassword: null
    config:
      clamav_backend_url: clamav-service
      clamav_backend_port: 3310
      max_file_size: 4000MB
      max_request_size: 4000MB
      api_request_limit: 20
      with_in: 2
      time_unit: seconds
      auth_api_host: null
      restricted_url_pattern: null
      loggingPath: /tmp/clamav/log
      loggingEnvironment: dev
      corsOriginUrl: null
      dbUri: null
      flywayEnabled: true
      flywayBaselineOnMigrate: true
      flywayBaselineVersion: 0
      flywaySchema: public
      vaultHost: null
      vaultPort: null
      appUrl: null
      enableAuth: true
      verifyLoginApi: null
      unscribeMalwareScanApi: null
      naas_broker: null
  vault:
    secret:
      rootToken: null
  probes:
    initialDelaySeconds: 60
    timeoutSeconds: 10
    periodSeconds: 10
    failureThreshold: 3
    livenessProbe:
      path: /actuator/health/liveness
      port: api
    readinessProbe:
      path: /actuator/health/readiness
      port: api
image:
  repo: registry-emea.app.corpintra.net/dnaplatform/clamav:2024-10-14
  replicaCount: 1
  pullPolicy: Always
  tag: '41'
ingress:
  enabled: false
  host: scan.dev.dna.app.corpintra.net
  certificateIssuer: daimler-acme
  prefix: /internal
  annotations:
    traefik.frontend.rule.type: PathPrefix
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: 'true'
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: daimler-acme
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect@kubernetescrd
imagePullSecret:
  name: imagepullsecret
Storage:
  storageClass: cinder
  accessModes: ReadWriteOnce
  size: 5G
resources:
  requests:
    memory: 500Mi
    cpu: 500m
  limits:
    memory: 5000Mi
    cpu: 3
vaultInjector:
  enable: true
  annotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/role: dna
    vault.hashicorp.com/tls-skip-verify: 'true'
    vault.hashicorp.com/namespace: fmas/dev
    vault.hashicorp.com/agent-image: registry-emea.app.corpintra.net/dnaplatform/vault-secret-auto-update:v1
    vault.hashicorp.com/agent-inject-command-envvar: sh /opt/restart_deployment.sh
    vault.hashicorp.com/template-static-secret-render-interval: 10s
    vault.hashicorp.com/agent-pre-populate-only: 'false'
    vault.hashicorp.com/agent-inject-secret-truststore.jks: kv/dna/kubernetesSecret/kafka
    vault.hashicorp.com/agent-inject-template-truststore.jks: |
      {{- with secret "kv/dna/kubernetesSecret/kafka" -}}
      {{ base64Decode  .Data.data.TRUSTSTORE }}
      {{- end }}
    vault.hashicorp.com/agent-inject-secret-keystore.p12: kv/dna/kubernetesSecret/kafka
    vault.hashicorp.com/agent-inject-template-keystore.p12: |
      {{- with secret "kv/dna/kubernetesSecret/kafka" -}}
      {{ base64Decode  .Data.data.KEYSTORE }}
      {{- end }}      
    vault.hashicorp.com/agent-inject-secret-envvar: kv/dna/kubernetesSecret/malwareService
    vault.hashicorp.com/agent-inject-template-envvar: |
      {{- with secret "kv/dna/kubernetesSecret/malwareService" -}}
        {{- range $k, $v := .Data.data }}
            export {{ $k }}="{{ $v }}"
        {{- end }}
      {{- end }}
      {{- with secret "kv/dna/kubernetesSecret/kafka" -}}
        {{- range $k, $v := .Data.data }}
        {{- if or (eq $k "KEYSTORE_PASSWORD") (eq $k "TRUSTSTORE_PASSWORD") (eq $k "KEYSTORE_PATH") (eq $k "TRUSTSTORE_PATH") }}
            export {{ $k }}="{{ $v }}"
        {{- end }}        
        {{- end }}      
      {{- end }}         
  saName: default
  jarName: malwarescan-lib*.jar
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 3
