namespace: data-product
configJs: |
  window["DATA_PRODUCT_INJECTED_ENVIRONMENT"]={
    CONTAINER_APP_URL: "https://dna.app.corpintra.net",
    API_BASEURL: "https://dna.app.corpintra.net/api",
    DATA_PRODUCT_API_BASEURL: "https://data-product.dna.app.corpintra.net/api",
    DATA_GOVERNANCE_HTML_FOR_CHINA_DATA: '<p>If yes, and due to the complexity of corresponding Data Governance requirements, we recommend you reach out to us at the <a href="https://localhost" target="_blank" rel="noopener noreferrer"> Data Governance Office FM </a> directly.</p>',
    DATA_PRODUCT_TOU_HTML: '<div>I agree to <a href="#" target="_blank" rel="noopener noreferrer">terms of use</a></div>'
  };
replicaCount: 2
image:
  repository: registry-emea.app.corpintra.net/dnaplatform/data-product-mfe
  pullPolicy: IfNotPresent
  tag: 1.3.3
imagePullSecrets:
  - name: imagepullsecret
nameOverride: ''
fullnameOverride: data-product-mfe
podSecurityContext:
  runAsUser: 1001
containerPort: 4000
service:
  type: ClusterIP
  port: 90
ingress:
  enabled: true
  annotations:
    traefik.frontend.rule.type: PathPrefix
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: 'true'
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: daimler-acme
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect@kubernetescrd
  hosts:
    - host: data-product.dna.app.corpintra.net
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - data-product.dna.app.corpintra.net
      secretName: data-product-tls-secret
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
vaultInjector:
  enable: true
  annotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/role: dna
    vault.hashicorp.com/tls-skip-verify: 'true'
    vault.hashicorp.com/namespace: fmas/prod
    vault.hashicorp.com/agent-pre-populate-only: 'true'
    vault.hashicorp.com/agent-inject-secret-configjs: kv/dna/kubernetesSecret/dataProductMFE
    vault.hashicorp.com/agent-inject-file-configjs: config.js
    vault.hashicorp.com/agent-inject-template-configjs: |
      {{- with secret "kv/dna/kubernetesSecret/dataProductMFE" -}}
          window["DATA_PRODUCT_INJECTED_ENVIRONMENT"]={
          {{- range $k, $v := .Data.data }}
          {{- if or (eq $v "true") (eq $v "false") (regexMatch "^[0-9]+$" $v) }}
                  {{ $k }}:{{ $v }},
          {{ else }}
                  {{ $k }}:'{{ $v }}',
          {{- end }}
          {{- end }}
              };
      {{- end }}   
  saName: default
podDisruptionBudget:
  enabled: true
  minAvailable: 50%
