namespace: chronos
configJs: |
  window["chronos_INJECTED_ENVIRONMENT"]={
    CONTAINER_APP_URL: "https://dna.app.corpintra.net",
    API_BASEURL: "https://dna.app.corpintra.net/api",
    CHRONOS_API_BASEURL: "",
  };
replicaCount: 2
chronosbackend: http://chronos-be.chronos.svc.cluster.local:80
image:
  repository: registry-emea.app.corpintra.net/dnaplatform/chronos-mfe
  pullPolicy: IfNotPresent
  tag: 1.7.5
imagePullSecrets:
  - name: imagepullsecret
nameOverride: ''
fullnameOverride: chronos-mfe
podSecurityContext:
  runAsUser: 1001
containerPort: 4000
service:
  type: ClusterIP
  port: 90
ingress:
  enabled: true
  annotations:
    traefik.frontend.rule.type: PathPrefix
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: 'true'
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: daimler-acme
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect@kubernetescrd
  hosts:
    - host: chronos.dna.app.corpintra.net
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - chronos.dna.app.corpintra.net
      secretName: chronos-tls-secret
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
vaultInjector:
  enable: true
  annotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/role: 'dna_prod_k8_role'
    vault.hashicorp.com/tls-skip-verify: 'true'
    vault.hashicorp.com/agent-pre-populate-only: 'true'
    vault.hashicorp.com/agent-inject-secret-configjs: dna_kv/prod/kubernetesSecret/chronosMFE
    vault.hashicorp.com/agent-inject-file-configjs: config.js
    vault.hashicorp.com/agent-inject-template-configjs: |
      {{- with secret "dna_kv/prod/kubernetesSecret/chronosMFE" -}}
          window["CHRONOS_INJECTED_ENVIRONMENT"]={
          {{- range $k, $v := .Data.data }}
          {{- if or (eq $v "true") (eq $v "false") (regexMatch "^[0-9]+$" $v) }}
                  {{ $k }}:{{ $v }},
          {{ else }}
                  {{ $k }}:'{{ $v }}',
          {{- end }}
          {{- end }}
              };
      {{- end }}   
  saName: default
podDisruptionBudget:
  enabled: true
  minAvailable: 50%
