apiVersion: v1
appVersion: 5.1.1
description: I³ PostgreSQL provides high availability and easy replication mainly for DHC CaaS. In addition it handles backup/restore and includes security hardening.
home: https://git.daimler.com/i3/i3-postgresql
maintainers:
- email: i3.consulting@mercedes-benz.com
  name: i3 Team
name: postgresql-helm
version: 5.1.1-2022.6.15
