apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: az-blob-fuse
  namespace: <<namespace-name>>
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: default