appName: naas
namespace: test-dna-naas
app:
  backend:
    replicaCount: 1
    image: registry-emea.app.corpintra.net/dnaplatform/naas-backend:b785186ddd6169023867e57010fde96e9995b3f9
    secrets:
      name: naas-app-secrets
      jwtKey: null
      db:
        appUserName: null
        appPassword: null
    config:
      api_db_url: null
      naas_broker: null
      max_poll_records: null
      dna_uri: null
      dna_auth_enable: null
      mailServerHost: null
      mailServerPort: null
      notificationSenderEmail: null
      poll_time: null
      naas_central_topic: null
      naas_centralread_topic: null
      naas_centraldelte_topic: null
      loggingPath: null
      loggingEnvironment: null
      corsOriginUrl: null
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1000Mi
      cpu: 500m
  probes:
    initialDelaySeconds: 900
    timeoutSeconds: 10
    periodSeconds: 30
    failureThreshold: 3
    livenessProbe:
      path: /actuator/health/liveness
      port: api
    readinessProbe:
      path: /actuator/health/readiness
      port: api
image:
  pullPolicy: Always
  tag: '69'
ingress:
  enabled: false
  host: naas.test.dna.app.corpintra.net
  annotations:
    traefik.frontend.rule.type: PathPrefix
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: 'true'
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: mercedes-benz-acme
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect@kubernetescrd
imagePullSecret:
  name: imagepullsecret
vaultInjector:
  enable: true
  annotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/role: dna
    vault.hashicorp.com/tls-skip-verify: 'true'
    vault.hashicorp.com/namespace: DnAPlatform/staging
    vault.hashicorp.com/agent-image: registry-emea.app.corpintra.net/dnaplatform/vault-secret-auto-update:v1
    vault.hashicorp.com/agent-inject-command-envvar: sh /opt/restart_deployment.sh
    vault.hashicorp.com/template-static-secret-render-interval: 10s
    vault.hashicorp.com/agent-pre-populate-only: 'false'
    vault.hashicorp.com/agent-inject-secret-truststore.jks: kv/dna/kubernetesSecret/kafka
    vault.hashicorp.com/agent-inject-template-truststore.jks: |
      {{- with secret "kv/dna/kubernetesSecret/kafka" -}}
      {{ base64Decode  .Data.data.TRUSTSTORE }}
      {{- end }}
    vault.hashicorp.com/agent-inject-secret-keystore.p12: kv/dna/kubernetesSecret/kafka
    vault.hashicorp.com/agent-inject-template-keystore.p12: |
      {{- with secret "kv/dna/kubernetesSecret/kafka" -}}
      {{ base64Decode  .Data.data.KEYSTORE }}
      {{- end }}      
    vault.hashicorp.com/agent-inject-secret-envvar: kv/dna/kubernetesSecret/naasService
    vault.hashicorp.com/agent-inject-template-envvar: |
      {{- with secret "kv/dna/kubernetesSecret/naasService" -}}
        {{- range $k, $v := .Data.data }}
            export {{ $k }}="{{ $v }}"
        {{- end }}
      {{- end }}
      {{- with secret "kv/dna/kubernetesSecret/kafka" -}}
        {{- range $k, $v := .Data.data }}
        {{- if or (eq $k "KEYSTORE_PASSWORD") (eq $k "TRUSTSTORE_PASSWORD") (eq $k "KEYSTORE_PATH") (eq $k "TRUSTSTORE_PATH") }}
            export {{ $k }}="{{ $v }}"
        {{- end }}        
        {{- end }}      
      {{- end }}      
  saName: default
  jarName: naas-lib*.jar
