{{- if .Values.lb.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . }}-lb
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.lb.ip }}
  loadBalancerSourceRanges:
    - 53.0.0.0/8
  selector:
    app.kubernetes.io/name: {{ include "postgres.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    role: master #set by patroni
  ports:
    - port: {{ .Values.lb.port }}
      name: postgresql
      targetPort: postgresql
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "postgres.fullname" . }}.outside-infra.ingress
  namespace: {{ .Values.namespace }}
spec:
  ingress:
    - {}
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "postgres.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Ingress
{{- end}}