{{- if and .Values.secrets.enabled (not .Values.secrets.externalSecretName) }}
# secrets
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}
  namespace: {{ .Values.namespace }}

  labels:
    app.kubernetes.io/name: {{ include "postgres.name" . }}
    helm.sh/chart: {{ include "postgres.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.dbusers.backup.username }}
  postgres.backupuser.username : {{ .Values.dbusers.backup.username | b64enc }}
  postgres.backupuser.password : {{ .Values.dbusers.backup.password | b64enc }}
  {{- end }}
  {{- if .Values.dbusers.dbadm.username }}
  postgres.dbadm.username : {{ .Values.dbusers.dbadm.username | b64enc }}
  postgres.dbadm.password : {{ .Values.dbusers.dbadm.password | b64enc }}
  {{- end }}
  {{- if .Values.dbusers.patroni.password }}
  postgres.patroniuser.password : {{ .Values.dbusers.patroni.password | b64enc }}
  {{- end }}
  {{- if .Values.dbusers.pgmon.username }}
  postgres.pgmon.username : {{ .Values.dbusers.pgmon.username | b64enc }}
  postgres.pgmon.password : {{ .Values.dbusers.pgmon.password | b64enc }}
  {{- end }}
  {{- if .Values.dbusers.debezium.password }}
  postgres.debezium.username : {{ .Values.dbusers.debezium.username | b64enc }}
  postgres.debezium.password : {{ .Values.dbusers.debezium.password | b64enc }}
  {{- end }}
  {{- if .Values.dbusers.dataCatalog.password }}
  postgres.dataCatalog.password: {{ .Values.dbusers.dataCatalog.password | b64enc }}
  {{- end }}
  {{- if .Values.s3.accesskey }}
  postgres.s3.accesskey: {{ .Values.s3.accesskey | b64enc }}
  postgres.s3.secretkey: {{ .Values.s3.secretkey | b64enc }}
  {{- end }}
  {{- if and .Values.SSL.enabled .Values.SSL.tlscrt }}
  postgres.tls.crt: {{ .Values.SSL.tlscrt }}
  {{- end }}
  {{- if and .Values.SSL.enabled .Values.SSL.tlskey }}
  postgres.tls.key: {{ .Values.SSL.tlskey }}
  {{- end }}
  {{- if and .Values.encryptBackupWal.enabled .Values.encryptBackupWal.publicKey }}
  encryptBackupWal.publicKey: {{ .Values.encryptBackupWal.publicKey }}
  {{- end }}
  {{- if and .Values.encryptBackupWal.enabled .Values.encryptBackupWal.keyId }}
  encryptBackupWal.keyId: {{ .Values.encryptBackupWal.keyId | b64enc }}
  {{- end }}
{{- end }}
{{- if and (not .Values.secrets.externalGpgSecretName) .Values.decryptBackupWal.enabled .Values.decryptBackupWal.privateKey .Values.decryptBackupWal.passphrase }}
---
# private key
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}-privatekey
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "postgres.name" . }}
    helm.sh/chart: {{ include "postgres.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- if and .Values.decryptBackupWal.enabled .Values.decryptBackupWal.passphrase }}
  decryptBackupWal.passphrase: {{ .Values.decryptBackupWal.passphrase | b64enc }}
  {{- end }}
  {{- if and .Values.decryptBackupWal.enabled .Values.decryptBackupWal.privateKey }}
  decryptBackupWal.privateKey: {{ .Values.decryptBackupWal.privateKey }}
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "i3secret-%s" (include "postgres.fullname" .) | trunc 63 | trimSuffix "-"}}
  namespace: {{ .Values.namespace }}
  labels:
    i3-product: i3-postgresql
    i3-version: {{.Chart.AppVersion}}
    i3-dep-postgresql: {{required (print "image tag has unsupported format: " .Values.image.tag)  (.Values.image.tag | regexFind ".*?-" | trimSuffix "-" | quote)}}
type: Opaque
stringData: