insert into additionalresources_nsql(id,data)
values('1','{"name": "Yes (For implementing a new solution)"}'),
      ('2','{"name": "No"}'),
	  ('3','{"name": "Yes (For an existing solution)"}');
	  
insert into algorithm_nsql(id,data)
values('1','{"name": "Bayesian Networks"}'),
('2','{"name": "Python"}'),
('3','{"name": "Databricks"}'),
('4','{"name": "TTS"}'),
('5','{"name": "STT"}'),
('6','{"name": "Pyth"}'),
('7','{"name": "NLU"}'),
('8','{"name": "Bert"}'),
('9','{"name": "LOGISTIC REGRESSION"}'),
('10','{"name": "DECISION TREE"}'),
('11','{"name": "NAIVE BAYES"}'),
('12','{"name": "K-MEANS"}'),
('13','{"name": "RANDOM FOREST"}'),
('14','{"name": "XGBOOST"}'),
('15','{"name": "LINEAR REGRESSION (OLS)"}'),
('16','{"name": "SUPPORT VECTOR MACHINES (SVM)"}'),
('17','{"name": "WEIGHTED LINEAR REGRESSION"}'),
('18','{"name": "HIERARCHICAL LINEAR MODELLING (HLM)"}'),
('19','{"name": "RECURRENT NEURAL NETWORKS"}'),
('20','{"name": "GRADIENT BOOSTING TREE"}'),
('21','{"name": "NON LINEAR OPTIMIZATION"}'),
('22','{"name": "ARIMA"}'),
('23','{"name": "ETS"}'),
('24','{"name": "THETAM"}'),
('25','{"name": "NNETAR"}'),
('26','{"name": "STLM"}'),
('27','{"name": "TBATS"}'),
('28','{"name": "SNAIVE"}'),
('29','{"name": "BORUTA"}'),
('30','{"name": "CLUSTERING"}'),
('31','{"name": "RIDGE REGRESSION"}'),
('32','{"name": "ISOLATED FOREST"}'),
('33','{"name": "COLLABORATIVE FILTERING"}'),
('34','{"name": "FP-GROWTH"}'),
('35','{"name": "SPLINE FITTING"}'),
('36','{"name": "DEEP LEARNING"}'),
('37','{"name": "CONSTRAINT BASED OPTIMIZATION"}'),
('38','{"name": "INHOUSE MODEL"}'),
('40','{"name": "XSM BOOSTR MODEL"}'),
('41','{"name": "GRAPH NEURONAL NETWORK"}'),
('42','{"name": "REINFORCEMENT LEARNING"}'),
('43','{"name": "SOFT ACTOR CRITIC"}'),
('44','{"name": "CLASSIFICATION"}'),
('45','{"name": "REGRESSION"}'),
('46','{"name": "NLP"}'),
('47','{"name": "AUTOMATION"}'),
('48','{"name": "DBSCAN"}'),
('49','{"name": "FEATURE IMPORTANCE"}'),
('50','{"name": "GAUSSIAN MIXTURE MODELS"}'),
('51','{"name": "NATURAL LANGUAGE PROCESSING"}'),
('52','{"name": "Verseagility Toolkit"}'),
('53','{"name": "Chain Ladder Method"}'),
('54','{"name": "Unobserved Component"}'),
('55','{"name": "Factor Analysis"}'),
('56','{"name": "KPI Calculations"}'),
('57','{"name": "Principal Component Analysis (PCA)"}'),
('58','{"name": "S"}'),
('59','{"name": "da"}'),
('60','{"name": "NLG"}'),
('61','{"name": "GPT3"}'),
('62','{"name": "FP-MAX"}'),
('63','{"name": "Frequent Itemset"}'),
('64','{"name": "CATBOOST"}'),
('65','{"name": "UAP"}'),
('66','{"name": "Zerolayer"}'),
('67','{"name": "Databr"}'),
('68','{"name": "PySpark"}'),
('69','{"name": "Azure"}'),
('70','{"name": "control chart"}'),
('71','{"name": "SUPPORT VECTOR MACHINES (SVM) / RECURRENT NEURAL NETWORKS / ISOLATED FOREST"}'),
('72','{"name": "RDF"}'),
('73','{"name": "Synapse"}'),
('74','{"name": "a"}'),
('75','{"name": "SKTime"}');
	  
insert into benefitrelevance_nsql(id,data)
values('1','{"name": "Very High"}'),
      ('2','{"name": "High"}'),
	  ('3','{"name": "Relatively High"}'),
	  ('4','{"name": "Relatively Low"}'),
	  ('5','{"name": "Low"}'),
	  ('6','{"name": "Very Low"}');
	  
insert into businessgoal_nsql(id,data)
values('1','{"name": "Transparency"}'),
      ('2','{"name": "Revenue"}'),
	  ('3','{"name": "Savings"}'),
	  ('4','{"name": "Legal Mandatory"}'),
	  ('5','{"name": "Foundation"}');
	
insert into category_nsql(id,data)
values('1','{"name": "Algorithms"}'),
      ('2','{"name": "Data Sources"}'),
	  ('3','{"name": "Languages"}'),
	  ('4','{"name": "Platform"}'),
	  ('5','{"name": "Tags"}'),
	  ('6','{"name": "Visualization"}'),
	  ('7','{"name": "Related Products"}');
	  
insert into datasource_nsql (id, data)
values('1','{"name": "NACOS"}'),
('3','{"name": "GO-DWH"}'),
('4','{"name": "VEGA"}'),
('5','{"name": "KUFRI DATA, MAPIS, OPRA, COMPETITOR DATA (JATO, JD POWER), CAMPAIGN DATA"}'),
('6','{"name": "EMAILS, LOGFILES"}'),
('7','{"name": "MARKET RESEARCH AFTER-SALES (MRA)"}'),
('8','{"name": "VEGE"}'),
('9','{"name": "EQ REGISTRATION"}'),
('10','{"name": "INFAS 360"}'),
('11','{"name": "CRIS"}'),
('12','{"name": "ME ID"}'),
('13','{"name": "OPEN SOURCE"}'),
('14','{"name": "XENTRY DIAGNOSIS"}'),
('15','{"name": "AQUA"}'),
('16','{"name": "TIPS"}'),
('17','{"name": "TIPS"}'),
('18','{"name": "KNOWLEDGE DATABASE"}'),
('19','{"name": "AQUA"}'),
('20','{"name": "AQUA"}'),
('21','{"name": "VDC"}'),
('22','{"name": "CESAR"}'),
('23','{"name": "SWT"}'),
('24','{"name": "VPM"}'),
('25','{"name": "AUTOLINE"}'),
('26','{"name": "VSE"}'),
('27','{"name": "PUMA"}'),
('28','{"name": "GLOBUS"}'),
('29','{"name": "START"}'),
('30','{"name": "DIALOG"}'),
('31','{"name": "GSS"}'),
('32','{"name": "WPP"}'),
('33','{"name": "PPO"}'),
('34','{"name": "SBIM"}'),
('35','{"name": "MEC (SAP BI)"}'),
('36','{"name": "IHS"}'),
('37','{"name": "MONHTLY MARKET SEGMENT FORECAST"}'),
('38','{"name": "DIP"}'),
('39','{"name": "ICMS"}'),
('40','{"name": "TDS"}'),
('41','{"name": "SALESFORCE OS"}'),
('42','{"name": "SALES TRANSACTION SYSTEM"}'),
('43','{"name": "SBS"}'),
('44','{"name": "ICON"}'),
('45','{"name": "DIMS"}'),
('46','{"name": "CCC INSIGHTS"}'),
('47','{"name": "XENTRY PORTAL PARTS INFORMATION"}'),
('48','{"name": "VEDOC"}'),
('49','{"name": "GEOLOCATION DATA (ANAGOG SDK)"}'),
('50','{"name": "C4ME APP ANALYTICS DATA"}'),
('51','{"name": "OFFER DATA"}'),
('52','{"name": "DMP"}'),
('53','{"name": "CDM"}'),
('54','{"name": "CPD"}'),
('55','{"name": "XENTRY SERVICE MANAGEMENT"}'),
('56','{"name": "MBCPOS"}'),
('57','{"name": "REPORT2WEB"}'),
('58','{"name": "ONLINE SERVICE BOOKING ADVISOR"}'),
('59','{"name": "MAPIS"}'),
('60','{"name": "SP START"}'),
('61','{"name": "ISP4D"}'),
('62','{"name": "ADOBE ANALYTICS (ONEWEB)"}'),
('63','{"name": "DIGITAL SIGNAGE MEDIA CONTENT"}'),
('64','{"name": "MERCEDES-BENZ VIDEO LIBRARY"}'),
('65','{"name": "IBIS BASIC"}'),
('66','{"name": "IBIS CLASSIC"}'),
('67','{"name": "VISTA"}'),
('68','{"name": "UCARS"}'),
('69','{"name": "OASIS"}'),
('70','{"name": "VID CHECKER"}'),
('71','{"name": "KUFRI"}'),
('72','{"name": "MVIS"}'),
('73','{"name": "IMPACT"}'),
('74','{"name": "GO"}'),
('75','{"name": "SSP"}'),
('76','{"name": "PARAGON"}'),
('77','{"name": "JDA"}'),
('78','{"name": "IMPACT-BI"}'),
('79','{"name": "VIDEOS (SELF PRODUCED)"}'),
('80','{"name": "MICRODEMOGRAFIC DATA"}'),
('81','{"name": "OTB"}'),
('82','{"name": "GO PPM-ML"}'),
('83','{"name": "OPRA"}'),
('84','{"name": "VCS"}'),
('85','{"name": "CCS"}'),
('86','{"name": "GENESIS"}'),
('87','{"name": "SAP"}'),
('88','{"name": "CBFC"}'),
('89','{"name": "COFICO"}'),
('90','{"name": "OTHER FC-SYSTEMS"}'),
('91','{"name": "DATA CULTURE SPACE"}'),
('92','{"name": "IFIS"}'),
('93','{"name": "ALATION"}'),
('94','{"name": "MYPROJECTS"}'),
('95','{"name": "IT-SHOP"}'),
('96','{"name": "WIPPS"}'),
('97','{"name": "WEATHER DATA (3RD PARTY)"}'),
('98','{"name": "ADVANTAGES"}'),
('99','{"name": "RETAIL PORTAL"}'),
('100','{"name": "PRESALESNEWS"}'),
('101','{"name": "MERCEDES-BENZ WEBSITE"}'),
('102','{"name": "MANAGEMENT INFORMATION FACTORY"}'),
('103','{"name": "USER DATA"}'),
('104','{"name": "CONNECT"}'),
('105','{"name": "PROMAS"}'),
('106','{"name": "RD BI"}'),
('107','{"name": "TBE"}'),
('108','{"name": "CIP"}'),
('109','{"name": "ISP"}'),
('110','{"name": "VPPL"}'),
('111','{"name": "DISY"}'),
('112','{"name": "MRS"}'),
('113','{"name": "PPLF"}'),
('114','{"name": "Global Campaign"}'),
('115','{"name": "eXtollo"}'),
('116','{"name": "TELElog"}'),
('117','{"name": "BLK"}'),
('118','{"name": "DCP"}'),
('119','{"name": "Mercedes Me Connect"}'),
('120','{"name": "Car Configurator"}'),
('121','{"name": "BBD"}'),
('122','{"name": "enterprise data warehouse"}'),
('123','{"name": "Mercedes Me App Support Module"}'),
('124','{"name": "OneAPI"}'),
('125','{"name": "dealer locator"}'),
('126','{"name": "mercedes me ID"}'),
('127','{"name": "Afab"}'),
('128','{"name": "FIT"}'),
('129','{"name": "OneCRM"}'),
('130','{"name": "OTR"}'),
('131','{"name": "P.EN"}'),
('132','{"name": "PPS"}'),
('133','{"name": "Pulse"}'),
('134','{"name": "yucon"}'),
('135','{"name": "VBS"}'),
('136','{"name": "SMMT"}'),
('137','{"name": "CCD-EMS"}'),
('138','{"name": "MFP Target"}'),
('139','{"name": "CO2"}'),
('140','{"name": "SKD GEOLOCATION BASED DATA (VIA SMARTPHONE)"}'),
('141','{"name": "INITIAL Q&A (PREFERENCE) DATA"}'),
('142','{"name": "CONTENT AND USER-DATA"}'),
('143','{"name": "EXISTING DOCUMENTATION"}'),
('144','{"name": "PUBLIC SOCIAL MEDIA DATA"}'),
('145','{"name": "PICTURES (SELF PRODUCED)"}'),
('146','{"name": "NCBS"}'),
('147','{"name": "NVES"}'),
('148','{"name": "ASADI"}'),
('149','{"name": "WISO"}'),
('150','{"name": "EQ-Portal"}'),
('151','{"name": "CCD"}'),
('152','{"name": "CIS2"}'),
('153','{"name": "Powernet Data"}'),
('155','{"name": "COLT"}'),
('156','{"name": "Symphony"}'),
('157','{"name": "TELE"}'),
('158','{"name": "Mercedes me Data"}'),
('159','{"name": "BLK (limited)"}'),
('160','{"name": "ISTDaWo"}'),
('161','{"name": "Office Products"}'),
('162','{"name": "eX"}'),
('163','{"name": "Global Ordering"}'),
('164','{"name": "IOP"}'),
('165','{"name": "PMS"}'),
('166','{"name": "MRA"}'),
('167','{"name": "Ve"}'),
('168','{"name": "OAB"}'),
('169','{"name": "SimSearch"}'),
('170','{"name": "Test Drive Booking API"}'),
('171','{"name": "Unified Messaging"}'),
('172','{"name": "Open.Ai"}'),
('173','{"name": "Owner Manual"}'),
('174','{"name": "here2help"}'),
('175','{"name": "owners manual"}'),
('176','{"name": "oneweb"}'),
('177','{"name": "MVA"}'),
('178','{"name": "price lists"}'),
('179','{"name": "ODX DIAGNOSTIC DATA"}'),
('180','{"name": "AUTOSAR DIAGNOSTIC EXTRACT"}'),
('181','{"name": "VX"}'),
('182','{"name": "CONAIR"}'),
('183','{"name": "CORPORATE DATA CATALOG (ALATION)"}'),
('184','{"name": "MBD"}'),
('185','{"name": "ATHLON"}'),
('187','{"name": "GENESIS"}'),
('188','{"name": "REAL LIFE STUDY 213"}'),
('189','{"name": "BCAP"}'),
('190','{"name": "ASL"}'),
('191','{"name": "WLTP SERVICE"}'),
('192','{"name": "MAPIS"}'),
('193','{"name": "TOM"}'),
('194','{"name": "EQS"}'),
('195','{"name": "CO2MO"}'),
('196','{"name": "CO2FI"}'),
('197','{"name": "MDV"}'),
('198','{"name": "VDM"}'),
('199','{"name": "GRAPE"}'),
('200','{"name": "EPDM"}'),
('201','{"name": "SMARAGD"}'),
('202','{"name": "GABI"}'),
('203','{"name": "OKOBILANZEN"}'),
('204','{"name": "PBK"}'),
('205','{"name": "VERSO"}'),
('206','{"name": "COMAN"}'),
('207','{"name": "ECS4DQ"}'),
('208','{"name": "WEIGHTSERVICE"}'),
('209','{"name": "WLTP INSIGHTS"}'),
('210','{"name": "DOORS"}'),
('211','{"name": "KONZEPTHEFT"}'),
('212','{"name": "LASTENHEFT"}'),
('213','{"name": "vehicle deeplink service"}'),
('214','{"name": "Training Documents; Advantages Online; Hear to Help CaC .... etc."}'),
('215','{"name": "WARRANTY"}'),
('216','{"name": "Warranty & Goodwill Data"}'),
('217','{"name": "iParts"}'),
('218','{"name": "ZEUS"}'),
('219','{"name": "EE-CarLA"}'),
('220','{"name": "DukE, SQMS, CAT, ZEUS, QEC, MRS, Blackbelt,"}'),
('221','{"name": "aicq"}'),
('222','{"name": "ACM"}'),
('223','{"name": "IWQ"}'),
('224','{"name": "PIA"}'),
('225','{"name": "QEC"}'),
('226','{"name": "RTM"}'),
('227','{"name": "Battery Testing"}'),
('228','{"name": "BMS-Testing"}'),
('229','{"name": "Module Testing"}'),
('230','{"name": "Cell Testing"}'),
('231','{"name": "Battery Management System Testing"}'),
('232','{"name": "Salesforce"}'),
('233','{"name": "Development Cars Hyb42"}'),
('234','{"name": "Finas"}'),
('235','{"name": "generall Measurement Data"}'),
('236','{"name": "SRM"}'),
('237','{"name": "SMB"}'),
('238','{"name": "Assisten System Data"}'),
('239','{"name": "DIC"}'),
('240','{"name": "GTLS"}'),
('241','{"name": "OTR+"}'),
('242','{"name": "SPM"}'),
('243','{"name": "LPO"}'),
('244','{"name": "TACO"}'),
('245','{"name": "MIF"}'),
('246','{"name": "PPL-F"}'),
('247','{"name": "SA PRICING LIST"}'),
('248','{"name": "PRICING ENGINE"}'),
('249','{"name": "POSEIDON"}'),
('250','{"name": "MEDIA DATA"}'),
('251','{"name": "Dealer Master Data"}'),
('252','{"name": "Telediagnosis"}'),
('253','{"name": "cplace"}'),
('254','{"name": "Encoma"}'),
('255','{"name": "CTIME"}'),
('256','{"name": "MIC"}'),
('257','{"name": "Pre-integration Test Vehicles"}'),
('258','{"name": "eDrive Logger"}'),
('259','{"name": "Development Cars Gen5 ADAS"}'),
('260','{"name": "Testing Cars Gen5 ADAS"}'),
('261','{"name": "Validation Cars Gen5 ADAS"}'),
('262','{"name": "Simulation Results Gen5 ADAS"}'),
('263','{"name": "Endurance Testing Cars"}'),
('264','{"name": "Measurement data of endurance testing cars"}'),
('265','{"name": "WARP"}'),
('266','{"name": "CRETA"}'),
('267','{"name": "MDW"}'),
('268','{"name": "MIC VVR"}'),
('269','{"name": "PM-ASL"}'),
('270','{"name": "OASIS (CESAR Data)"}'),
('271','{"name": "EMS Leads"}'),
('272','{"name": "Microservices"}');

insert into datastrategydomain_nsql(id,data)
values('1','{"name": "Data driven Process Optimization & Self-Service"}'),
      ('2','{"name": "Data-driven Product Optimization"}'),
	  ('3','{"name": "Data-as-a-Service Business"}'),
	  ('4','{"name": "Data driven Offers & Recommendations"}'),
	  ('5','{"name": "Data-driven Marketing & Sales"}'),
	  ('6','{"name": "Digital Service Business"}'),
	  ('7','{"name": "Forecasting, Planning & Reporting"}');
	 
insert into datavolume_nsql(id,data)
values('1','{"name": "<100 MB"}'),
      ('2','{"name": "100 MB - 1GB"}'),
	  ('3','{"name": "1 GB - 100 GB"}'),
	  ('4','{"name": ">100 GB"}');
	  
insert into division_nsql (id, data)
values('1','{"name": "COB & MBC", "subdivisions": [{"id": "1", "name": "IT"}, {"id": "2", "name": "MBC"}, {"id": "3", "name": "COB"}, {"id": "4", "name": "COM"}, {"id": "5", "name": "CASE"}, {"id": "6", "name": "EA"}, {"id": "7", "name": "M-AMG"}]}'),
	  ('2','{"name": "FC", "subdivisions": [{"id": "1", "name": "FT"}, {"id": "2", "name": "FI"}, {"id": "3", "name": "FC"}, {"id": "4", "name": "FA"}, {"id": "5", "name": "FD"}, {"id": "6", "name": "FR"}, {"id": "7", "name": "FG"}, {"id": "8", "name": "FS"}, {"id": "9", "name": "FM"}, {"id": "10", "name": "FF"}]}'),
	  ('3','{"name": "HR", "subdivisions": [{"id": "1", "name": "IPS"}, {"id": "2", "name": "HR"}, {"id": "3", "name": "CBS"}, {"id": "4", "name": "CS"}, {"id": "5", "name": "KB"}]}'),
	  ('4','{"name": "IL", "subdivisions": [{"id": "1", "name": "IL"}, {"id": "2", "name": "CA"}]}'),
	  ('5','{"name": "T", "subdivisions": [{"id": "1", "name": "TE"}, {"id": "2", "name": "T"}, {"id": "3", "name": "TP"}, {"id": "4", "name": "TN"}, {"id": "5", "name": "TG"}, {"id": "6", "name": "TA"}]}'),
	  ('6','{"name": "DMO", "subdivisions": []}'),
	  ('7','{"name": "GRC", "subdivisions": []}'),
	  ('8','{"name": "MS", "subdivisions": [{"id": "1", "name": "MS/D"}, {"id": "2", "name": "GSP/O"}, {"id": "3", "name": "MS/S"}, {"id": "4", "name": "MS/C"}, {"id": "5", "name": "MS/E"}, {"id": "6", "name": "MS/N"}, {"id": "7", "name": "MS/O"}, {"id": "8", "name": "BMBS"}, {"id": "9", "name": "GSP/TP"}, {"id": "10", "name": "GSP/RV"}, {"id": "11", "name": "GSP/BW"}]}'),
	  ('9','{"name": "RD & MBC-COO", "subdivisions": [{"id": "1", "name": "MO"}, {"id": "2", "name": "RDCASE-CTO"}, {"id": "3", "name": "RD"}, {"id": "4", "name": "IT"}]}');
	  

insert into language_nsql (id, data) 
values('1','{"name": "Scal"}'),
('2','{"name": "German"}'),
('3','{"name": "Low Code"}'),
('4','{"name": "ABAP"}'),
('5','{"name": "JavaScript"}'),
('6','{"name": "Germ"}'),
('7','{"name": "English"}'),
('8','{"name": "ph"}'),
('9','{"name": "R"}'),
('10','{"name": "PYTHON"}'),
('11','{"name": "C++"}'),
('12','{"name": "PYSPARK"}'),
('13','{"name": "ALTERYX"}'),
('14','{"name": "PHYTHON"}'),
('15','{"name": "SQL"}'),
('16','{"name": "SCALA"}'),
('17','{"name": "JAVE"}'),
('18','{"name": "JAVA"}'),
('19','{"name": "JYTHON"}'),
('20','{"name": "JAVA"}'),
('21','{"name": "POWERSHELL"}'),
('22','{"name": "C#"}'),
('23','{"name": "py"}'),
('24','{"name": "HTML"}'),
('25','{"name": "CSS"}'),
('26','{"name": "Pys"}'),
('27','{"name": "SC"}'),
('28','{"name": "SPARKR"}'),
('29','{"name": "KAFKA"}'),
('30','{"name": "Athena"}'),
('31','{"name": "reactjs"}'),
('32','{"name": "Chinese"}'),
('33','{"name": "Korean"}'),
('34','{"name": "RDF"}'),
('35','{"name": "JSON"}');


insert into location_nsql (id, data) 
values('107','{"name": "Myanmar", "is_row": true}'),
('108','{"name": "Nepal", "is_row": true}'),
('109','{"name": "New Caledonia", "is_row": true}'),
('110','{"name": "New Zealand", "is_row": true}'),
('111','{"name": "Nicaragua", "is_row": true}'),
('112','{"name": "Nigeria", "is_row": true}'),
('113','{"name": "Oman", "is_row": true}'),
('114','{"name": "Pakistan", "is_row": true}'),
('115','{"name": "Palestine", "is_row": true}'),
('116','{"name": "Panama", "is_row": true}'),
('117','{"name": "Papua new Guinea", "is_row": true}'),
('118','{"name": "Paraguay", "is_row": true}'),
('119','{"name": "Peru", "is_row": true}'),
('120','{"name": "Philippines", "is_row": true}'),
('121','{"name": "Qatar", "is_row": true}'),
('122','{"name": "Reunion", "is_row": true}'),
('123','{"name": "Romania", "is_row": true}'),
('124','{"name": "Russia", "is_row": true}'),
('125','{"name": "Saint Lucia", "is_row": true}'),
('126','{"name": "Samoa", "is_row": true}'),
('127','{"name": "Saudi Arabia", "is_row": true}'),
('128','{"name": "Serbia-Montenegro", "is_row": true}'),
('129','{"name": "Singapore", "is_row": false}'),
('130','{"name": "Slovakia", "is_row": true}'),
('131','{"name": "Slovenia", "is_row": true}'),
('132','{"name": "South Africa", "is_row": false}'),
('133','{"name": "Sri Lanka", "is_row": true}'),
('134','{"name": "Sudan", "is_row": true}'),
('135','{"name": "Suriname", "is_row": true}'),
('136','{"name": "Syria", "is_row": true}'),
('137','{"name": "Tajikistan", "is_row": true}'),
('138','{"name": "Tanzania", "is_row": true}'),
('139','{"name": "Thailand", "is_row": true}'),
('140','{"name": "Tonga", "is_row": true}'),
('141','{"name": "Trinidad and Tobago", "is_row": true}'),
('142','{"name": "Tunisia", "is_row": true}'),
('143','{"name": "Turkey", "is_row": true}'),
('144','{"name": "Turkmenistan", "is_row": true}'),
('145','{"name": "Uganda", "is_row": true}'),
('146','{"name": "Ukraine", "is_row": true}'),
('147','{"name": "United Arab Emirates", "is_row": true}'),
('148','{"name": "Uruguay", "is_row": true}'),
('149','{"name": "Uzbekistan", "is_row": true}'),
('150','{"name": "Venezuela", "is_row": true}'),
('151','{"name": "Vietnam", "is_row": true}'),
('152','{"name": "West Bank", "is_row": true}'),
('153','{"name": "Yemen", "is_row": true}'),
('154','{"name": "Zambia", "is_row": true}'),
('155','{"name": "Zimbabwe", "is_row": true}'),
('156','{"name": "Burundi", "is_row": true}'),
('157','{"name": "Egypt", "is_row": true}'),
('158','{"name": "Guateloupe", "is_row": true}'),
('159','{"name": "Gran Canaria", "is_row": true}'),
('160','{"name": "Teneriffa", "is_row": true}'),
('1','{"name": "Germany", "is_row": false}'),
('2','{"name": "Canada", "is_row": false}'),
('3','{"name": "Mexico", "is_row": false}'),
('4','{"name": "USA", "is_row": false}'),
('5','{"name": "China", "is_row": false}'),
('6','{"name": "Hong Kong", "is_row": false}'),
('7','{"name": "Taiwan", "is_row": false}'),
('8','{"name": "Austria", "is_row": false}'),
('9','{"name": "Belgium", "is_row": false}'),
('10','{"name": "Czech Republic", "is_row": false}'),
('11','{"name": "Denmark", "is_row": false}'),
('12','{"name": "Finland", "is_row": false}'),
('13','{"name": "France", "is_row": false}'),
('14','{"name": "Greece", "is_row": false}'),
('15','{"name": "Ireland", "is_row": false}'),
('16','{"name": "Italy", "is_row": false}'),
('17','{"name": "Luxembourg", "is_row": false}'),
('18','{"name": "Netherlands", "is_row": false}'),
('19','{"name": "Norway", "is_row": false}'),
('20','{"name": "Poland", "is_row": false}'),
('21','{"name": "Portugal", "is_row": false}'),
('22','{"name": "Spain", "is_row": false}'),
('23','{"name": "Sweden", "is_row": false}'),
('24','{"name": "Switzerland", "is_row": false}'),
('25','{"name": "United Kingdom", "is_row": false}'),
('26','{"name": "Argentina", "is_row": true}'),
('27','{"name": "Albania", "is_row": true}'),
('28','{"name": "Algeria", "is_row": true}'),
('29','{"name": "Angola", "is_row": true}'),
('30','{"name": "Armenia", "is_row": true}'),
('31','{"name": "Aruba", "is_row": true}'),
('32','{"name": "Australia", "is_row": false}'),
('33','{"name": "Azerbaijan", "is_row": true}'),
('34','{"name": "Bahamas", "is_row": true}'),
('35','{"name": "Bahrain", "is_row": true}'),
('36','{"name": "Barbados", "is_row": true}'),
('37','{"name": "Belarus", "is_row": true}'),
('38','{"name": "Bermuda", "is_row": true}'),
('39','{"name": "Bolivia", "is_row": true}'),
('40','{"name": "Bosnia and Herzegovina", "is_row": true}'),
('41','{"name": "Brazil", "is_row": true}'),
('42','{"name": "Brunei", "is_row": true}'),
('43','{"name": "Burkina Faso", "is_row": true}'),
('44','{"name": "Cambodia", "is_row": true}'),
('45','{"name": "Cameroon", "is_row": true}'),
('46','{"name": "Cayman Islands", "is_row": true}'),
('47','{"name": "Chile", "is_row": true}'),
('48','{"name": "Colombia", "is_row": true}'),
('49','{"name": "Congo", "is_row": true}'),
('50','{"name": "Costa Rica", "is_row": true}'),
('51','{"name": "Croatia", "is_row": true}'),
('52','{"name": "Cuba VP", "is_row": true}'),
('53','{"name": "Curacao", "is_row": true}'),
('54','{"name": "Cyprus", "is_row": true}'),
('55','{"name": "Dominican Republic", "is_row": true}'),
('56','{"name": "Ecuador", "is_row": true}'),
('57','{"name": "Egypt", "is_row": true}'),
('58','{"name": "El Salvador", "is_row": true}'),
('59','{"name": "Eritrea", "is_row": true}'),
('60','{"name": "Estonia", "is_row": true}'),
('61','{"name": "Ethiopia", "is_row": true}'),
('62','{"name": "Fiji", "is_row": true}'),
('63','{"name": "French Guinea", "is_row": true}'),
('64','{"name": "French Polynesia", "is_row": true}'),
('65','{"name": "Gabon", "is_row": true}'),
('66','{"name": "Gaza", "is_row": true}'),
('67','{"name": "Georgia", "is_row": true}'),
('68','{"name": "Ghana", "is_row": true}'),
('69','{"name": "Gibraltar", "is_row": true}'),
('70','{"name": "Guadeloupe", "is_row": true}'),
('71','{"name": "Guatemala", "is_row": true}'),
('72','{"name": "Guyana", "is_row": true}'),
('73','{"name": "Haiti", "is_row": true}'),
('74','{"name": "Honduras", "is_row": true}'),
('75','{"name": "Hungary", "is_row": true}'),
('76','{"name": "Iceland", "is_row": true}'),
('77','{"name": "India", "is_row": true}'),
('78','{"name": "Indonesia", "is_row": true}'),
('79','{"name": "Iran", "is_row": true}'),
('80','{"name": "Iraq", "is_row": true}'),
('81','{"name": "Israel", "is_row": true}'),
('82','{"name": "Ivory Coast", "is_row": true}'),
('83','{"name": "Jamaica", "is_row": true}'),
('84','{"name": "Japan", "is_row": false}'),
('85','{"name": "Jordan", "is_row": true}'),
('86','{"name": "Kazakhstan", "is_row": true}'),
('87','{"name": "Kenya", "is_row": true}'),
('88','{"name": "Korea", "is_row": false}'),
('89','{"name": "Kuwait", "is_row": true}'),
('90','{"name": "Laos", "is_row": true}'),
('91','{"name": "Latvia", "is_row": true}'),
('92','{"name": "Lebanon", "is_row": true}'),
('93','{"name": "Libya", "is_row": true}'),
('94','{"name": "Lithuania", "is_row": true}'),
('95','{"name": "Macau", "is_row": true}'),
('96','{"name": "Macedonia", "is_row": true}'),
('97','{"name": "Madagascar", "is_row": true}'),
('98','{"name": "Malawi", "is_row": true}'),
('99','{"name": "Malaysia", "is_row": true}'),
('100','{"name": "Malta", "is_row": true}'),
('101','{"name": "Martinique", "is_row": true}'),
('102','{"name": "Mauritius", "is_row": true}'),
('103','{"name": "Moldova", "is_row": true}'),
('104','{"name": "Mongolia", "is_row": true}'),
('105','{"name": "Morocco", "is_row": true}'),
('106','{"name": "Mozambique", "is_row": true}'),
('161','{"name": "Bulgaria", "is_row": true}'),
('162','{"name": "Bangladesh", "is_row": true}');


insert into maturitylevel_nsql (id, data) 
values('1','{"name": "Idea"}'),
('2','{"name": "Evaluated / Concept"}'),
('3','{"name": "Decided / Committed"}'),
('4','{"name": "Implemented"}'),
('6','{"name": "Rejected"}'),
('5','{"name": "Savings Realized / Incoming"}');


insert into phase_nsql (id, data) 
values('1','{"name": "KICK-OFF"}'),
('2','{"name": "IDEE / STUDIE"}'),
('3','{"name": "CONCEPT DEVELOPMENT"}'),
('4','{"name": "PILOT"}'),
('5','{"name": "SERIE"}'),
('6','{"name": "ROLLOUT"}');


insert into platform_nsql (id, data) 
values('1','{"name": "MS Azure"}'),
('2','{"name": "Conversational Intelligence Platform"}'),
('3','{"name": "CIP"}'),
('4','{"name": "GO-DWH"}'),
('5','{"name": "Optika"}'),
('6','{"name": "VEGA"}'),
('7','{"name": "AQUA"}'),
('8','{"name": "MIC"}'),
('9','{"name": "YUCON"}'),
('10','{"name": "YUCAS"}'),
('11','{"name": "DHC"}'),
('12','{"name": "AWS"}'),
('13','{"name": "IIH"}'),
('14','{"name": "ABO EXTOLLO PLATFORM"}'),
('15','{"name": "CAAS"}'),
('16','{"name": "FUTURE: EXTOLLO"}'),
('17','{"name": "EXTOLLO"}'),
('18','{"name": "DAIMLER HYBRID CLOUD (DHC)"}'),
('19','{"name": "SAP HANA"}'),
('20','{"name": "DATAIKU"}'),
('21','{"name": "EUREP"}'),
('22','{"name": "SDCE"}'),
('23','{"name": "RCPS"}'),
('24','{"name": "SPSS MODELER"}'),
('25','{"name": "OPEN SHIFT"}'),
('26','{"name": "SQL SERVER"}'),
('27','{"name": "PARAGON"}'),
('28','{"name": "JDA"}'),
('29','{"name": "STOCKPRO"}'),
('30','{"name": "ZIPPY (BLUEPRISM)"}'),
('31','{"name": "SAP"}'),
('32','{"name": "PEOPLESOFT"}'),
('33','{"name": "OUTLOOK"}'),
('34','{"name": "CISM "}'),
('35','{"name": "MAINFRAME "}'),
('36','{"name": "ONEAPI"}'),
('37','{"name": "CORPORATE DATA CATALOG"}'),
('38','{"name": "LOGBUS"}'),
('39','{"name": "BDS (BRAND DESIGN SYSTEM)"}'),
('40','{"name": "MBFS IBM WATSON"}'),
('41','{"name": "IPARTS"}'),
('42','{"name": "XENTRY PORTAL"}'),
('43','{"name": "CONAIR"}'),
('44','{"name": "MIF"}'),
('45','{"name": "DNA Internal Notebook"}'),
('46','{"name": "BW4"}'),
('47','{"name": "Databricks"}'),
('48','{"name": "CAS"}'),
('49','{"name": "Frankfurt"}'),
('50','{"name": "DnA Dataiku Project"}'),
('51','{"name": "smaragd"}'),
('52','{"name": "Power Platform"}'),
('53','{"name": "Daimler"}'),
('54','{"name": "Daimler Hybrid Cloud"}'),
('55','{"name": "TSS"}'),
('56','{"name": "China Data Lake"}'),
('57','{"name": "#BatteryData On-premise and exTollo"}'),
('58','{"name": "#BatteryData On-Premise and Cloud"}'),
('59','{"name": "IPLM"}'),
('60','{"name": "China BigData Platform"}'),
('61','{"name": "cplace"}'),
('62','{"name": "Data Management Platform"}'),
('63','{"name": "IT4AD.ADAS"}'),
('64','{"name": "WARP Edge Nodes"}');



insert into projectstatus_nsql (id, data) 
values('1','{"name": "ON TRACK"}'),
('2','{"name": "STRUGGLING"}'),
('3','{"name": "CRITICAL"}'),
('4','{"name": "INACTIVE"}'),
('5','{"name": "CLOSED"}');

insert into relatedproduct_nsql (id, data) 
values('1','{"name": "Analytics Based Offers (ABO)"}'),
('2','{"name": "CarDataCockpit"}'),
('3','{"name": "Infrastructure service Dashboard"}'),
('4','{"name": "MB B2B Connect"}'),
('5','{"name": "Mme App Family"}'),
('6','{"name": "NB(x)"}'),
('7','{"name": "Offers Connected Vehicles"}'),
('8','{"name": "Radical SA tool"}'),
('9','{"name": "GO-DWH"}'),
('10','{"name": "OneDNA Dashboards"}'),
('11','{"name": "Virtual Sales Assistant"}'),
('12','{"name": "iBDC Voicebot"}'),
('13','{"name": "Converstaional Intelligence Platform (CIP)/ Build Your Own Bot (BYOB)"}'),
('14','{"name": "VEGA"}'),
('15','{"name": "Profitable Allocation"}'),
('16','{"name": "CO2 Registration Tracking"}'),
('17','{"name": "Stock Management"}'),
('18','{"name": "XENTRY"}'),
('19','{"name": "BigData@GSP"}'),
('20','{"name": "AaaS"}'),
('21','{"name": "forecast"}'),
('22','{"name": "AQUA"}'),
('23','{"name": "eXtollo"}'),
('24','{"name": "WLTP-Service"}'),
('25','{"name": "Knowledge Search"}'),
('26','{"name": "ISTDaWo"}'),
('27','{"name": "Dispatch Automation"}'),
('28','{"name": "FAQ Service Assistant Comet"}'),
('29','{"name": "MB Bank Bot"}'),
('30','{"name": "HR Service Assistant"}'),
('31','{"name": "Direct Sales Bot"}'),
('32','{"name": "Intelligent Filter Mme Inbox"}'),
('33','{"name": "#BatteryData"}'),
('34','{"name": "OTR+"}'),
('35','{"name": "Data Quality Framework"}'),
('36','{"name": "SPM"}'),
('37','{"name": "Mercedes-Benz Data Dashboard"}'),
('38','{"name": "eMission Platform"}'),
('39','{"name": "Data Management Platform"}'),
('40','{"name": "OneWeb"}'),
('41','{"name": "Salesforce"}'),
('42','{"name": "WARP - Worldwide Analysis and Reporting Platform"}'),
('43','{"name": "DHC"}'),
('44','{"name": "VCARecosystem"}');


insert into result_nsql (id, data) 
values('1','{"name": "DASHBOARD"}'),
('2','{"name": "SHAREPOINT"}'),
('3','{"name": "SERVICE"}');

insert into skill_nsql (id, data) 
values('1','{"name": "Data Product Owner"}'),
('2','{"name": "Data Engineer"}'),
('3','{"name": "Data Analyst / Advanced Analyst"}'),
('4','{"name": "Machine Learning Engineer"}'),
('5','{"name": "Data Automation Engineer"}'),
('6','{"name": "No-code (BI) Developer / BI-DevOps Engineer"}'),
('7','{"name": "Backend Developer"}'),
('8','{"name": "DevOps"}'),
('9','{"name": "Data Protection Engineer"}'),
('10','{"name": "Knowledge Engineer"}'),
('11','{"name": "Portfolio Manager"}'),
('12','{"name": "Leader"}'),
('13','{"name": "Scrum Master"}'),
('14','{"name": "Process Automation Engineer"}'),
('15','{"name": "Conversational AI Engineer"}'),
('16','{"name": "Conversational AI Platform Product Owner"}'),
('17','{"name": "Solution Architect"}'),
('18','{"name": "Frontend Developer"}'),
('19','{"name": "Data Scientist"}'),
('20','{"name": "AUTOSAR Classic expert"}'),
('21','{"name": "AUTOSAR adaptive expert"}'),
('22','{"name": "MB.OS SW Development Process expert"}'),
('23','{"name": "RD/P subject matter expert"}'),
('24','{"name": "RD/E subject matter expert"}'),
('25','{"name": "Data Architect"}'),
('26','{"name": "Datasource Product Owner"}'),
('27','{"name": "RD/M subject matter expert"}'),
('28','{"name": "RD/A subject matter expert"}'),
('29','{"name": "RD/TQM process expert"}'),
('30','{"name": "product owner"}'),
('31','{"name": "data analyst"}'),
('32','{"name": "Expert in smart algorithm development"}'),
('33','{"name": "Familiar with data sourcing and interface connection"}'),
('34','{"name": "Familiar with data mapping"}'),
('35','{"name": "Familiar with cloud solutions (Azzure, AWS DevOps)"}'),
('36','{"name": "Power BI Developer"}'),
('37','{"name": "Data Strategist"}'),
('38','{"name": "Process Engineer"}'),
('39','{"name": "DevPartner"}'),
('40','{"name": "Data Processing Product Owner"}'),
('41','{"name": "Data Reliability Engineer"}'),
('42','{"name": "Expert in BOT Solutions"}'),
('43','{"name": "Product Owner Data-Discovery Plattform"}'),
('44','{"name": "Product Owner Data-Discovery Platform"}'),
('45','{"name": "Technical Marketing Expert"}');


insert into strategicrelevance_nsql (id, data) 
values('1','{"name": "Very Low"}'),
('2','{"name": "Low"}'),
('3','{"name": "Relatively Low"}'),
('4','{"name": "Relatively High"}'),
('5','{"name": "High"}'),
('6','{"name": "Very High"}');

insert into topic_nsql (id, data) 
values('1','{"name": "BIG DATA"}'),
('2','{"name": "360 CONNECTIVITY"}'),
('3','{"name": "WANDLUNGSFAHIGE FABRIK"}'),
('4','{"name": "DIGITALE PROZESSKETTE"}'),
('5','{"name": "SMART SUPPLY CHAIN"}'),
('6','{"name": "CUSTOMER VALUE"}');

insert into userrole_nsql (id, data) 
values('1','{"name": "User"}'),
('2','{"name": "Admin"}'),
('3','{"name": "ReportAdmin"}');

insert into visualization_nsql (id, data)
values('1','{"name": "SHINY APP"}'),
('2','{"name": "TM1"}'),
('3','{"name": "TABLEAU"}'),
('4','{"name": "R-SHINY"}'),
('5','{"name": "USERLIKE"}'),
('6','{"name": "POWER BI"}'),
('7','{"name": "JUPYTER LAB"}'),
('8','{"name": "UI5"}'),
('9','{"name": "PLOTLY"}'),
('10','{"name": "JAVA"}'),
('11','{"name": "JAVA UI"}'),
('12','{"name": "ADOBE ANALYTICS"}'),
('13','{"name": "JUPYTER NOTEBOOKS"}'),
('14','{"name": "IWEB"}'),
('15','{"name": "DATAIKU"}'),
('16','{"name": "BOKEH"}'),
('17','{"name": "MATPLOTLIP"}'),
('18','{"name": "SEABORN"}'),
('19','{"name": "WEBAPPS"}'),
('20','{"name": "Excel"}'),
('21','{"name": "Kibana"}'),
('22','{"name": "SAP Fiori"}'),
('23','{"name": "SAP Analytics Cloud"}'),
('24','{"name": "Analysis for Office"}'),
('25','{"name": "Power"}'),
('26','{"name": "none"}'),
('27','{"name": "Angular"}'),
('28','{"name": "Vue.js"}'),
('29','{"name": "Pow"}'),
('30','{"name": "PowerBI"}'),
('31','{"name": "Seamless Web"}'),
('32','{"name": "Uneeq"}'),
('33','{"name": "GUI"}'),
('34','{"name": "HTML"}'),
('35','{"name": "datashader"}'),
('36','{"name": "Knowledge-Tree"}'),
('37','{"name": "p"}'); 