{
 "title": "I³ Access 4",
 "tags": [
  "i3",
  "i3-access"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(caddy_http_requests_total,kubernetes_namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "i3-tex-caddy Health",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=~\"(Running|Succeeded)\",namespace=~\"$namespace\"} * on (pod) group_left(label_app) kube_pod_labels{label_app_kubernetes_io_name=~\"i3-tex-caddy\",namespace=~\"$namespace\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase!=\"Running\",phase!=\"Succeeded\",namespace=~\"$namespace\"} * on (pod) group_left(label_app) kube_pod_labels{label_app_kubernetes_io_name=~\"i3-tex-caddy\",namespace=~\"$namespace\"})",
     "legendFormat": "Unavailable"
    }
   ]
  },
  {
   "title": "i3-tex-service Health",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=~\"(Running|Succeeded)\",namespace=~\"$namespace\"} * on (pod) group_left(label_app) kube_pod_labels{label_app_kubernetes_io_name=~\"i3-tex-service\",namespace=~\"$namespace\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase!=\"Running\",phase!=\"Succeeded\",namespace=~\"$namespace\"} * on (pod) group_left(label_app) kube_pod_labels{label_app_kubernetes_io_name=~\"i3-tex-service\",namespace=~\"$namespace\"})",
     "legendFormat": "Unavailable"
    }
   ]
  },
  {
   "title": "Image Versions",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "label_replace(label_replace(sum(kube_pod_container_info{namespace=~\"$namespace\"} * on (pod) group_left(label_app) kube_pod_labels{label_app_kubernetes_io_name=~\"i3-tex-caddy|i3-tex-service\",namespace=~\"$namespace\"}) by (image), \"tag\", \"$2\", \"image\", \"registry-emea.app.corpintra.net/(.*):(.*)\"), \"image\", \"$1\", \"image\", \"registry-emea.app.corpintra.net/(.*):(.*)\")"
    }
   ]
  },
  {
   "title": "i3-tex-caddy Restarts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=~\"$namespace\"} * on (pod) group_left(label_app) kube_pod_labels{label_app_kubernetes_io_name=~\"i3-tex-caddy\",namespace=~\"$namespace\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "i3-tex-service Restarts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=~\"$namespace\"} * on (pod) group_left(label_app) kube_pod_labels{label_app_kubernetes_io_name=~\"i3-tex-service\",namespace=~\"$namespace\"})",
     "legendFormat": " "
    }
   ]
  },
  { "title": "Live", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Success/Error Requests Ratio",
   "type": "piechart",
   "description": "Current Success/Error Requests Ratio in i3-tex-caddy's tex handler",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(caddy_http_requests_total{app_kubernetes_io_name=\"i3-tex-caddy\", handler=\"tex\", kubernetes_namespace=\"$namespace\"}[10m])) - sum(increase(caddy_http_request_errors_total{kubernetes_namespace=\"i3-access-develop\", handler=\"tex\", app_kubernetes_io_name=\"i3-tex-caddy\"}[10m])) != 0 or vector(1)",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(increase(caddy_http_request_errors_total{kubernetes_namespace=\"i3-access-develop\", handler=\"tex\", app_kubernetes_io_name=\"i3-tex-caddy\"}[10m])) != 0 or vector(0)",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Token Exchange Success/Error Ratio",
   "type": "piechart",
   "description": "Current Token Exchange Success/Error Rate with i3-tex-service",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(tex_service_requests_total{app_kubernetes_io_name=\"i3-tex-service\",kubernetes_namespace=~\"$namespace\",url=\"/token.oauth2\",code=\"200\"}[10m])) != 0 or vector(1)",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(increase(tex_service_requests_total{app_kubernetes_io_name=\"i3-tex-service\",kubernetes_namespace=~\"$namespace\",url=\"/token.oauth2\",code!=\"200\"}[$__range])) != 0 or vector(0)",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Success/Error JWT Signings Ratio",
   "type": "piechart",
   "description": "Success/Errors Ratio of JWT Signings by i3-tex-service",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(tex_service_jwt_signings{app_kubernetes_io_name=\"i3-tex-service\",kubernetes_namespace=~\"$namespace\"}[10m])) != 0 or vector(1)",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(increase(tex_service_jwt_errors{app_kubernetes_io_name=\"i3-tex-service\",kubernetes_namespace=~\"$namespace\"}[10m])) != 0 or vector(0)",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Requests/Sec",
   "type": "stat",
   "description": "Incoming requests per seconds, including user requests and metrics scraping",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(caddy_http_requests_total{kubernetes_namespace=~\"$namespace\",app_kubernetes_io_name=~\"i3-tex-caddy\"}[3m]))"
    }
   ]
  },
  {
   "title": "Token Exchanges/Sec",
   "type": "stat",
   "description": "The number of successful token exchanges per seconds",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(tex_service_requests_total{app_kubernetes_io_name=\"i3-tex-service\",kubernetes_namespace=~\"$namespace\",url=\"/token.oauth2\"}[10m])) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Estimated Number of Active Users",
   "type": "stat",
   "description": "Estimated Number of Currently Active Users.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(sum(increase(tex_service_parsed_valid_jwts{kubernetes_namespace=~\"$namespace\",id=~\".+\"}[10m])) by (id) > 0) "
    }
   ]
  },
  {
   "title": "Total Request Durations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Successful Requests duration",
     "type": "graph",
     "description": "Request duration including token exchange and backend",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(caddy_http_request_duration_seconds_bucket{kubernetes_namespace=~\"$namespace\",handler=\"reverse_proxy\",code=~\"(2|3).*\"}[3m])) by (le))",
       "legendFormat": "50th percentile duration"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(caddy_http_request_duration_seconds_bucket{kubernetes_namespace=~\"$namespace\",code=~\"(2|3).*\",handler=\"reverse_proxy\"}[3m])) by (le))",
       "legendFormat": "95th percentile duration"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(caddy_http_request_duration_seconds_bucket{kubernetes_namespace=~\"$namespace\",code=~\"(2|3).*\",handler=\"reverse_proxy\"}[3m])) by (le))",
       "legendFormat": "99th percentile duration"
      }
     ]
    },
    {
     "title": "Total Error Requests duration",
     "type": "graph",
     "description": "Request duration including token exchange and backend",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(caddy_http_request_duration_seconds_bucket{kubernetes_namespace=~\"$namespace\",handler=\"reverse_proxy\",code=~\"(400|5.*)\"}[3m])) by (le))",
       "legendFormat": "50th percentile duration"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(caddy_http_request_duration_seconds_bucket{kubernetes_namespace=~\"$namespace\",code=~\"(400|5.*)\",handler=\"reverse_proxy\"}[3m])) by (le))",
       "legendFormat": "95th percentile duration"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(caddy_http_request_duration_seconds_bucket{kubernetes_namespace=~\"$namespace\",code=~\"(400|5.*)\",handler=\"reverse_proxy\"}[3m])) by (le))",
       "legendFormat": "99th percentile duration"
      }
     ]
    }
   ]
  },
  {
   "title": "TEX-Caddy  ↔  TEX-Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Successful Token Exchange durations",
     "type": "graph",
     "description": "Request duration for successfully exchanging access token to JWT",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(tex_service_requests_seconds_bucket{kubernetes_namespace=~\"$namespace\",app_kubernetes_io_name=~\"i3-tex-service\", url=~\".*token.*\",code=~\"2.*\"}[3m])) by (le))",
       "legendFormat": "50th percentile duration 2xx"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(tex_service_requests_seconds_bucket{kubernetes_namespace=~\"$namespace\",app_kubernetes_io_name=~\"i3-tex-service\", url=~\".*token.*\",code=~\"2.*\"}[3m])) by (le))",
       "legendFormat": "95th percentile duration 2xx"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tex_service_requests_seconds_bucket{kubernetes_namespace=~\"$namespace\",app_kubernetes_io_name=~\"i3-tex-service\", url=~\".*token.*\",code=~\"2.*\"}[3m])) by (le))",
       "legendFormat": "99th percentile duration 2xx"
      }
     ]
    },
    {
     "title": "Failed Token Exchange durations",
     "type": "graph",
     "description": "Request duration for exchanging access token to JWT failed",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(tex_service_requests_seconds_bucket{kubernetes_namespace=~\"$namespace\",app_kubernetes_io_name=~\"i3-tex-service\", url=~\".*token.*\",code=~\"(400|5.*)\"}[3m])) by (le))",
       "legendFormat": "50th percentile duration 4xx/5xx"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(tex_service_requests_seconds_bucket{kubernetes_namespace=~\"$namespace\",app_kubernetes_io_name=~\"i3-tex-service\", url=~\".*token.*\",code=~\"(400|5.*)\"}[3m])) by (le))",
       "legendFormat": "95th percentile duration 4xx/5xx"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(tex_service_requests_seconds_bucket{kubernetes_namespace=~\"$namespace\",app_kubernetes_io_name=~\"i3-tex-service\", url=~\".*token.*\",code=~\"(400|5.*)\"}[3m])) by (le))",
       "legendFormat": "95th percentile duration 4xx/5xx"
      }
     ]
    },
    {
     "title": "Successful JWKS duration",
     "type": "graph",
     "description": "Successful requests duration for JWKS endpoint of tex-service",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(tex_service_requests_seconds_bucket{kubernetes_namespace=~\"$namespace\",app_kubernetes_io_name=~\"i3-tex-service\", url=~\".*JWKS.*\",code=~\"2.*\"}[3m])) by (le))",
       "legendFormat": "50th percentile duration 2xx"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(tex_service_requests_seconds_bucket{kubernetes_namespace=~\"$namespace\",app_kubernetes_io_name=~\"i3-tex-service\", url=~\".*JWKS.*\",code=~\"2.*\"}[3m])) by (le))",
       "legendFormat": "95th percentile duration 2xx"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tex_service_requests_seconds_bucket{kubernetes_namespace=~\"$namespace\",app_kubernetes_io_name=~\"i3-tex-service\", url=~\".*JWKS.*\",code=~\"2.*\"}[3m])) by (le))",
       "legendFormat": "99th percentile duration 2xx"
      }
     ]
    },
    {
     "title": "Error JWKS duration",
     "type": "graph",
     "description": "Error requests duration for JWKS endpoint of tex-service",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(tex_service_requests_seconds_bucket{kubernetes_namespace=~\"$namespace\",app_kubernetes_io_name=~\"i3-tex-service\", url=~\".*JWKS.*\",code=~\"(400|5.*)\"}[3m])) by (le))",
       "legendFormat": "50th percentile duration 4xx/5xx"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(tex_service_requests_seconds_bucket{kubernetes_namespace=~\"$namespace\",app_kubernetes_io_name=~\"i3-tex-service\", url=~\".*JWKS.*\",code=~\"(400|5.*)\"}[3m])) by (le))",
       "legendFormat": "95th percentile duration 4xx/5xx"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tex_service_requests_seconds_bucket{kubernetes_namespace=~\"$namespace\",app_kubernetes_io_name=~\"i3-tex-service\", url=~\".*JWKS.*\",code=~\"(400|5.*)\"}[3m])) by (le))",
       "legendFormat": "99th percentile duration 4xx/5xx"
      }
     ]
    }
   ]
  },
  {
   "title": "TEX-Caddy  ↔  Backends",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Successful Backend Requests Duration",
     "type": "graph",
     "description": "Request duration to backend services by traefik in i3-tex-caddy",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(traefik_service_request_duration_seconds_bucket{kubernetes_namespace=~\"$namespace\",code=~\"2.*\",app_kubernetes_io_name=\"i3-tex-caddy\"}[3m])) by (le))",
       "legendFormat": "50th percentile duration 2xx"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(traefik_service_request_duration_seconds_bucket{kubernetes_namespace=~\"$namespace\",code=~\"2.*\",app_kubernetes_io_name=\"i3-tex-caddy\"}[3m])) by (le))",
       "legendFormat": "95th percentile duration 2xx"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(traefik_service_request_duration_seconds_bucket{kubernetes_namespace=~\"$namespace\",code=~\"2.*\",app_kubernetes_io_name=\"i3-tex-caddy\"}[3m])) by (le))",
       "legendFormat": "99th percentile duration 2xx"
      }
     ]
    },
    {
     "title": "Failed Backend Requests Duration",
     "type": "graph",
     "description": "Failed requests duration to backend services by traefik in i3-tex-caddy",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(traefik_service_request_duration_seconds_bucket{kubernetes_namespace=~\"$namespace\",code=~\"(4|5).*\",app_kubernetes_io_name=\"i3-tex-caddy\"}[3m])) by (le))",
       "legendFormat": "50th percentile duration 4xx/5xx"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(traefik_service_request_duration_seconds_bucket{kubernetes_namespace=~\"$namespace\",code=~\"(4|5).*\",app_kubernetes_io_name=\"i3-tex-caddy\"}[3m])) by (le))",
       "legendFormat": "95th percentile duration 4xx/5xx"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(traefik_service_request_duration_seconds_bucket{kubernetes_namespace=~\"$namespace\",code=~\"(4|5).*\",app_kubernetes_io_name=\"i3-tex-caddy\"}[3m])) by (le))",
       "legendFormat": "99th percentile duration 4xx/5xx"
      }
     ]
    },
    {
     "title": "Median Requests Duration by Backend",
     "type": "graph",
     "description": "Average request duration by traefik in i3-tex-caddy clustered by backend service",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(traefik_service_request_duration_seconds_bucket{kubernetes_namespace=~\"$namespace\",code=~\"2.*\",app_kubernetes_io_name=\"i3-tex-caddy\"}[3m])) by (le,service))",
       "legendFormat": "{{ service }}"
      }
     ]
    }
   ]
  },
  {
   "title": "TEX-Service  ↔  OIDC Provider/Provisioning Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Outgoing Requests duration",
     "type": "graph",
     "description": "Request duration for external resources (e.g. OIDC Provider)",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tex_service_client_request_seconds_bucket{kubernetes_namespace=~\"$namespace\"}[3m])) by (host, le))",
       "legendFormat": "99th percent quantile [{{host}}]"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(tex_service_client_request_seconds_bucket{kubernetes_namespace=~\"$namespace\"}[3m])) by (host, le))",
       "legendFormat": "50th percent quantile [{{host}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "Caches",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache Hits/Sec",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "hits/sec" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tex_service_cache_hits{app_kubernetes_io_name=\"i3-tex-service\",kubernetes_namespace=~\"$namespace\", type=\"local\"}[3m]))",
       "legendFormat": "local JWT cache"
      },
      {
       "expr": "sum(rate(tex_service_cache_hits{app_kubernetes_io_name=\"i3-tex-service\",kubernetes_namespace=~\"$namespace\", type=\"external\"}[3m]))",
       "legendFormat": "external JWT cache"
      }
     ]
    },
    {
     "title": "Cache Hit Ratio",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tex_service_cache_hits{app_kubernetes_io_name=\"i3-tex-service\", kubernetes_namespace=~\"$namespace\",type=\"local\"}[3m])) / (sum(rate(tex_service_cache_hits{app_kubernetes_io_name=\"i3-tex-service\", kubernetes_namespace=~\"$namespace\",type=\"local\"}[3m])) + sum(rate(tex_service_cache_misses{app_kubernetes_io_name=\"i3-tex-service\", kubernetes_namespace=~\"$namespace\",type=\"local\"}[3m])))",
       "legendFormat": "local JWT cache"
      },
      {
       "expr": "sum(rate(tex_service_cache_hits{app_kubernetes_io_name=\"i3-tex-service\", kubernetes_namespace=~\"$namespace\",type=\"external\"}[3m])) / (sum(rate(tex_service_cache_hits{app_kubernetes_io_name=\"i3-tex-service\", kubernetes_namespace=~\"$namespace\",type=\"external\"}[3m])) + sum(rate(tex_service_cache_misses{app_kubernetes_io_name=\"i3-tex-service\", kubernetes_namespace=~\"$namespace\",type=\"external\"}[3m])))",
       "legendFormat": "external JWT cache"
      }
     ]
    },
    {
     "title": "Cache Deletions/Sec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tex_service_cache_dels{app_kubernetes_io_name=\"i3-tex-service\", kubernetes_namespace=~\"$namespace\", type=\"local\"}[3m]))",
       "legendFormat": "local JWT cache"
      },
      {
       "expr": "sum(rate(tex_service_cache_dels{app_kubernetes_io_name=\"i3-tex-service\", kubernetes_namespace=~\"$namespace\", type=\"external\"}[3m]))",
       "legendFormat": "external JWT cache"
      }
     ]
    },
    {
     "title": "Cache Entries",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tex_service_cache_entries_gauge{app_kubernetes_io_name=\"i3-tex-service\", kubernetes_namespace=~\"$namespace\",type=\"local\"}",
       "legendFormat": "local JWT cache {{kubernetes_pod_name}} "
      },
      {
       "expr": "tex_service_cache_entries_gauge{app_kubernetes_io_name=\"i3-tex-service\", kubernetes_namespace=~\"$namespace\",type=\"external\"}",
       "legendFormat": "external JWT cache {{kubernetes_pod_name}} "
      }
     ]
    }
   ]
  }
 ]
}