{
 "title": "I³ Access 5",
 "tags": [
  "i3",
  "i3-access"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(i3_access_requests_total,kubernetes_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests/Sec",
   "type": "stat",
   "description": "Incoming requests per seconds",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(i3_access_requests_total{kubernetes_namespace=~\"$namespace\", url!~\"/health|/JWKS\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage vs Limit",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name=\"i3-access\", namespace=~\"$namespace\"}[$__rate_interval])) by (pod_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_pod_container_resource_limits{namespace=~\"$namespace\", container=\"i3-access\", resource=\"cpu\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage vs Limit",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_name=\"i3-access\", namespace=~\"$namespace\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_pod_container_resource_limits{namespace=~\"$namespace\", container=\"i3-access\", unit=\"byte\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "i3-access Health",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{container=\"i3-access\", namespace=~\"$namespace\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kube_pod_container_status_waiting{container=\"i3-access\", namespace=~\"$namespace\"})",
     "legendFormat": "Waiting"
    }
   ]
  },
  {
   "title": "i3-access Restarts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container=\"i3-access\", namespace=~\"$namespace\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Image Versions",
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 4 },
   "targets": [
    {
     "expr": "kube_pod_container_info{container=\"i3-access\", namespace=~\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Count > StatusCodes",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(i3_access_requests_total{url!~\"/health|/JWKS\", kubernetes_namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by(code) (increase(i3_access_requests_total{url!~\"/health|/JWKS\", kubernetes_namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average ResponseTimes per Api",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(url) (rate(i3_access_request_duration_seconds_sum{kubernetes_namespace=~\"$namespace\"}[$__rate_interval])) / sum by(url) (rate(i3_access_request_duration_seconds_count{kubernetes_namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success/Error JWT Signings Ratio",
   "type": "piechart",
   "description": "Success/Errors Ratio of JWT Signings by i3-auth-service",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(i3_access_jwt_signings{kubernetes_namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(increase(i3_access_jwt_errors{kubernetes_namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Outgoing Requests duration",
   "type": "timeseries",
   "description": "Request duration for external resources (e.g. OIDC Provider)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(host, le) (rate(i3_access_client_request_idp_seconds_bucket{kubernetes_namespace=~\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "99th% quantile [{{host}}]"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(host, le) (rate(i3_access_client_request_idp_seconds_bucket{kubernetes_namespace=~\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "75th% quantile[{{host}}]"
    },
    {
     "expr": "histogram_quantile(1, sum by(host, le) (rate(i3_access_client_request_idp_seconds_bucket{kubernetes_namespace=~\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "100th% quantile [{{host}}]"
    }
   ]
  },
  {
   "title": "Average Outgoing Requests duration",
   "type": "timeseries",
   "description": "Request duration for external resources (e.g. OIDC Provider)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (host)(rate(i3_access_client_request_idp_seconds_sum{kubernetes_namespace=~\"$namespace\"}[$__rate_interval])) / sum by (host)(rate(i3_access_client_request_idp_seconds_count{kubernetes_namespace=~\"$namespace\"}[$__rate_interval])) ",
     "legendFormat": "avg {{host}}"
    }
   ]
  },
  {
   "title": "Caches",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Cache Hits/Sec",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "hits/sec" } },
     "targets": [
      {
       "expr": "sum(rate(i3_access_cache_hits{kubernetes_namespace=~\"$namespace\", type=\"local\"}[$__rate_interval]))",
       "legendFormat": "local JWT cache"
      },
      {
       "expr": "sum(rate(i3_access_cache_hits{kubernetes_namespace=~\"$namespace\", type=\"external\"}[$__rate_interval]))",
       "legendFormat": "external JWT cache"
      }
     ]
    },
    {
     "title": "Cache Hit Ratio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(i3_access_cache_hits{kubernetes_namespace=~\"$namespace\",type=\"local\"}[$__rate_interval])) / (sum(rate(i3_access_cache_hits{kubernetes_namespace=~\"$namespace\",type=\"local\"}[$__rate_interval])) + sum(rate(i3_access_cache_misses{kubernetes_namespace=~\"$namespace\",type=\"local\"}[$__rate_interval])))",
       "legendFormat": "local JWT cache"
      },
      {
       "expr": "sum(rate(i3_access_cache_hits{kubernetes_namespace=~\"$namespace\",type=\"external\"}[$__rate_interval])) / (sum(rate(i3_access_cache_hits{kubernetes_namespace=~\"$namespace\",type=\"external\"}[$__rate_interval])) + sum(rate(i3_access_cache_misses{kubernetes_namespace=~\"$namespace\",type=\"external\"}[$__rate_interval])))",
       "legendFormat": "external JWT cache"
      }
     ]
    },
    {
     "title": "Cache Deletions/Sec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(i3_access_cache_dels{kubernetes_namespace=~\"$namespace\", type=\"local\"}[$__rate_interval]))",
       "legendFormat": "local JWT cache"
      },
      {
       "expr": "sum(rate(i3_access_cache_dels{kubernetes_namespace=~\"$namespace\", type=\"external\"}[$__rate_interval]))",
       "legendFormat": "external JWT cache"
      }
     ]
    },
    {
     "title": "Cache Entries",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "i3_access_cache_entries_gauge{kubernetes_namespace=~\"$namespace\",type=\"local\"}",
       "legendFormat": "local JWT cache {{kubernetes_pod_name}} "
      },
      {
       "expr": "i3_access_cache_entries_gauge{kubernetes_namespace=~\"$namespace\",type=\"external\"}",
       "legendFormat": "external JWT cache {{kubernetes_pod_name}} "
      }
     ]
    }
   ]
  },
  {
   "title": "AuthZ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Policy evaluation duration",
     "type": "timeseries",
     "description": "Duration for policy evaluation",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.75, sum by(le) (rate(i3_access_authz_duration_seconds_bucket{kubernetes_namespace=~\"$namespace\"}[$__rate_interval])))",
       "legendFormat": "75th% quantile"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(i3_access_authz_duration_seconds_bucket{kubernetes_namespace=~\"$namespace\"}[$__rate_interval])))",
       "legendFormat": "99th% quantile"
      },
      {
       "expr": "histogram_quantile(1, sum by(le) (rate(i3_access_authz_duration_seconds_bucket{kubernetes_namespace=~\"$namespace\"}[$__rate_interval])))",
       "legendFormat": "100th% quantile"
      }
     ]
    },
    {
     "title": "Policy Evaluation Result Ratio",
     "type": "piechart",
     "description": "Allowed/Denied/Errors ratio of policy evaluation result",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(increase(i3_access_authz_allowed_total{kubernetes_namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "Allowed"
      },
      {
       "expr": "sum(increase(i3_access_authz_errors_total{code=\"403\", kubernetes_namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "Denied"
      },
      {
       "expr": "sum(increase(i3_access_authz_errors_total{code!=\"403\", kubernetes_namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "Error"
      }
     ]
    }
   ]
  }
 ]
}