{
 "title": "I³ K8s dhc-gp3 disk usage",
 "tags": [
  "kubernetes",
  "i3"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Current status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Quota In-Use",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(dhc-gp3_quota_volume_disk_gigabytes{quota_type=\"in-use\"})"
    }
   ]
  },
  {
   "title": "Quota Limit",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(dhc-gp3_quota_volume_disk_gigabytes{quota_type=\"limit\"})"
    }
   ]
  },
  {
   "title": "dhc-gp3 disk usage",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort_desc((1 - node_filesystem_free_bytes{pv_name!=\"\"} / node_filesystem_size_bytes + on(pv_name) group_left(pvc_name, namespace) 0 * min by(pv_name, pvc_name, namespace) (kube_persistentvolumeclaim_info{pv_name!=\"\",pvc_name!~\"lostandfound-pvc-.*\"})) * 100)",
     "legendFormat": "{{namespace}}/{{pvc_name}}"
    }
   ]
  },
  {
   "title": "Current Disk Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(dhc-gp3_volume_status) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Disk status in transition for more than 10 min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum((dhc-gp3_volume_status{status=~\".*ing\"}==1) and (rate(dhc-gp3_volume_status{status=~\".*ing\"}[10m])==0)) by (status)",
     "legendFormat": "{{ status }} 10m"
    }
   ]
  },
  { "title": "History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "dhc-gp3 disk usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sort_desc((1 - node_filesystem_free_bytes{pv_name!=\"\"} / node_filesystem_size_bytes + on(pv_name) group_left(pvc_name, namespace) 0 * min by(pv_name, pvc_name, namespace) (kube_persistentvolumeclaim_info{pv_name!=\"\",pvc_name!~\"lostandfound-pvc-.*\"})) * 100)",
     "legendFormat": "{{ namespace }}/{{ pvc_name }}"
    }
   ]
  }
 ]
}