{
 "title": "I³ k8s Pods",
 "tags": [
  "i3",
  "kubernetes",
  "pods"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{phase=\"Active\"},namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=~\"$namespace\",pod=~\"$pod\"}, container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Container Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Usage vs Limits for Containers in $pod Pod(s)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=~\"$namespace\",pod_name=~\"$pod\",container_name!=\"POD\",container_name=~\"$container\"}",
     "legendFormat": "{{container_name}} in {{pod_name}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{resource=\"memory\",unit=\"byte\", namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\"}",
     "legendFormat": "limit for {{container}} in {{pod }} "
    }
   ]
  },
  {
   "title": "CPU Usage vs Limits for Containers in $pod Pod(s)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod_name=~\"$pod\",container_name!=\"POD\",container_name=~\"$container\"}[5m])) by (pod_name,container_name)",
     "legendFormat": "{{container_name}} in {{pod_name}}"
    },
    {
     "expr": "quantile(0.5,kube_pod_container_resource_limits{resource=\"cpu\",unit=\"core\",pod=~\"$pod\", container!=\"\",container=~\"$container\"}) by (container, pod)",
     "legendFormat": "limit for {{container}} in {{pod}}"
    }
   ]
  },
  {
   "title": "Filesystem Read for Containers in $pod Pod(s)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{namespace=~\"$namespace\",pod_name=~\"$pod\",container_name!=\"POD\",container_name=~\"$container\"}[3m])) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Filesystem Write for Containers in $pod Pod(s)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{namespace=~\"$namespace\", pod_name=~\"$pod\",container_name!=\"POD\",container_name=~\"$container\"}[3m])) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  { "title": "Container Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Container Errors in $pod Pod(s)",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "kube_pod_container_status_waiting_reason{namespace=~\"$namespace\", pod=~\"$pod\"} > 0"
    }
   ]
  },
  {
   "title": "Container Restarts in $pod Pod(s) [1h]",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=~\"$namespace\", pod=~\"$pod\",container=~\"$container\"}"
    }
   ]
  },
  { "title": "Pods Network I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Incoming Traffic in $pod Pod(s) [3m]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=~\"$namespace\",pod_name=~\"$pod\"}[3m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Outgoing Traffic for $pod Pod(s) [3m]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=~\"$namespace\",pod_name=~\"$pod\"}[3m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Incoming Packets Dropped  for $pod Pod(s) [3m]",
   "type": "graph",
   "description": "Count of packets dropped while receiving.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_dropped_total{namespace=~\"$namespace\",pod_name=~\"$pod\"}[3m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Outgoing Packets Dropped  for $pod Pod(s) [3m]",
   "type": "graph",
   "description": "Count of packets dropped while receiving.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_packets_dropped_total{namespace=~\"$namespace\",pod_name=~\"$pod\"}[3m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Incoming Packets Errors for $pod Pod(s) [3m]",
   "type": "graph",
   "description": "Count of errors encountered while receiving.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_errors_total{namespace=~\"$namespace\",pod_name=~\"$pod\"}[3m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Outgoing Packets Errors for $pod Pod(s) [3m]",
   "type": "graph",
   "description": "Count of errors encountered while transmitting.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_errors_total{namespace=~\"$namespace\",pod_name=~\"$pod\"}[3m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  }
 ]
}