{
 "title": "I³ k8s Cluster",
 "tags": [
  "i3",
  "kubernetes",
  "cluster"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Pod Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=~\"(Running|Pending|Unknown)\"}) / sum(kube_node_status_allocatable{resource=\"pods\"})"
    }
   ]
  },
  {
   "title": "Cluster CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=~\"user|system\"}[3m])) / sum (machine_cpu_cores)"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes) - sum (node_memory_MemAvailable_bytes)) / sum (node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "Cluster Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (node_filesystem_size_bytes) - sum (node_filesystem_free_bytes)) / sum (node_filesystem_size_bytes)"
    }
   ]
  },
  {
   "title": "Cluster Pod Capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "pods" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"pods\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"pods\"})",
     "legendFormat": "capacity"
    },
    { "expr": "sum(kube_pod_info)", "legendFormat": "requested" }
   ]
  },
  {
   "title": "Cluster CPU Capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"cpu\",unit=\"core\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\",unit=\"core\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\",unit=\"core\"})",
     "legendFormat": "requested"
    }
   ]
  },
  {
   "title": "Cluster Mem Capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\",unit=\"byte\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"memory\",unit=\"byte\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\",unit=\"byte\"})",
     "legendFormat": "requested"
    }
   ]
  },
  {
   "title": "Cluster Disk Capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes) - sum(node_filesystem_free_bytes)",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(node_filesystem_size_bytes)",
     "legendFormat": "limit"
    }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Node Health",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "kube_node_spec_unschedulable{exported_node=~\".+\"}",
     "legendFormat": "{{ exported_node }}"
    }
   ]
  },
  {
   "title": "Nodes Out of Disk",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"OutOfDisk\", node=~\"$node\", status=\"true\"})"
    }
   ]
  },
  {
   "title": "CPU Usage Per Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum (rate (node_cpu_seconds_total{mode=~\"user|system\"}[3m])) by (kubernetes_io_hostname) / sum (machine_cpu_cores) by (kubernetes_io_hostname)",
     "legendFormat": "{{ kubernetes_io_hostname }}"
    }
   ]
  },
  {
   "title": "Memory Usage Per Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes) by (kubernetes_io_hostname) - sum (node_memory_MemAvailable_bytes) by (kubernetes_io_hostname)) / sum(node_memory_MemTotal_bytes) by (kubernetes_io_hostname)",
     "legendFormat": "{{ kubernetes_io_hostname }}"
    }
   ]
  },
  {
   "title": "Disk Usage Per Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum (node_filesystem_size_bytes) by (node) - sum (node_filesystem_free_bytes) by (node)) / sum (node_filesystem_size_bytes) by (node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Nodes Incoming Traffic [3m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total[3m])) by (kubernetes_io_hostname)",
     "legendFormat": "{{kubernetes_io_hostname}}"
    }
   ]
  },
  {
   "title": "Nodes Outgoing Traffic [3m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_transmit_bytes_total[3m])) by (kubernetes_io_hostname)",
     "legendFormat": "{{kubernetes_io_hostname}}"
    }
   ]
  },
  { "title": "Deployments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Deployment Replicas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{namespace!~\"kube-system|caas-system|kube-scan\"})"
    }
   ]
  },
  {
   "title": "Deployment Replicas - Updated",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_updated{namespace!~\"kube-system|caas-system|kube-scan\"})"
    }
   ]
  },
  {
   "title": "Deployment Replicas - Unavailable",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace!~\"kube-system|caas-system|kube-scan\"})"
    }
   ]
  },
  { "title": "Statefulsets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Statefulset Replicas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_statefulset_replicas{namespace!~\"kube-system|caas-system|kube-scan\"})"
    }
   ]
  },
  {
   "title": "Statefulset Replicas - Updated",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_statefulset_status_replicas_updated{namespace!~\"kube-system|caas-system|kube-scan\"})"
    }
   ]
  },
  {
   "title": "Statefulset Replicas - Unavailable",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_statefulset_replicas{namespace!~\"kube-system|caas-system|kube-scan\"} - kube_statefulset_status_replicas_ready{namespace!~\"kube-system|caas-system|kube-scan\"})"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Pods Running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\",namespace!~\"kube-system|caas-system|kube-scan\"})"
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Pending\",namespace!~\"kube-system|caas-system|kube-scan\"})"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Failed\",namespace!~\"kube-system|caas-system|kube-scan\"})"
    }
   ]
  },
  {
   "title": "Pods Unknown",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Unknown\",namespace!~\"kube-system|caas-system|kube-scan\"})"
    }
   ]
  },
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Containers Running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace!~\"kube-system|caas-system|kube-scan\"})"
    }
   ]
  },
  {
   "title": "Containers Waiting",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace!~\"kube-system|caas-system|kube-scan\"})"
    }
   ]
  },
  {
   "title": "Containers Terminated",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace!~\"kube-system|caas-system|kube-scan\"})"
    }
   ]
  },
  {
   "title": "Containers Restarts (Last 30 Minutes)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(kube_pod_container_status_restarts_total{namespace!~\"kube-system|caas-system|kube-scan\"}[30m]))"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "Deployment Replicas",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"kube-system|caas-system|kube-scan\"})",
       "legendFormat": "Unavailable"
      },
      {
       "expr": "sum(kube_deployment_status_replicas_updated{namespace=~\"kube-system|caas-system|kube-scan\"})",
       "legendFormat": "Updated"
      },
      {
       "expr": "sum(kube_deployment_status_replicas{namespace=~\"kube-system|caas-system|kube-scan\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Statefulset Replicas",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_statefulset_replicas{namespace=~\"kube-system|caas-system|kube-scan\"} - kube_statefulset_status_replicas_ready{namespace=~\"kube-system|caas-system|kube-scan\"})",
       "legendFormat": "Unavailable"
      },
      {
       "expr": "sum(kube_statefulset_status_replicas_updated{namespace=~\"kube-system|caas-system|kube-scan\"})",
       "legendFormat": "Updated"
      },
      {
       "expr": "sum(kube_statefulset_replicas{namespace=~\"kube-system|caas-system|kube-scan\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Pods",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{phase=\"Failed\",namespace=~\"kube-system|caas-system|kube-scan\"})",
       "legendFormat": "Failed"
      },
      {
       "expr": "sum(kube_pod_status_phase{phase=\"Pending\",namespace=~\"kube-system|caas-system|kube-scan\"})",
       "legendFormat": "Pending"
      },
      {
       "expr": "sum(kube_pod_status_phase{phase=\"Running\", namespace=~\"kube-system|caas-system|kube-scan\"})",
       "legendFormat": "Running"
      }
     ]
    },
    {
     "title": "Containers",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_terminated{namespace=~\"kube-system|caas-system|kube-scan\"})",
       "legendFormat": "Terminated"
      },
      {
       "expr": "sum(delta(kube_pod_container_status_restarts_total{namespace=~\"kube-system|caas-system|kube-scan\"}[30m]))",
       "legendFormat": "Restarts"
      },
      {
       "expr": "sum(kube_pod_container_status_running{namespace=~\"kube-system|caas-system|kube-scan\"})",
       "legendFormat": "Running"
      }
     ]
    }
   ]
  }
 ]
}