# Author: PALANSA
# This is the Data Product Service build & deploy workflow

name: CS Apps Manage

# Build is triggered either if run manually or when push happens to development branch
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      environment:
        description: 'Target environment'
        type: environment
        default: 'Development'
        required: true  
      repo:
        description: "Github repo(org/repo name)"         
      branch:
        description: "Branch to deploy it"  
        default: "main"         
      action:
        description: "Action"
        type: choice
        default: build
        required: true  
        options: 
          - build
          - deploy
          - undeploy
          - restart
      target_env:
        description: "Target Environment to deploy WS App" 
        type: choice
        required: true  
        options: 
          - 'int'
          - 'prod' 
      projectName:    
        description: 'Name of the project'
        required: true
      appVersion:    
        description: 'App New Version'
        default: "v1"
      wsid:    
        description: 'Workspace ID'
        required: true
      valutInjectorEnable:
        description: "valutInjectorEnable"  
        type: boolean
        default: false  
env:
  REGISTRY: registry-emea.app.corpintra.net
  REGISTRY_DNA_USER: robot_dnaplatform+cicdbot  
  RUNNER_ALLOW_RUNASROOT: 1

jobs:

  debug:
    name: 'Print input'
    runs-on: [road-runner, medium]
    steps:

    - name: Inputs
      run: |
        echo "environment: ${{ github.event.inputs.environment }}"
        echo "repo: ${{ github.event.inputs.repo }}"
        echo "branch: ${{ github.event.inputs.branch }}"
        echo "action: ${{ github.event.inputs.action }}"
        echo "target_env: ${{ github.event.inputs.target_env }}"
        echo "projectName: ${{ github.event.inputs.projectName }}"
        echo "appVersion: ${{ github.event.inputs.appVersion }}"
        echo "wsid: ${{ github.event.inputs.wsid }}"
        echo "valutInjectorEnable: ${{ github.event.inputs.valutInjectorEnable }}"
  
  build_deploy:
    name: 'Build or Deploy workspace application'
    if: ${{ github.event.inputs.action == 'build' ||  github.event.inputs.action == 'deploy' }}
    environment: ${{ github.event.inputs.environment }}
    runs-on: [road-runner, large]
    steps:
        
    - name: Check user repo
      uses: actions/checkout@v3
      with:
        repository: ${{ github.event.inputs.repo }}
        token: ${{ secrets.PID_PAT }}
        ref: ${{ github.event.inputs.branch }}
        path: workspace-repo
        github-server-url: "https://git.i.mercedes-benz.com/"             

    - name: Use .npmrc
      if: ${{ github.event.inputs.action == 'build' }}      
      uses: bduff9/use-npmrc@v2.0.0
      with:
        dot-npmrc: ${{ secrets.DOT_NPMRC }}
        working-directory: ./workspace-repo
        
    - name: Build application
      if: ${{ github.event.inputs.action == 'build' }}      
      working-directory: ./workspace-repo/deploy
      run: | 
       docker build -t registry-emea.app.corpintra.net/dnaplatform/code-server/codespaces-apps-${{ github.event.inputs.projectName }}:${{ github.event.inputs.appVersion }} \
        --build-arg ROOT_PATH=/${{ github.event.inputs.projectName }}/${{ github.event.inputs.target_env }}/api \
        --build-arg ROOT_PATH_NON_API=/${{ github.event.inputs.projectName }}/${{ github.event.inputs.target_env }}/ \
        --build-arg OBFUSKATOR_ARTIFACTORY_PASSWORD=${{ secrets.OBFUSKATOR_ARTIFACTORY_PASSWORD }} \
        --build-arg INDEX_URL=https://${{ secrets.ARTIFACTORY_USER }}:${{ secrets.ARTIFACTORY_PASSWORD }}@artifacts.i.mercedes-benz.com/artifactory/api/pypi/pypi-opensource-virtual/simple \
        -f build.Dockerfile --no-cache ../
      env:
        no_proxy: "artifacts.i.mercedes-benz.com"     
    
    - name: Publish application containers to registry
      if: ${{ github.event.inputs.action == 'build' }}    
      run: |
        echo ${{ secrets.HARBOR_DNA_REPO_SECRET }} | docker login $REGISTRY -u $REGISTRY_DNA_USER --password-stdin
        docker push registry-emea.app.corpintra.net/dnaplatform/code-server/codespaces-apps-${{ github.event.inputs.projectName }}:${{ github.event.inputs.appVersion }}     

    - name: Deploy App
      uses: vimeda/helm@v1.7.0
      if: ${{ github.event.inputs.action == 'deploy' }}
      with:
        release: '${{ github.event.inputs.projectName }}-${{ github.event.inputs.target_env }}'
        namespace: 'codespaces-apps'
        chart: 'workspace-repo/deploy/helm'
        values: |
          fullnameOverride: ${{ github.event.inputs.projectName }}-${{ github.event.inputs.target_env }}
          namespace: codespaces-apps
          image:
            repository: registry-emea.app.corpintra.net/dnaplatform/code-server/codespaces-apps-${{ github.event.inputs.projectName }}
            tag: ${{ github.event.inputs.appVersion }}
          imagePullSecrets: 
            - name: imagepullsecret
          vaultInjector:
            enable: ${{ github.event.inputs.valutInjectorEnable }}
            path: kv/${{ github.event.inputs.projectName }}/${{ github.event.inputs.target_env }}
            root_path: /${{ github.event.inputs.projectName }}/${{ github.event.inputs.target_env }}/api    
            root_path_non_api: /${{ github.event.inputs.projectName }}/${{ github.event.inputs.target_env }}/
            authpath: ${{ vars.VAULT_AUTH_PATH }}
            namespace: ${{ vars.VAULT_NAMESPACE }}
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'

  upload-build_deploy-logs-to-opensearch:
    name: "Upload Logs to Opensearch" 
    runs-on: [road-runner, medium]
    environment: ${{ github.event.inputs.environment }}
    needs: build_deploy
    if: ${{ !cancelled() && (success() || failure())}}
    steps:    
      - name: Upload GitHub Action workflows logs to opensearch
        uses: sathishkumar-p/upload-github-workflow-logs-to-opensearch@v5
        with:
          github_token: "${{ secrets.PID_PAT }}"
          github_org: "DNA"
          github_repository: "NeuDnAPlatform"
          github_run_id: "${{ github.run_id }}"
          github_host_api: "https://git.i.mercedes-benz.com/api/v3"
          opensearch_username: "${{ secrets.OPENSEARCH_USERNAME }}"
          opensearch_password: "${{ secrets.OPENSEARCH_PASSWORD }}"
          opensearch_host: "${{ vars.OPENSEARCH_HOST }}"
          opensearch_index: "ci-cd"  

  statusUpdateBuildDeploy:
    name: Update Status build_deploy
    needs: build_deploy
    if: ${{ !cancelled() && (success() || failure())}}
    uses: ./.github/workflows/cs-status-update.yml
    with:
      status: '${{ needs.build_deploy.result }}'
      action: ${{ github.event.inputs.action }}
      environment: ${{ github.event.inputs.environment }}
      projectName: ${{ github.event.inputs.projectName }}
      target_env: ${{ github.event.inputs.target_env }}
      branch: ${{ github.event.inputs.branch }}
      wsid: ${{ github.event.inputs.wsid }}
    secrets:
      PAT: ${{ secrets.PID_PAT }}
      CS_STATUS_UPDATE_DOMAIN: ${{ secrets.CS_STATUS_UPDATE_DOMAIN }}

  undeploy:
    name: 'Delete Code Server Workspace'
    if: ${{ github.event.inputs.action == 'undeploy'}}
    environment: ${{ github.event.inputs.environment }}
    runs-on: [road-runner, medium]

    steps:
      - name: 'Delete Code Server Apps'
        uses: 'vimeda/helm@v1.7.0'
        with:
          task: 'remove'
          chart: 'workspace-application-0.1.0'
          release: '${{ github.event.inputs.projectName }}-${{ github.event.inputs.target_env }}'
          namespace: 'codespaces-apps'
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'             

  statusUpdateUndeploy:
    name: Update Status Undeploy
    needs: undeploy
    if: ${{ !cancelled() && (success() || failure())  && github.event.inputs.action == 'undeploy' }}    
    uses: ./.github/workflows/cs-status-update.yml
    with:
      status: '${{ needs.undeploy.result }}'
      action: ${{ github.event.inputs.action }}
      environment: ${{ github.event.inputs.environment }}
      target_env: ${{ github.event.inputs.target_env }}
      projectName: ${{ github.event.inputs.projectName }}
      branch: ${{ github.event.inputs.branch }}
      wsid: ${{ github.event.inputs.wsid }}
    secrets:
      PAT: ${{ secrets.PID_PAT }}
      CS_STATUS_UPDATE_DOMAIN: ${{ secrets.CS_STATUS_UPDATE_DOMAIN }}

  restart:
    name: 'Restart Code Server Workspace'
    if: ${{ github.event.inputs.action == 'restart'}}
    environment: ${{ github.event.inputs.environment }}
    runs-on: [road-runner, medium]

    steps:
        
      - uses: actions-hub/kubectl@v1.30.3
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG_BASE64 }}
        with:
          args: rollout restart deployment ${{ github.event.inputs.projectName }}-${{ github.event.inputs.target_env }} --namespace=codespaces-apps

  statusUpdateRestart:
    name: Update Status restart
    needs: restart
    if: ${{ !cancelled() && (success() || failure())  && github.event.inputs.action == 'restart' }}    
    uses: ./.github/workflows/cs-status-update.yml
    with:
      status: '${{ needs.restart.result }}'
      wsid: '${{ github.event.inputs.wsid }}'
      shortid: '${{ github.event.inputs.shortid }}'
      action: ${{ github.event.inputs.action }}
      environment: ${{ github.event.inputs.environment }}
      target_env: ${{ github.event.inputs.target_env }}
      branch: ${{ github.event.inputs.branch }}
    secrets:
      PAT: ${{ secrets.PID_PAT }}
      CS_STATUS_UPDATE_DOMAIN: ${{ secrets.CS_STATUS_UPDATE_DOMAIN }}

  sonar-qube-gradle:
    name: Sonar Qube Scan Gradle
    needs: build_deploy
    if: ${{ github.event.inputs.projectName == 'fc-cockpit-backend' }}
    runs-on: [ medium ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Check user repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.repo }}
          token: ${{ secrets.PID_PAT }}
          ref: ${{ github.event.inputs.branch }}
          path: workspace-repo
          github-server-url: "https://git.i.mercedes-benz.com/"           
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 7.4.1      
          cache-overwrite-existing: true   
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build and analyze
        working-directory: ./workspace-repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        # run: ls && chmod +x gradlew && ./gradlew build sonarqube --info
        run: gradle build sonarqube --info

  sonar-qube-js:
    name: Sonar Qube Scan Javascript
    needs: build_deploy
    if: ${{ github.event.inputs.projectName == 'fc-cockpit-frontend' }}
    runs-on: [ medium ]
    steps:
      - name: Check user repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.repo }}
          token: ${{ secrets.PID_PAT }}
          ref: ${{ github.event.inputs.branch }}
          github-server-url: "https://git.i.mercedes-benz.com/"    
          fetch-depth: 0       

      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
