name: Git Sync
on:
  workflow_dispatch:
    inputs:
      publicBranch:
        description: 'Public Branch name'
        required: true  
      privateBranch:
        description: 'Private Branch name'
        default: dev
        required: true         
        type: choice
        options: 
          - dev
          - staging
          - main         
  workflow_call:
    inputs:
      isSync:
        required: true
        type: string
        default: 'yes'
    secrets:
      PID_PAT:
        required: true  
env:
  PUBLIC_SRC_REPO: https://github.com/mercedes-benz/DnA.git
  DEST_REPO: git.i.mercedes-benz.com/DNA/DnA-Private.git
  # DEST_STAGING_BRANCH: staging-gitsync

jobs:
  gitsync:
    name: "Git Sync"
    if: ${{ inputs.isSync == 'yes' || ( github.event_name == 'workflow_dispatch' && inputs.isSync == '' ) }}
    runs-on: [ road-runner, self-hosted ]
    steps:

      - name: Check Source Branch
        run: |
          if [[ "${{ github.event.inputs.publicBranch }}" == *"feature"* ]]; then
            echo "Public Branch name: ${{ github.event.inputs.publicBranch }}"
          else
            echo "Public Branch name does not valid"
            echo "Given Branch name: ${{ github.event.inputs.publicBranch }}"
            exit 1
          fi

      # - uses: actions/checkout@v3

      # - name: Clone changes from public repo branch to private branch
      #   working-directory: ./utils/gitsync/
      #   run: |
      #     chmod +x ./gitsync
      #     ./gitsync
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.PID_PAT }}
      #     PUBLIC_SRC_BRANCH:  ${{ github.event.inputs.publicBranch }}
      #     DEST_BRANCH: ${{ github.event.inputs.privateBranch }}
      #     DEST_STAGING_BRANCH: ${{ github.event.inputs.privateBranch }}
      

      - name: Sync code with Public repo
        uses: wei/git-sync@v3
        with:
          source_repo: "$PUBLIC_SRC_REPO"
          source_branch: "${{ github.event.inputs.publicBranch }}"
          destination_repo: "https://${{ secrets.PID_PAT }}@$DEST_REPO"
          destination_branch: "${{ github.event.inputs.publicBranch }}"

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: '${{ github.event.inputs.publicBranch }}'  

      - name: Debug
        run: |
          echo "${{toJSON(github.event)}}"
          echo "head_commit -${{ github.event.head_commit.message }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.html_url }}"              

      - name: Create pull request
        uses: thomaseizinger/create-pull-request@master
        id: cpr
        with:
          github_token: ${{ secrets.PID_PAT }}
          head: ${{ github.event.inputs.publicBranch }}
          base: ${{ github.event.inputs.privateBranch }}
          reviewers: "palansa"
          labels: "automatic,feature"
          title: "${{ github.event.head_commit.message }}"

      # - name: pull-request
      #   id: cpr
      #   uses: diillson/auto-pull-request@v1.0.1
      #   env:
      #     GITHUB_SERVER_URL: "https://git.i.mercedes-benz.com"
      #   with:
      #     source_branch: "${{ github.event.inputs.publicBranch }}"  
      #     destination_repository: "https://git.i.mercedes-benz.com/DNA/DnA-Private"                             # If blank, default: triggered branch
      #     destination_branch: "${{ github.event.inputs.privateBranch }}"                      # If blank, default: master
      #     pr_title: "${{ github.event.commits[0].message }}" # Title of pull request
      #     pr_reviewer: "palansa"                         # Comma-separated list (no spaces)
      #     pr_assignee: "palansa"                         # Comma-separated list (no spaces)
      #     pr_label: "automatic,feature"                               # Comma-separated list (no spaces)
      #     pr_draft: false                                    # Creates pull request as draft
      #     pr_allow_empty: false                              # Creates pull request even if there are no changes
      #     github_token: ${{ secrets.PID_PAT }}      # If blank, default: secrets.GITHUB_TOKEN
      #     debug: true             

      - name: Pull Request URL
        if: ${{ steps.cpr.outputs.number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.html_url }}"
            
      - uses: peter-evans/enable-pull-request-automerge@v3
        if: ${{ steps.cpr.outputs.number }}
        with:
          token: ${{ secrets.PID_PAT }}
          pull-request-number: ${{ steps.cpr.outputs.number }}
              

  success:
  #To avoid skipping other dependent job, just running cmd to make job success.
    name: "Make job success"
    needs: gitsync
    if: always() && needs.gitsync.result == 'skipped'
    runs-on: [ road-runner, self-hosted ]
    steps:

      - name: Success
        run: |
          echo "Success"  
