name: Migrate Harbor Registry

on:
  workflow_dispatch:
    inputs:
      dest:
        description: "destination to push image"
        required: true
        default: "registry-emea.app.corpintra.net/dnaplatform"
      page:
        description: "Page Number"
        required: true
        default: "1"
      page_size:
        description: "Size of page"
        required: true
        default: "10"                     
env:
  REGISTRY_DNA_USER: robot_dnaplatform+cicdbot  
  REGISTRY_NEW_DNA_USER: robot_dnaplatform+cicdbot  


jobs:


  getrepo:
    name: 'Get Repo List'
    runs-on: [road-runner, medium]
    outputs:
        matrix: ${{ steps.getrepo.outputs.response }}
    steps:

      - name: Get Repos
        id: getrepo
        uses: CamiloGarciaLaRotta/watermelon-http-client@v1.6
        with:
          url: 'https://registry.app.corpintra.net/api/v2.0/projects/dna/repositories?page=${{ github.event.inputs.page }}&page_size=${{ github.event.inputs.page_size }}'
          method: 'GET'
          headers: '{"Content-Type": "application/json", "Accept": "*/*", "X-Request-Id": "PALANSA:${{ secrets.HARBOR_PALANSA_SECRET }}"}'
          fail_fast: false
          verbose: true
        env:
          no_proxy: "registry.app.corpintra.net"     


  migrate:
    name: 'Migrate the image'
    runs-on: [road-runner, medium]
    needs: getrepo
    strategy:
      max-parallel: 2
      matrix: 
        input: ${{ fromJson(needs.getrepo.outputs.matrix) }} 

    steps:

    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Run skopeo migration
      run: | 
        rm -f ./src.yml
        printf "registry.app.corpintra.net:\n   images-by-tag-regex:\n      ${{ matrix.input.name }}: ^.{1,39}$" >> src.yml      
        if [[ ${{ matrix.input.name }} == *"/"*"/"* ]]; then
          output_string=$(echo "${{ matrix.input.name }}" | sed 's/^dna\///;s/\/[^/]*$//')
        fi
        echo "Migrating repo: $output_string"
        docker run -v ./src.yml:/tmp/src.yml registry.app.corpintra.net/dna/skopeo:latest sync --src yaml --dest docker --src-username PALANSA --src-password ${{ secrets.HARBOR_PALANSA_SECRET }} --dest-username ${{ env.REGISTRY_NEW_DNA_USER }} --dest-password ${{ secrets.NEW_REPO_SECRET }} /tmp/src.yml ${{ github.event.inputs.dest }}//$output_string
        rm -f ./src.yml