## Author: PALANSA
name: Update DnAPlatform Repo
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0/1 * * *' # every day at midnight     

jobs:


  update-repo:
    name: 'Make Public'
    runs-on: [ self-hosted ]


    steps:
      - name: Change Visibility 
        run: |
          gh repo edit DNA/DnAPlatform --visibility=public
        env:
          GH_ENTERPRISE_TOKEN: ${{ secrets.PID_PAT }}
          GH_HOST: git.i.mercedes-benz.com

 
