name: sonarqube-build-testing 

# Build is triggered either if run manually or when push happens to development branch
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target build environment"
        type: environment
        required: true
        default: 'Development'

  # push:
  #   branches:
  #     - dev
  #   paths-ignore:
  #     - 'deployment/helm/**'
  # pull_request:
  #   types:
  #     - closed
  #   branches:
  #     - 'dev'
  #     - 'staging'
  #     - 'main'

env:
  REGISTRY: registry-emea.app.corpintra.net
  REGISTRY_DNA_USER: ADEVALL 
  NO_PROXY: ''
  RUNNER_ALLOW_RUNASROOT: 1
  IMAGE_NAME: registry-emea.app.corpintra.net/dnaplatform/storage-be
  IMAGE_TAG_PATH: image.tag
  BLACKDUCK_URL: https://bdscan.i.mercedes-benz.com/
  BLACKDUCK_PROJECT_NAME: StorageBE
  BLACKDUCK_SOURCE_PATH: storage-lib

jobs: 

  build:
    name: 'Build App'
    needs: sonarqube
    if: github.event_name == 'push' || github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: [ dot-enterprise-runner ]
    outputs:
      version: ${{ steps.updated.outputs.version }}
    steps:

    - name: Check out repository code
      uses: actions/checkout@v3
        
    - name: Login Registry
      run: | 
        echo ${{ secrets.HARBOR_DNA_REPO_SECRET }} | img login $REGISTRY -u $REGISTRY_DNA_USER --password-stdin


    # - name: Override files & Login Registry
    #   run: | 
    #     echo ${{ secrets.HARBOR_DNA_REPO_SECRET }} | img login $REGISTRY -u $REGISTRY_DNA_USER --password-stdin
    #     chmod +x ./utils/gitFileOverride/fileOverride.sh
    #     ./utils/gitFileOverride/fileOverride.sh 

    - name: Build Application Containers
      working-directory: ./deployment
      run: | 
        img build \
          -t $IMAGE_NAME:${{ github.sha }} -e SONAR_TOKEN="" -e SONAR_HOST_URL=https://fmas-sonar.dot.i.mercedes-benz.com \
          -f storage-be.Dockerfile ../
        img --help
        img create --name temp_container $IMAGE_NAME:${{ github.sha }}
        img cp temp_container:report-task.txt report-task.txt
        img rm temp_container
       
