name: Testing FC_OS AKS deploy 

on: workflow_dispatch


jobs:

  deploy:
    name: 'Deploying in FC_OS AKS'
    environment: Azure_FC_OS
    runs-on: [ large ]



    steps:   

    - name: Check out repository code
      uses: actions/checkout@v3
      
    - name: loading the env variables
      run: |
      env:
        HTTP_PROXY: ${{ secrets.HTTP_PROXY }}
        HTTPS_PROXY: ${{ secrets.HTTPS_PROXY }}
        NO_PROXY: ${{ secrets.NO_PROXY }}
        #http_proxy: ${{ secrets.HTTP_PROXY }}
        #https_proxy: ${{ secrets.HTTPS_PROXY }}
        #no_proxy: ${{ secrets.NO_PROXY }}

    - name: Deploy App
      uses: vimeda/helm@v1.7.0
      with:
        release: 'testing-aks-dss-mfe'
        namespace: 'testing-aks-dss'
        chart: '/home/runner/actions-runner/_work/dna-dss-mfe/dna-dss-mfe/deployment/helm'
        values: |
          image:
            repository: fcosacr.azurecr.io/fcosacr/dss-mfe/testing
            tag: 61b0c50b1abd94b53ef9e53c911ab805b935fa3f
        value-files: '/home/runner/actions-runner/_work/dna-dss-mfe/dna-dss-mfe/deployment/helm/values-testing-aks.yaml'
      env:
        KUBECONFIG_FILE: '${{ secrets.AZURE_KUBECONFIG }}'
