
name: Trigger Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target build environment"
        type: environment
        required: true
        default: 'Development'      

  pull_request:
    types:
      - closed
    branches:
      - 'dev'
      - 'staging'
      - 'main'
    paths:
      - 'packages/**'   
      - 'deployment/dockerfiles/**'   

jobs: 
          
  select-service:
    name: 'Detect changes in the service files'
    runs-on: [road-runner, medium]
    outputs:
      code-server: ${{ steps.filter.outputs.code-server }}    
      chronos-mfe: ${{ steps.filter.outputs.chronos-mfe }}
      code-space-mfe: ${{ steps.filter.outputs.code-space-mfe }}    
    permissions:
      pull-requests: read    
      contents: read
      packages: write   
      actions: write   
      checks: write            
    steps:

      # For pull requests it's not necessary to checkout the code
      - name: checkout 
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3.0.2
        id: filter
        with:
          filters: |
            code-server: 
              - 'packages/code-server/**'
              - 'deployment/dockerfiles/codeServer/cs-backend.Dockerfile'
            chronos-mfe: 
              - 'packages/chronos-mfe/**'
              - 'deployment/dockerfiles/chronosService/chronos-mfe.Dockerfile'
            code-space-mfe: 
              - 'packages/code-server/**'
              - 'deployment/dockerfiles/codeServer/code-space-mfe.Dockerfile'

  code-server:
        name: Code Server Backend
        needs: select-service
        if: needs.select-service.outputs.code-server == 'true'
        uses: ./.github/workflows/deploy.yaml
        with:
          IMAGE_NAME: 'registry-emea.app.corpintra.net/dnaplatform/code-server-be'
          DOCKER_FILE_PATH: 'codeServer/cs-backend.Dockerfile'
          DETECT_PROJECT_NAME: 'CodeServerBE'
          IS_OVERRIDE_REQUIRED: true
          ENVIRONMENT: ${{ github.event.inputs.environment }}
          IS_REACT_APP: false
          CODE_FOLDER: 'packages/code-server'
          APP_VERSION_FILE_PATH: 'packages/code-server/code-server-lib/src/main/resources/application.yml'
          HELM_FOLDER: 'deployment/kubernetes/helm/charts/code-server-backend'
          YML_IMAGE_TAG_PATH: 'image.tag' 
        secrets: inherit

  chronos-mfe:
        name: Chronos MFE
        needs: select-service
        if: needs.select-service.outputs.chronos-mfe == 'true'
        uses: ./.github/workflows/deploy.yaml
        with:
          IMAGE_NAME: 'registry-emea.app.corpintra.net/dnaplatform/chronos-mfe'
          DOCKER_FILE_PATH: 'chronosService/chronos-mfe.Dockerfile'
          DETECT_PROJECT_NAME: 'ChronosMFE'
          IS_OVERRIDE_REQUIRED: false
          ENVIRONMENT: ${{ github.event.inputs.environment }}
          IS_REACT_APP: true
          CODE_FOLDER: 'packages/chronos-mfe'
          APP_VERSION_FILE_PATH: 'packages/chronos-mfe/package.json'
          HELM_FOLDER: 'deployment/kubernetes/helm/charts/chronos-mfe'
          YML_IMAGE_TAG_PATH: 'image.tag' 
        secrets: inherit
  code-space-mfe:
        name: code-space-mfe
        needs: select-service
        if: needs.select-service.outputs.code-space-mfe == 'true'
        uses: ./.github/workflows/deploy.yaml
        with:
          IMAGE_NAME: 'registry-emea.app.corpintra.net/dnaplatform/codepsace-mfe'
          DOCKER_FILE_PATH: 'codeServer/code-space-mfe.Dockerfile'
          DETECT_PROJECT_NAME: 'codespace-mfe'
          IS_OVERRIDE_REQUIRED: false
          ENVIRONMENT: ${{ github.event.inputs.environment }}
          IS_REACT_APP: true
          CODE_FOLDER: 'packages/chronos-mfe'
          APP_VERSION_FILE_PATH: 'packages/code-space-mfe/package.json'
          HELM_FOLDER: 'deployment/kubernetes/helm/charts/code-space-mfe'
          YML_IMAGE_TAG_PATH: 'image.tag' 
        secrets: inherit      
