
name: Trigger Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target build environment"
        type: environment
        required: true
        default: 'Development'
      # service:
      #   description: 'Service to deploy'
      #   default: code-server
      #   required: true         
      #   type: choice
      #   options: 
      #     - code-server
      #     - dna-frontend
      #     - dna-backend         

  # push:
  #   branches:
  #     - dev
  #   paths:
  #     - 'packages/**'
  pull_request:
    types:
      - closed
    branches:
      - 'dev'
      - 'staging'
      - 'main'
    paths:
      - 'packages/**'      

env:
  REGISTRY: registry-emea.app.corpintra.net
  REGISTRY_DNA_USER: robot_dnaplatform+cicdbot 
  NO_PROXY: ''
  RUNNER_ALLOW_RUNASROOT: 1
  IMAGE_NAME: registry-emea.app.corpintra.net/dnaplatform/code-server-be
  IMAGE_TAG_PATH: image.tag
  DOCKER_FILE_PATH: dockerfiles/cs-backend.Dockerfile
  BLACKDUCK_URL: https://bdscan.i.mercedes-benz.com/
  DETECT_PROJECT_NAME: CodeServerBE
  # DETECT_SOURCE_PATH: <<<<fill-it>>>>>  # comment the line if path is root
  SECHUB_USERID: pid6c39
  SECHUB_SERVER: https://sechub.app.corpintra.net

jobs: 

    # changes:
    #   name: 'Detect Changes'
    #   runs-on: [road-runner, medium]
    #   # Required permissions
    #   permissions:
    #     pull-requests: read
    #   outputs:
    #     # Expose matched filters as job 'packages' output variable
    #     packages: ${{ steps.filter.outputs.changes }}
    #   steps:
      
    #   # For pull requests it's not necessary to checkout the code
    #   - name: checkout 
    #     if: ${{ github.event_name == 'workflow_dispatch' }}
    #     uses: actions/checkout@v4

    #   - uses: dorny/paths-filter@v3.0.2
    #     id: filter
    #     with:
    #       filters: |
    #         package1: src/package1
    #         package2: src/package2
          
  select-service:
    name: 'Select Service to Deploy'
    runs-on: [road-runner, medium]
    permissions:
      pull-requests: read    
    steps:

      # For pull requests it's not necessary to checkout the code
      - name: checkout 
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v3.0.2
        id: filter
        with:
          filters: |
            code-server: packages/code-server
            chronos-mfe: packages/chronos-mfe

      - name: Debug
        run: |
          echo  "${{ steps.filter.outputs }}"
          echo  "${{ steps.filter.outputs.code-server }}"
          echo  "${{ steps.filter.outputs.chronos-mfe }}"

      - name: Code Server
        if: steps.filter.outputs.code-server == 'true'
        run: |
          echo  "Code-server Folder"

