schedule: <path:dna_kv/data/dev/kubernetesSecret/vaultBackup#schedule>
restartPolicy: OnFailure
successfulJobsHistoryLimit: 1
namespace: vault

backup:
  image:
    name: registry-emea.app.corpintra.net/dnaplatform/vault/medusa
    tag: latest
    pullPolicy: IfNotPresent

  #Add new env as array value with name/value field. Keep one tab indentation.
  envs:
    - name: VAULT_SKIP_VERIFY
      value: "true"
    - name: VAULT_ADDR
      value: <path:dna_kv/data/dev/kubernetesSecret/vaultBackup#address>
    - name: VAULT_PATH
      value: <path:dna_kv/data/dev/kubernetesSecret/vaultBackup#path>
    - name: VAULT_TOKEN
      value: <path:dna_kv/data/dev/kubernetesSecret/vaultBackup#token>

minio:
  image:
    name: registry-emea.app.corpintra.net/dnaplatform/minio/minio-client
    tag: 2022.1.25-debian-10-r2
    pullPolicy: IfNotPresent
  bucket: <path:dna_kv/data/dev/kubernetesSecret/vaultBackup#bucket>
  endpoint: <path:dna_kv/data/dev/kubernetesSecret/vaultBackup#endpoint>
  accessKey: <path:dna_kv/data/dev/kubernetesSecret/vaultBackup#accessKey>
  secretKey: <path:dna_kv/data/dev/kubernetesSecret/vaultBackup#secretKey>
  fileName: <path:dna_kv/data/dev/kubernetesSecret/vaultBackup#fileName>